from tensorflow.python.keras.saving.saved_model import json_utils as json_utils
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any

def model_from_config(config, custom_objects: Any | None = ...): ...
def model_from_yaml(yaml_string, custom_objects: Any | None = ...) -> None: ...
def model_from_json(json_string, custom_objects: Any | None = ...): ...
