from statsmodels.tsa.tsatools import freq_to_period as freq_to_period
from typing import Any

def pandas_wrapper(func, trim_head: Any | None = ..., trim_tail: Any | None = ..., names: Any | None = ..., *args, **kwargs): ...
def pandas_wrapper_bunch(func, trim_head: Any | None = ..., trim_tail: Any | None = ..., names: Any | None = ..., *args, **kwargs): ...
def pandas_wrapper_predict(func, trim_head: Any | None = ..., trim_tail: Any | None = ..., columns: Any | None = ..., *args, **kwargs) -> None: ...
def pandas_wrapper_freq(func, trim_head: Any | None = ..., trim_tail: Any | None = ..., freq_kw: str = ..., columns: Any | None = ..., *args, **kwargs): ...
