import collections.abc
from typing import Any

class OrderPreservingSet(collections.abc.MutableSet):
    def __init__(self, iterable: Any | None = ...) -> None: ...
    def __len__(self): ...
    def __contains__(self, value): ...
    def __iter__(self): ...
    def add(self, item) -> None: ...
    def discard(self, value) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def union(self, other): ...
