from tensorflow.python.framework import dtypes as dtypes, indexed_slices as indexed_slices, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_ragged_conversion_ops as gen_ragged_conversion_ops, math_ops as math_ops
from tensorflow.python.ops.ragged import ragged_tensor as ragged_tensor
from typing import Any

def from_tensor(tensor, lengths: Any | None = ..., padding: Any | None = ..., ragged_rank: int = ..., row_splits_dtype=..., name: Any | None = ...): ...
def to_tensor(rt_input, default_value: Any | None = ..., name: Any | None = ...): ...
def ragged_to_dense(rt_input, default_value: Any | None = ..., shape: Any | None = ...): ...
def to_sparse(rt_input, name: Any | None = ...): ...
def from_sparse(st_input, name: Any | None = ...): ...
