from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_shape as tensor_shape, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.ops.ragged import ragged_array_ops as ragged_array_ops, ragged_config as ragged_config, ragged_tensor as ragged_tensor, ragged_util as ragged_util
from typing import Any

class RaggedTensorDynamicShape:
    def __init__(self, partitioned_dim_sizes, inner_dim_sizes, dim_size_dtype: Any | None = ...) -> None: ...
    @staticmethod
    def from_dim_sizes(dim_sizes): ...
    @classmethod
    def from_tensor(cls, rt_input, dim_size_dtype: Any | None = ...): ...
    def dimension_size(self, axis): ...
    def is_ragged(self, axis): ...
    @property
    def rank(self): ...
    @property
    def partitioned_dim_sizes(self): ...
    @property
    def inner_dim_sizes(self): ...
    @property
    def num_partitioned_dimensions(self): ...
    @property
    def num_inner_dimensions(self): ...
    @property
    def dim_size_dtype(self): ...
    def broadcast_to_rank(self, rank): ...
    def broadcast_dimension(self, axis, lengths): ...
    def num_slices_in_dimension(self, axis): ...
    def with_dim_size_dtype(self, dtype): ...

def broadcast_dynamic_shape(shape_x, shape_y): ...
def broadcast_to(rt_input, shape, broadcast_inner_dimensions: bool = ...): ...
