from tensorflow.python.util import tf_contextlib as tf_contextlib
from tensorflow.python.util.tf_export import tf_export as tf_export

def forward_compatible(year, month, day): ...
def forward_compatibility_horizon(year, month, day) -> None: ...
