import unittest

from _typeshed import Incomplete

from ...testing import data_path as data_path
from ...testing import error_warnings as error_warnings
from ..array_sequence import ArraySequence as ArraySequence
from ..tck import TckFile as TckFile
from ..tractogram import Tractogram as Tractogram
from ..tractogram_file import DataError as DataError
from ..tractogram_file import HeaderError as HeaderError
from ..tractogram_file import HeaderWarning as HeaderWarning
from .test_tractogram import assert_tractogram_equal as assert_tractogram_equal

DATA: Incomplete

def setup_module() -> None: ...

class TestTCK(unittest.TestCase):
    def test_load_empty_file(self) -> None: ...
    def test_load_no_magic_number_file(self) -> None: ...
    def test_load_no_header_end_file(self) -> None: ...
    def test_load_no_header_end_eof_file(self) -> None: ...
    def test_load_simple_file(self) -> None: ...
    def test_load_matlab_nan_file(self) -> None: ...
    def test_load_multiline_header_file(self) -> None: ...
    def test_writeable_data(self) -> None: ...
    def test_load_simple_file_in_big_endian(self) -> None: ...
    def test_load_file_with_wrong_information(self) -> None: ...
    def test_write_empty_file(self) -> None: ...
    def test_write_simple_file(self) -> None: ...
    def test_write_bigheader_file(self) -> None: ...
    def test_load_write_file(self) -> None: ...
    def test_str(self) -> None: ...
