import unittest

from _typeshed import Incomplete
from nibabel.testing import clear_and_catch_warnings as clear_and_catch_warnings
from nibabel.testing import data_path as data_path
from nibabel.testing import error_warnings as error_warnings
from nibabel.tmpdirs import InTemporaryDirectory as InTemporaryDirectory

from .. import FORMATS as FORMATS
from .. import trk as trk
from ..tractogram import LazyTractogram as LazyTractogram
from ..tractogram import Tractogram as Tractogram
from ..tractogram_file import ExtensionWarning as ExtensionWarning
from ..tractogram_file import TractogramFile as TractogramFile
from .test_tractogram import assert_tractogram_equal as assert_tractogram_equal

DATA: Incomplete

def setup() -> None: ...
def test_is_supported_detect_format(tmp_path) -> None: ...

class TestLoadSave(unittest.TestCase):
    def test_load_empty_file(self) -> None: ...
    def test_load_simple_file(self) -> None: ...
    def test_load_complex_file(self) -> None: ...
    def test_save_tractogram_file(self) -> None: ...
    def test_save_empty_file(self) -> None: ...
    def test_save_simple_file(self) -> None: ...
    def test_save_complex_file(self) -> None: ...
    def test_save_sliced_tractogram(self) -> None: ...
    def test_load_unknown_format(self) -> None: ...
    def test_save_unknown_format(self) -> None: ...
    def test_save_from_generator(self): ...
