from keras import backend as backend
from keras.engine import base_layer_utils as base_layer_utils
from keras.mixed_precision import device_compatibility_check as device_compatibility_check
from keras.utils import generic_utils as generic_utils
from typing import Any

class Policy:
    def __init__(self, name) -> None: ...
    @property
    def variable_dtype(self): ...
    @property
    def compute_dtype(self): ...
    @property
    def name(self): ...
    def get_config(self): ...
    @classmethod
    def from_config(cls, config, custom_objects: Any | None = ...): ...

class PolicyV1(Policy):
    def __init__(self, name, loss_scale: str = ...) -> None: ...
    @property
    def loss_scale(self): ...
    def get_config(self): ...
    @classmethod
    def from_config(cls, config, custom_objects: Any | None = ...): ...

def global_policy(): ...
def set_global_policy(policy) -> None: ...
def policy_scope(policy) -> None: ...
def serialize(policy): ...
def deserialize(config, custom_objects: Any | None = ...): ...
