from tensorflow.python._pywrap_mlir import *
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.eager import context as context
from typing import Any

def import_graphdef(graphdef, pass_pipeline, show_debug_info, input_names: Any | None = ..., input_data_types: Any | None = ..., input_data_shapes: Any | None = ..., output_names=...): ...
def import_function(concrete_function, pass_pipeline, show_debug_info): ...
def experimental_convert_saved_model_to_mlir(saved_model_path, exported_names, show_debug_info): ...
def experimental_convert_saved_model_v1_to_mlir_lite(saved_model_path, exported_names, tags, upgrade_legacy, show_debug_info): ...
def experimental_convert_saved_model_v1_to_mlir(saved_model_path, exported_names, tags, lift_variables, upgrade_legacy, show_debug_info): ...
def experimental_run_pass_pipeline(mlir_txt, pass_pipeline, show_debug_info): ...
