from typing import Any

def GPA(A, ff: Any | None = ..., vgQ: Any | None = ..., T: Any | None = ..., max_tries: int = ..., rotation_method: str = ..., tol: float = ...): ...
def Gf(T, ff): ...
def rotateA(A, T, rotation_method: str = ...): ...
def oblimin_objective(L: Any | None = ..., A: Any | None = ..., T: Any | None = ..., gamma: int = ..., rotation_method: str = ..., return_gradient: bool = ...): ...
def orthomax_objective(L: Any | None = ..., A: Any | None = ..., T: Any | None = ..., gamma: int = ..., return_gradient: bool = ...): ...
def CF_objective(L: Any | None = ..., A: Any | None = ..., T: Any | None = ..., kappa: int = ..., rotation_method: str = ..., return_gradient: bool = ...): ...
def vgQ_target(H, L: Any | None = ..., A: Any | None = ..., T: Any | None = ..., rotation_method: str = ...): ...
def ff_target(H, L: Any | None = ..., A: Any | None = ..., T: Any | None = ..., rotation_method: str = ...): ...
def vgQ_partial_target(H, W: Any | None = ..., L: Any | None = ..., A: Any | None = ..., T: Any | None = ...): ...
def ff_partial_target(H, W: Any | None = ..., L: Any | None = ..., A: Any | None = ..., T: Any | None = ...): ...
