from typing import Any

__ALL__: Any

class ModuleDeprecationWarning(DeprecationWarning): ...
class VisibleDeprecationWarning(UserWarning): ...

class _NoValueType:
    def __new__(cls): ...
    def __reduce__(self): ...
