def fromarrays(arrayList, dtype=..., shape=..., formats=..., names=..., titles=..., aligned=..., byteorder=...) -> None: ...
def fromrecords(recList, dtype=..., shape=..., formats=..., names=..., titles=..., aligned=..., byteorder=...) -> None: ...
def fromstring(datastring, dtype=..., shape=..., offset=..., formats=..., names=..., titles=..., aligned=..., byteorder=...) -> None: ...
def fromfile(fd, dtype=..., shape=..., offset=..., formats=..., names=..., titles=..., aligned=..., byteorder=...) -> None: ...
def array(obj, dtype=..., shape=..., offset=..., strides=..., formats=..., names=..., titles=..., aligned=..., byteorder=..., copy=...) -> None: ...
