from typing import Any

def find_executable(exe, path: Any | None = ..., _cache=...): ...
def exec_command(command, execute_in: str = ..., use_shell: Any | None = ..., use_tee: Any | None = ..., _with_python: int = ..., **env): ...
