def dos2unix(file): ...
def dos2unix_one_dir(modified_files, dir_name, file_names) -> None: ...
def dos2unix_dir(dir_name): ...
def unix2dos(file): ...
def unix2dos_one_dir(modified_files, dir_name, file_names) -> None: ...
def unix2dos_dir(dir_name): ...
