from typing import Any

class FormatError(IOError):
    msg: Any
    def __init__(self, msg) -> None: ...

class PkgNotFound(IOError):
    msg: Any
    def __init__(self, msg) -> None: ...

def parse_flags(line): ...

class LibraryInfo:
    name: Any
    description: Any
    requires: Any
    version: Any
    vars: Any
    def __init__(self, name, description, version, sections, vars, requires: Any | None = ...) -> None: ...
    def sections(self): ...
    def cflags(self, section: str = ...): ...
    def libs(self, section: str = ...): ...

class VariableSet:
    def __init__(self, d) -> None: ...
    def interpolate(self, value): ...
    def variables(self): ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, value) -> None: ...

def read_config(pkgname, dirs: Any | None = ...): ...
