from tensorflow.python.util.tf_export import tf_export as tf_export

def is_mixed_precision_graph_rewrite_enabled(): ...
def set_mixed_precision_graph_rewrite_enabled(enabled) -> None: ...
def non_mixed_precision_session_created(): ...
def set_non_mixed_precision_session_created(created) -> None: ...
def is_using_mixed_precision_policy(): ...
def set_using_mixed_precision_policy(is_using) -> None: ...
