from tensorflow.compiler.jit.ops import xla_ops as xla_ops, xla_ops_grad as xla_ops_grad
from tensorflow.core.framework import attr_value_pb2 as attr_value_pb2
from tensorflow.python.distribute import summary_op_util as summary_op_util
from tensorflow.python.eager import context as context, def_function as def_function
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, variable_scope as variable_scope
from tensorflow.python.util import compat as compat, nest as nest, tf_inspect as tf_inspect
from tensorflow.python.util.compat import collections_abc as collections_abc
from tensorflow.python.util.deprecation import deprecated as deprecated
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def compile(computation, inputs: Any | None = ...): ...

class XLACompileContext(control_flow_ops.XLAControlFlowContext):
    def __init__(self, name, pivot) -> None: ...
    def report_unsupported_operations(self) -> None: ...
    def AddOp(self, op) -> None: ...
    def AddValue(self, val): ...
    def AddInnerOp(self, op) -> None: ...
    @property
    def grad_state(self) -> None: ...
    @property
    def back_prop(self): ...

def is_flat(outputs): ...

class _CapturedObject:
    def __init__(self) -> None: ...
    def capture(self, o) -> None: ...
    def get(self): ...

def check_function_argument_count(func, input_arity, infeed_queue): ...
