from google.protobuf.any_pb2 import Any
from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2, saved_model_pb2 as saved_model_pb2, saver_pb2 as saver_pb2
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.ops import variables as variables
from tensorflow.python.platform import tf_logging as tf_logging
from tensorflow.python.saved_model import constants as constants, signature_def_utils as signature_def_utils
from tensorflow.python.saved_model.pywrap_saved_model import metrics as metrics
from tensorflow.python.util import compat as compat
from tensorflow.python.util.deprecation import deprecated_args as deprecated_args
from tensorflow.python.util.tf_export import tf_export as tf_export

class _SavedModelBuilder:
    def __init__(self, export_dir) -> None: ...
    def add_meta_graph(self, tags, signature_def_map: Any | None = ..., assets_list: Any | None = ..., clear_devices: bool = ..., init_op: Any | None = ..., train_op: Any | None = ..., saver: Any | None = ...) -> None: ...
    def add_meta_graph_and_variables(self, sess, tags, signature_def_map: Any | None = ..., assets_list: Any | None = ..., clear_devices: bool = ..., init_op: Any | None = ..., train_op: Any | None = ..., strip_default_attrs: bool = ..., saver: Any | None = ...) -> None: ...
    def save(self, as_text: bool = ...): ...

class SavedModelBuilder(_SavedModelBuilder):
    __doc__: Any
    def __init__(self, export_dir) -> None: ...
    def add_meta_graph(self, tags, signature_def_map: Any | None = ..., assets_collection: Any | None = ..., legacy_init_op: Any | None = ..., clear_devices: bool = ..., main_op: Any | None = ..., strip_default_attrs: bool = ..., saver: Any | None = ...) -> None: ...
    def add_meta_graph_and_variables(self, sess, tags, signature_def_map: Any | None = ..., assets_collection: Any | None = ..., legacy_init_op: Any | None = ..., clear_devices: bool = ..., main_op: Any | None = ..., strip_default_attrs: bool = ..., saver: Any | None = ...) -> None: ...

def get_asset_filename_to_add(asset_filepath, asset_filename_map): ...
def copy_assets_to_destination_dir(asset_filename_map, destination_dir) -> None: ...
