from tensorflow.core.protobuf import saved_object_graph_pb2 as saved_object_graph_pb2
from tensorflow.python.saved_model import nested_structure_coder as nested_structure_coder
from tensorflow.python.util import compat as compat, nest as nest

def serialize_concrete_function(concrete_function, node_ids, coder): ...
def serialize_bare_concrete_function(concrete_function, name_map): ...
def serialize_function(function, name_map): ...
def wrap_cached_variables(concrete_function): ...
