from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any

def get_registered_name(obj): ...
def get_registered_class(registered_name): ...
def register_serializable(package: str = ..., name: Any | None = ..., predicate: Any | None = ...): ...
