from tensorflow.python.util.tf_export import tf_export as tf_export

DEFAULT_SERVING_SIGNATURE_DEF_KEY: str
CLASSIFY_INPUTS: str
CLASSIFY_METHOD_NAME: str
CLASSIFY_OUTPUT_CLASSES: str
CLASSIFY_OUTPUT_SCORES: str
PREDICT_INPUTS: str
PREDICT_METHOD_NAME: str
PREDICT_OUTPUTS: str
REGRESS_INPUTS: str
REGRESS_METHOD_NAME: str
REGRESS_OUTPUTS: str
DEFAULT_TRAIN_SIGNATURE_DEF_KEY: str
DEFAULT_EVAL_SIGNATURE_DEF_KEY: str
SUPERVISED_TRAIN_METHOD_NAME: str
SUPERVISED_EVAL_METHOD_NAME: str
