from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2
from tensorflow.python.framework import errors as errors, ops as ops
from tensorflow.python.saved_model import signature_constants as signature_constants
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def build_signature_def(inputs: Any | None = ..., outputs: Any | None = ..., method_name: Any | None = ...): ...
def regression_signature_def(examples, predictions): ...
def classification_signature_def(examples, classes, scores): ...
def predict_signature_def(inputs, outputs): ...
def supervised_train_signature_def(inputs, loss, predictions: Any | None = ..., metrics: Any | None = ...): ...
def supervised_eval_signature_def(inputs, loss, predictions: Any | None = ..., metrics: Any | None = ...): ...
def is_valid_signature(signature_def): ...
def op_signature_def(op, key): ...
def load_op_from_signature_def(signature_def, key, import_scope: Any | None = ...): ...
