from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2, struct_pb2 as struct_pb2
from tensorflow.python.eager import context as context
from tensorflow.python.framework import composite_tensor as composite_tensor, dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor, tensor_shape as tensor_shape
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.saved_model import constants as constants, nested_structure_coder as nested_structure_coder
from tensorflow.python.util import compat as compat, deprecation as deprecation, nest as nest
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def build_tensor_info(tensor): ...
def build_tensor_info_internal(tensor): ...
def build_tensor_info_from_op(op): ...
def get_tensor_from_tensor_info(tensor_info, graph: Any | None = ..., import_scope: Any | None = ...): ...
def get_element_from_tensor_info(tensor_info, graph: Any | None = ..., import_scope: Any | None = ...): ...
def get_or_create_variables_dir(export_dir): ...
def get_variables_dir(export_dir): ...
def get_variables_path(export_dir): ...
def get_or_create_assets_dir(export_dir): ...
def get_assets_dir(export_dir): ...
def get_or_create_debug_dir(export_dir): ...
def get_saved_model_pbtxt_path(export_dir): ...
def get_saved_model_pb_path(export_dir): ...
def get_debug_dir(export_dir): ...

byte_swappable: Any

def swap_function_tensor_content(meta_graph_def, from_endiness, to_endiness) -> None: ...
def byte_swap_tensor_content(tensor, from_endiness, to_endiness) -> None: ...
