from .extras import mvstdnormcdf as mvstdnormcdf
from typing import Any

def chi2_pdf(self, x, df): ...
def chi_pdf(x, df): ...
def chi_logpdf(x, df): ...
def funbgh(s, a, b, R, df): ...
def funbgh2(s, a, b, R, df): ...
def bghfactor(df): ...
def mvstdtprob(a, b, R, df, ieps: float = ..., quadkwds: Any | None = ..., mvstkwds: Any | None = ...): ...
def multivariate_t_rvs(m, S, df=..., n: int = ...): ...
