from statsmodels.compat.python import lrange as lrange
from statsmodels.iolib.table import SimpleTable as SimpleTable
from typing import Any

class StatTestMC:
    dgp: Any
    statistic: Any
    def __init__(self, dgp, statistic) -> None: ...
    nrepl: Any
    statindices: Any
    dgpargs: Any
    statsargs: Any
    nreturn: Any
    mcres: Any
    def run(self, nrepl, statindices: Any | None = ..., dgpargs=..., statsargs=...) -> None: ...
    histo: Any
    cumhisto: Any
    cumhistoreversed: Any
    def histogram(self, idx: Any | None = ..., critval: Any | None = ...): ...
    mcressort: Any
    def get_mc_sorted(self): ...
    frac: Any
    def quantiles(self, idx: Any | None = ..., frac=...): ...
    def cdf(self, x, idx: Any | None = ...): ...
    def plot_hist(self, idx, distpdf: Any | None = ..., bins: int = ..., ax: Any | None = ..., kwds: Any | None = ...) -> None: ...
    def summary_quantiles(self, idx, distppf, frac=..., varnames: Any | None = ..., title: Any | None = ...): ...
    def summary_cdf(self, idx, frac, crit, varnames: Any | None = ..., title: Any | None = ...): ...
