from keras.optimizer_v2 import optimizer_v2 as optimizer_v2

class Ftrl(optimizer_v2.OptimizerV2):
    def __init__(self, learning_rate: float = ..., learning_rate_power=..., initial_accumulator_value: float = ..., l1_regularization_strength: float = ..., l2_regularization_strength: float = ..., name: str = ..., l2_shrinkage_regularization_strength: float = ..., beta: float = ..., **kwargs) -> None: ...
    def get_config(self): ...
