def all_reduce_sum_gradients(grads_and_vars): ...
def filter_empty_gradients(grads_and_vars): ...
def make_gradient_clipnorm_fn(clipnorm): ...
def make_global_gradient_clipnorm_fn(clipnorm): ...
def make_gradient_clipvalue_fn(clipvalue): ...
