from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

VERBOSITY_VAR_NAME: str
DEFAULT_VERBOSITY: int
verbosity_level: Any
echo_log_to_stdout: bool

def set_verbosity(level, alsologtostdout: bool = ...) -> None: ...
def trace(*args) -> None: ...
def get_verbosity(): ...
def has_verbosity(level): ...
def error(level, msg, *args, **kwargs) -> None: ...
def log(level, msg, *args, **kwargs) -> None: ...
def warning(msg, *args, **kwargs) -> None: ...
