from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_math_ops as gen_math_ops, math_ops as math_ops

def alias_tensors(*args): ...
def get_range_len(start, limit, delta): ...
