from tensorflow.python.framework import dtypes as dtypes, sparse_tensor as sparse_tensor, tensor_util as tensor_util
from tensorflow.python.ops import tensor_array_ops as tensor_array_ops

def is_dense_tensor(t): ...
def is_tensor_array(t): ...
def is_tensor_list(t): ...
def is_range_tensor(t): ...
