from typing import Any

def plot_scree(eigenvals, total_var, ncomp: Any | None = ..., x_label: str = ...): ...
def plot_loadings(loadings, col_names: Any | None = ..., row_names: Any | None = ..., loading_pairs: Any | None = ..., percent_variance: Any | None = ..., title: str = ...): ...
