from _typeshed import Incomplete

class AffineError(ValueError): ...

def apply_affine(aff, pts, inplace: bool = False): ...
def to_matvec(transform): ...
def from_matvec(matrix, vector: Incomplete | None = None): ...
def append_diag(aff, steps, starts=()): ...
def dot_reduce(*args): ...
def voxel_sizes(affine): ...
def obliquity(affine): ...
def rescale_affine(affine, shape, zooms, new_shape: Incomplete | None = None): ...
