from collections.abc import MutableMapping

from . import xmlutils as xml

class CaretMetaData(xml.XmlSerializable, MutableMapping):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
