from _typeshed import Incomplete

from .deprecated import deprecate_with_version as deprecate_with_version

class CastingError(Exception): ...

TRUNC_UINT64: Incomplete
sctypes: Incomplete
sctypes_aliases: Incomplete

def float_to_int(arr, int_type, nan2zero: bool = True, infmax: bool = False): ...
def shared_range(flt_type, int_type): ...

class FloatingError(Exception): ...

def on_powerpc(): ...
def type_info(np_type): ...
def as_int(x, check: bool = True): ...
def int_to_float(val, flt_type): ...
def floor_exact(val, flt_type): ...
def ceil_exact(val, flt_type): ...
def int_abs(arr): ...
def floor_log2(x): ...
def best_float(): ...
def longdouble_lte_float64(): ...
def longdouble_precision_improved(): ...
def have_binary128(): ...
def ok_floats(): ...

OK_FLOATS: Incomplete

def able_int_type(values): ...
def ulp(val=...): ...
