from _typeshed import Incomplete

from .environment import get_nipy_system_dir as get_nipy_system_dir
from .environment import get_nipy_user_dir as get_nipy_user_dir

DEFAULT_INSTALL_HINT: str

class DataError(Exception): ...
class BomberError(DataError, AttributeError): ...

class Datasource:
    base_path: Incomplete
    def __init__(self, base_path) -> None: ...
    def get_filename(self, *path_parts): ...
    def list_files(self, relative: bool = True): ...

class VersionedDatasource(Datasource):
    config: Incomplete
    version: Incomplete
    major_version: Incomplete
    minor_version: Incomplete
    version_no: Incomplete
    def __init__(
        self, base_path, config_filename: Incomplete | None = None
    ) -> None: ...

def get_data_path(): ...
def find_data_dir(root_dirs, *names): ...
def make_datasource(pkg_def, **kwargs): ...

class Bomber:
    name: Incomplete
    msg: Incomplete
    def __init__(self, name, msg) -> None: ...
    def __getattr__(self, attr_name) -> None: ...

def datasource_or_bomber(pkg_def, **options): ...
