from _typeshed import Incomplete

def euler2mat(z: int = 0, y: int = 0, x: int = 0): ...
def mat2euler(M, cy_thresh: Incomplete | None = None): ...
def euler2quat(z: int = 0, y: int = 0, x: int = 0): ...
def quat2euler(q): ...
def euler2angle_axis(z: int = 0, y: int = 0, x: int = 0): ...
def angle_axis2euler(theta, vector, is_normalized: bool = False): ...
