from _typeshed import Incomplete

from .loadsave import load as load
from .orientations import OrientationError as OrientationError
from .orientations import io_orientation as io_orientation

def squeeze_image(img): ...
def concat_images(
    images, check_affines: bool = True, axis: Incomplete | None = None
): ...
def four_to_three(img): ...
def as_closest_canonical(img, enforce_diag: bool = False): ...
