from _typeshed import Incomplete

from .deprecated import deprecate_with_version as deprecate_with_version

class OrientationError(Exception): ...

def io_orientation(affine, tol: Incomplete | None = None): ...
def ornt_transform(start_ornt, end_ornt): ...
def apply_orientation(arr, ornt): ...
def inv_ornt_aff(ornt, shape): ...
def flip_axis(arr, axis: int = 0): ...
def ornt2axcodes(ornt, labels: Incomplete | None = None): ...
def axcodes2ornt(axcodes, labels: Incomplete | None = None): ...
def aff2axcodes(
    aff, labels: Incomplete | None = None, tol: Incomplete | None = None
): ...
