from _typeshed import Incomplete

from .casting import sctypes as sctypes

MAX_FLOAT: Incomplete
FLOAT_EPS: Incomplete

def fillpositive(xyz, w2_thresh: Incomplete | None = None): ...
def quat2mat(q): ...
def mat2quat(M): ...
def mult(q1, q2): ...
def conjugate(q): ...
def norm(q): ...
def isunit(q): ...
def inverse(q): ...
def eye(): ...
def rotate_vector(v, q): ...
def nearly_equivalent(q1, q2, rtol: float = 1e-05, atol: float = 1e-08): ...
def angle_axis2quat(theta, vector, is_normalized: bool = False): ...
def angle_axis2mat(theta, vector, is_normalized: bool = False): ...
def quat2angle_axis(quat, identity_thresh: Incomplete | None = None): ...
