from _typeshed import Incomplete

from .affines import voxel_sizes as voxel_sizes
from .optpkg import optional_package as optional_package
from .orientations import aff2axcodes as aff2axcodes
from .orientations import axcodes2ornt as axcodes2ornt

class OrthoSlicer3D:
    def __init__(
        self,
        data,
        affine: Incomplete | None = None,
        axes: Incomplete | None = None,
        title: Incomplete | None = None,
    ) -> None: ...
    def show(self) -> None: ...
    def close(self) -> None: ...
    def draw(self) -> None: ...
    @property
    def n_volumes(self): ...
    @property
    def position(self): ...
    @property
    def figs(self): ...
    @property
    def cmap(self): ...
    @cmap.setter
    def cmap(self, cmap) -> None: ...
    @property
    def clim(self): ...
    @clim.setter
    def clim(self, clim) -> None: ...
    def link_to(self, other) -> None: ...
    def set_position(
        self,
        x: Incomplete | None = None,
        y: Incomplete | None = None,
        z: Incomplete | None = None,
    ) -> None: ...
    def set_volume_idx(self, v) -> None: ...
