from tensorflow.python.keras import layers as keras_layers
from tensorflow.python.keras.legacy_tf_layers import base as base
from tensorflow.python.util.tf_export import keras_export as keras_export, tf_export as tf_export
from typing import Any

class AveragePooling1D(keras_layers.AveragePooling1D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def average_pooling1d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...

class MaxPooling1D(keras_layers.MaxPooling1D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def max_pooling1d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...

class AveragePooling2D(keras_layers.AveragePooling2D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def average_pooling2d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...

class MaxPooling2D(keras_layers.MaxPooling2D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def max_pooling2d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...

class AveragePooling3D(keras_layers.AveragePooling3D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def average_pooling3d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...

class MaxPooling3D(keras_layers.MaxPooling3D, base.Layer):
    def __init__(self, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ..., **kwargs) -> None: ...

def max_pooling3d(inputs, pool_size, strides, padding: str = ..., data_format: str = ..., name: Any | None = ...): ...
AvgPool2D = AveragePooling2D
MaxPool2D = MaxPooling2D
max_pool2d = max_pooling2d
avg_pool2d = average_pooling2d
