from sklearn._loss.glm_distribution import DistributionBoundary as DistributionBoundary, GammaDistribution as GammaDistribution, InverseGaussianDistribution as InverseGaussianDistribution, NormalDistribution as NormalDistribution, PoissonDistribution as PoissonDistribution, TweedieDistribution as TweedieDistribution

def test_family_bounds(family, expected) -> None: ...
def test_invalid_distribution_bound() -> None: ...
def test_tweedie_distribution_power() -> None: ...
def test_deviance_zero(family, chk_values) -> None: ...
def test_deviance_derivative(family): ...
