from tensorflow.python import pywrap_tfe as pywrap_tfe

class CancellationManager:
    def __init__(self) -> None: ...
    @property
    def is_cancelled(self): ...
    def start_cancel(self) -> None: ...
    def get_cancelable_function(self, concrete_function): ...
