from tensorflow.python.eager import context as context
from tensorflow.python.framework import errors as errors
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.util import compat as compat
from tensorflow.python.util.deprecation import deprecated as deprecated

class ProfilerAlreadyRunningError(Exception): ...
class ProfilerNotRunningError(Exception): ...

def start() -> None: ...
def stop(): ...
def maybe_create_event_file(logdir) -> None: ...
def save(logdir, result) -> None: ...
def start_profiler_server(port) -> None: ...

class Profiler:
    def __init__(self, logdir) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, typ, value, tb) -> None: ...
