from sklearn import datasets as datasets, manifold as manifold, neighbors as neighbors, pipeline as pipeline, preprocessing as preprocessing
from sklearn.metrics.pairwise import pairwise_distances as pairwise_distances
from typing import Any

eigen_solvers: Any
path_methods: Any

def test_isomap_simple_grid() -> None: ...
def test_isomap_reconstruction_error() -> None: ...
def test_transform() -> None: ...
def test_pipeline() -> None: ...
def test_pipeline_with_nearest_neighbors_transformer() -> None: ...
def test_different_metric(): ...
def test_isomap_clone_bug() -> None: ...
def test_sparse_input() -> None: ...
def test_multiple_connected_components() -> None: ...
def test_multiple_connected_components_metric_precomputed() -> None: ...
