from sklearn.utils._testing import ignore_warnings as ignore_warnings

def test_smacof() -> None: ...
def test_smacof_error() -> None: ...
def test_MDS() -> None: ...
def test_MDS_pairwise_deprecated() -> None: ...
def test_MDS_pairwise(dissimilarity, expected_pairwise) -> None: ...
