from nibabel.cmdline import convert as convert
from nibabel.testing import get_test_data as get_test_data

def test_convert_noop(tmp_path) -> None: ...
def test_convert_dtype(tmp_path, data_dtype) -> None: ...
def test_convert_by_extension(tmp_path, ext, img_class) -> None: ...
def test_convert_imgtype(tmp_path, ext, img_class) -> None: ...
def test_convert_nifti_int_fail(tmp_path) -> None: ...
def test_convert_aliases(tmp_path, orig_dtype, alias, expected_dtype) -> None: ...
