from nibabel.cmdline.diff import *
from nibabel.cmdline.utils import *
from nibabel.testing import data_path as data_path

def test_table2string() -> None: ...
def test_ap() -> None: ...
def test_safe_get(): ...
def test_get_headers_diff() -> None: ...
def test_display_diff() -> None: ...
def test_get_data_diff() -> None: ...
def test_main() -> None: ...
