class Iterable:
    def __iter__(self): ...
    def reduce(self, initial_state, reduce_func) -> None: ...

class Iterator:
    def get_next(self) -> None: ...
    def __next__(self) -> None: ...
    def __iter__(self): ...
