from numpy.distutils.cpuinfo import cpu as cpu
from numpy.distutils.fcompiler import FCompiler as FCompiler, dummy_fortran_file as dummy_fortran_file
from numpy.distutils.misc_util import cyg2win32 as cyg2win32
from typing import Any

compilers: Any

class AbsoftFCompiler(FCompiler):
    compiler_type: str
    description: str
    version_pattern: Any
    executables: Any
    library_switch: str
    module_dir_switch: Any
    module_include_switch: str
    def update_executables(self) -> None: ...
    def get_flags_linker_so(self): ...
    def library_dir_option(self, dir): ...
    def library_option(self, lib): ...
    def get_library_dirs(self): ...
    def get_libraries(self): ...
    def get_flags(self): ...
    def get_flags_f77(self): ...
    def get_flags_f90(self): ...
    def get_flags_fix(self): ...
    def get_flags_opt(self): ...
