from numpy.distutils.exec_command import filepath_from_subprocess_output as filepath_from_subprocess_output
from numpy.distutils.fcompiler import FCompiler as FCompiler
from typing import Any

compilers: Any
TARGET_R: Any

def is_win64(): ...

class GnuFCompiler(FCompiler):
    compiler_type: str
    compiler_aliases: Any
    description: str
    def gnu_version_match(self, version_string): ...
    def version_match(self, version_string): ...
    possible_executables: Any
    executables: Any
    module_dir_switch: Any
    module_include_switch: Any
    pic_flags: Any
    g2c: str
    suggested_f90_compiler: str
    def get_flags_linker_so(self): ...
    def get_libgcc_dir(self): ...
    def get_libgfortran_dir(self): ...
    def get_library_dirs(self): ...
    def get_libraries(self): ...
    def get_flags_debug(self): ...
    def get_flags_opt(self): ...
    def get_flags_arch(self): ...
    def runtime_library_dir_option(self, dir): ...

class Gnu95FCompiler(GnuFCompiler):
    compiler_type: str
    compiler_aliases: Any
    description: str
    def version_match(self, version_string): ...
    possible_executables: Any
    executables: Any
    module_dir_switch: str
    module_include_switch: str
    g2c: str
    def get_flags(self): ...
    def get_flags_linker_so(self): ...
    def get_library_dirs(self): ...
    def get_libraries(self): ...
    def get_target(self): ...
    def can_ccompiler_link(self, compiler): ...
    def wrap_unlinkable_objects(self, objects, output_dir, extra_dll_dir): ...
