from numpy.distutils.fcompiler import FCompiler as FCompiler
from typing import Any

compilers: Any

class PGroupFCompiler(FCompiler):
    compiler_type: str
    description: str
    version_pattern: str
    executables: Any
    pic_flags: Any
    module_dir_switch: str
    module_include_switch: str
    def get_flags(self): ...
    def get_flags_opt(self): ...
    def get_flags_debug(self): ...
    def get_flags_linker_so(self): ...
    def get_flags_linker_so(self): ...
    def runtime_library_dir_option(self, dir): ...

class PGroupFlangCompiler(FCompiler):
    compiler_type: str
    description: str
    version_pattern: str
    ar_exe: str
    possible_executables: Any
    executables: Any
    library_switch: str
    module_dir_switch: str
    def get_libraries(self): ...
    def get_library_dirs(self): ...
    def get_flags(self): ...
    def get_flags_free(self): ...
    def get_flags_debug(self): ...
    def get_flags_opt(self): ...
    def get_flags_arch(self): ...
    def runtime_library_dir_option(self, dir) -> None: ...
