from statsmodels.api import OLS as OLS, stats as stats
from typing import Any

def multiOLS(model, dataframe, column_list: Any | None = ..., method: str = ..., alpha: float = ..., subset: Any | None = ..., model_type=..., **kwargs): ...
def multigroup(pvals, groups, exact: bool = ..., keep_all: bool = ..., alpha: float = ...): ...
