from typing import Any

class Pca:
    A: Any
    names: Any
    def __init__(self, data, names: Any | None = ...) -> None: ...
    def getCovarianceMatrix(self): ...
    def getEigensystem(self): ...
    def getEigenvalues(self): ...
    def getEigenvectors(self): ...
    def getEnergies(self): ...
    def plot2d(self, ix: int = ..., iy: int = ..., clf: bool = ...) -> None: ...
    def plot3d(self, ix: int = ..., iy: int = ..., iz: int = ..., clf: bool = ...) -> None: ...
    def sigclip(self, sigs): ...
    def reset(self) -> None: ...
    def project(self, vals: Any | None = ..., enthresh: Any | None = ..., nPCs: Any | None = ..., cumen: Any | None = ...): ...
    def deproject(self, A, normed: bool = ...): ...
    def subtractPC(self, pc, vals: Any | None = ...): ...
