from typing import Any

def forrt(X, m: Any | None = ...): ...
def revrt(X, m: Any | None = ...): ...
def silverman_transform(bw, M, RANGE): ...
def counts(x, v): ...
def kdesum(x, axis: int = ...): ...
