from ._kernel_base import EstimatorSettings as EstimatorSettings, GenericKDE
from typing import Any

class KDEMultivariate(GenericKDE):
    var_type: Any
    k_vars: Any
    data: Any
    data_type: Any
    bw: Any
    def __init__(self, data, var_type, bw: Any | None = ..., defaults: Any | None = ...) -> None: ...
    def loo_likelihood(self, bw, func=...): ...
    def pdf(self, data_predict: Any | None = ...): ...
    def cdf(self, data_predict: Any | None = ...): ...
    def imse(self, bw): ...

class KDEMultivariateConditional(GenericKDE):
    dep_type: Any
    indep_type: Any
    data_type: Any
    k_dep: Any
    k_indep: Any
    endog: Any
    exog: Any
    data: Any
    k_vars: Any
    bw: Any
    def __init__(self, endog, exog, dep_type, indep_type, bw, defaults: Any | None = ...) -> None: ...
    def loo_likelihood(self, bw, func=...): ...
    def pdf(self, endog_predict: Any | None = ..., exog_predict: Any | None = ...): ...
    def cdf(self, endog_predict: Any | None = ..., exog_predict: Any | None = ...): ...
    def imse(self, bw): ...
