class NotFittedError(ValueError, AttributeError): ...
class ChangedBehaviorWarning(UserWarning): ...
class ConvergenceWarning(UserWarning): ...
class DataConversionWarning(UserWarning): ...
class DataDimensionalityWarning(UserWarning): ...
class EfficiencyWarning(UserWarning): ...
class FitFailedWarning(RuntimeWarning): ...
class NonBLASDotWarning(EfficiencyWarning): ...
class SkipTestWarning(UserWarning): ...
class UndefinedMetricWarning(UserWarning): ...
class PositiveSpectrumWarning(UserWarning): ...
