from tensorflow.python.util.tf_export import tf_export as tf_export

enabled: bool

class Trace:
    def __init__(self, name, **kwargs) -> None: ...
    def __enter__(self): ...
    def set_metadata(self, **kwargs) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

def trace_wrapper(trace_name, **trace_kwargs): ...
