from typing import Any

class Duration:
    allowed: Any
    def __init__(self, frame, seconds) -> None: ...
    def frame(self): ...
    def __abs__(self): ...
    def __neg__(self): ...
    def seconds(self): ...
    def __bool__(self): ...
    __eq__: Any
    __ne__: Any
    __lt__: Any
    __le__: Any
    __gt__: Any
    __ge__: Any
    def __add__(self, rhs): ...
    def __sub__(self, rhs): ...
    def __mul__(self, rhs): ...
    __rmul__: Any
    def checkSameFrame(self, rhs, func) -> None: ...
