from matplotlib.dates import date2num as date2num
from typing import Any

class Epoch:
    allowed: Any
    def __init__(self, frame, sec: Any | None = ..., jd: Any | None = ..., daynum: Any | None = ..., dt: Any | None = ...) -> None: ...
    def convert(self, frame): ...
    def frame(self): ...
    def julianDate(self, frame): ...
    def secondsPast(self, frame, jd): ...
    __eq__: Any
    __ne__: Any
    __lt__: Any
    __le__: Any
    __gt__: Any
    __ge__: Any
    def __add__(self, rhs): ...
    def __sub__(self, rhs): ...
    @staticmethod
    def range(start, stop, step): ...
