import matplotlib.units as units
from typing import Any

class EpochConverter(units.ConversionInterface):
    jdRef: Any
    @staticmethod
    def axisinfo(unit, axis): ...
    @staticmethod
    def float2epoch(value, unit): ...
    @staticmethod
    def epoch2float(value, unit): ...
    @staticmethod
    def duration2float(value): ...
    @staticmethod
    def convert(value, unit, axis): ...
    @staticmethod
    def default_units(value, axis): ...
