from tensorflow.core.framework import step_stats_pb2 as step_stats_pb2
from tensorflow.core.grappler.costs import op_performance_data_pb2 as op_performance_data_pb2
from tensorflow.core.protobuf import device_properties_pb2 as device_properties_pb2
from typing import Any

class Cluster:
    def __init__(self, allow_soft_placement: bool = ..., disable_detailed_stats: bool = ..., disable_timeline: bool = ..., devices: Any | None = ...) -> None: ...
    def Shutdown(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def tf_cluster(self): ...
    def ListDevices(self): ...
    def ListAvailableOps(self): ...
    def GetSupportedDevices(self, item): ...
    def EstimatePerformance(self, device): ...
    def MeasureCosts(self, item): ...
    def DeterminePeakMemoryUsage(self, item): ...

def Provision(allow_soft_placement: bool = ..., disable_detailed_stats: bool = ..., disable_timeline: bool = ..., devices: Any | None = ...) -> None: ...
