from ..compat import collections_abc as collections_abc
from typing import Any

def assertProtoEqual(self, a, b, check_initialized: bool = ..., normalize_numbers: bool = ..., msg: Any | None = ...) -> None: ...
def NormalizeNumberFields(pb): ...
def ProtoEq(a, b): ...

class ProtoAssertions:
    def assertProtoEqual(self, *args, **kwargs): ...
