from typing import Any

def quantiles(a, prob=..., alphap: float = ..., betap: float = ..., axis: Any | None = ..., limit=..., masknan: bool = ...): ...
def scoreatpercentile(data, per, limit=..., alphap: float = ..., betap: float = ..., axis: int = ..., masknan: Any | None = ...): ...
def plotting_positions(data, alpha: float = ..., beta: float = ..., axis: int = ..., masknan: bool = ...): ...
meppf = plotting_positions

def plotting_positions_w1d(data, weights: Any | None = ..., alpha: float = ..., beta: float = ..., method: str = ...): ...
def edf_normal_inverse_transformed(x, alpha=..., beta=..., axis: int = ...): ...
