from typing import Any

def scoreatpercentile(data, percentile): ...
def percentileofscore(data, score): ...
def empiricalcdf(data, method: str = ...): ...

class HistDist:
    data: Any
    binlimit: Any
    ranking: Any
    cdfintp: Any
    ppfintp: Any
    def __init__(self, data) -> None: ...
    def empiricalcdf(self, data: Any | None = ..., method: str = ...): ...
    def cdf_emp(self, score): ...
    def ppf_emp(self, quantile): ...
    nbin: Any
    def optimize_binning(self, method: str = ...): ...
