from statsmodels.compat.python import asstr as asstr, lmap as lmap, lrange as lrange, lzip as lzip
from typing import Any

def date_parser(timestr, parserinfo: Any | None = ..., **kwargs): ...
def date_range_str(start, end: Any | None = ..., length: Any | None = ...): ...
def dates_from_str(dates): ...
def dates_from_range(start, end: Any | None = ..., length: Any | None = ...): ...
