from typing import Any

def model_to_estimator(keras_model: Any | None = ..., keras_model_path: Any | None = ..., custom_objects: Any | None = ..., model_dir: Any | None = ..., config: Any | None = ..., checkpoint_format: str = ..., metric_names_map: Any | None = ..., export_outputs: Any | None = ...): ...
def model_to_estimator_v2(keras_model: Any | None = ..., keras_model_path: Any | None = ..., custom_objects: Any | None = ..., model_dir: Any | None = ..., config: Any | None = ..., checkpoint_format: str = ..., metric_names_map: Any | None = ..., export_outputs: Any | None = ...): ...
