from sklearn.decomposition import LatentDirichletAllocation as LatentDirichletAllocation
from sklearn.exceptions import NotFittedError as NotFittedError
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, if_safe_multiprocessing_with_blas as if_safe_multiprocessing_with_blas

def test_lda_default_prior_params() -> None: ...
def test_lda_fit_batch() -> None: ...
def test_lda_fit_online() -> None: ...
def test_lda_partial_fit() -> None: ...
def test_lda_dense_input() -> None: ...
def test_lda_transform() -> None: ...
def test_lda_fit_transform(method) -> None: ...
def test_invalid_params() -> None: ...
def test_lda_negative_input() -> None: ...
def test_lda_no_component_error() -> None: ...
def test_lda_multi_jobs(method) -> None: ...
def test_lda_partial_fit_multi_jobs() -> None: ...
def test_lda_preplexity_mismatch() -> None: ...
def test_lda_perplexity(method) -> None: ...
def test_lda_score(method) -> None: ...
def test_perplexity_input_format() -> None: ...
def test_lda_score_perplexity() -> None: ...
def test_lda_fit_perplexity() -> None: ...
def test_lda_empty_docs() -> None: ...
def test_dirichlet_expectation() -> None: ...
def check_verbosity(verbose, evaluate_every, expected_lines, expected_perplexities) -> None: ...
def test_verbosity(verbose, evaluate_every, expected_lines, expected_perplexities) -> None: ...
