from sklearn.decomposition import FastICA as FastICA, PCA as PCA, fastica as fastica
from sklearn.exceptions import ConvergenceWarning as ConvergenceWarning
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal

def center_and_norm(x, axis: int = ...) -> None: ...
def test_gs() -> None: ...
def test_fastica_simple(add_noise, seed): ...
def test_fastica_nowhiten() -> None: ...
def test_fastica_convergence_fail() -> None: ...
def test_non_square_fastica(add_noise) -> None: ...
def test_fit_transform() -> None: ...
def test_inverse_transform() -> None: ...
def test_fastica_errors() -> None: ...
def test_fastica_output_shape(whiten, return_X_mean, return_n_iter) -> None: ...
