from sklearn.base import clone as clone
from sklearn.decomposition import DictionaryLearning as DictionaryLearning, MiniBatchDictionaryLearning as MiniBatchDictionaryLearning, SparseCoder as SparseCoder, dict_learning as dict_learning, dict_learning_online as dict_learning_online, sparse_encode as sparse_encode
from sklearn.exceptions import ConvergenceWarning as ConvergenceWarning
from sklearn.utils import check_array as check_array
from sklearn.utils._testing import TempMemmap as TempMemmap, assert_allclose as assert_allclose, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal, ignore_warnings as ignore_warnings
from sklearn.utils.estimator_checks import check_transformer_data_not_an_array as check_transformer_data_not_an_array, check_transformer_general as check_transformer_general, check_transformers_unfitted as check_transformers_unfitted
from typing import Any

rng_global: Any
n_samples: Any
n_features: Any
X: Any

def test_sparse_encode_shapes_omp() -> None: ...
def test_dict_learning_shapes() -> None: ...
def test_dict_learning_overcomplete() -> None: ...
def test_max_iter(): ...
def test_dict_learning_lars_positive_parameter() -> None: ...
def test_dict_learning_positivity(transform_algorithm, positive_code, positive_dict) -> None: ...
def test_dict_learning_lars_dict_positivity(positive_dict) -> None: ...
def test_dict_learning_lars_code_positivity() -> None: ...
def test_dict_learning_reconstruction() -> None: ...
def test_dict_learning_reconstruction_parallel() -> None: ...
def test_dict_learning_lassocd_readonly_data() -> None: ...
def test_dict_learning_nonzero_coefs() -> None: ...
def test_dict_learning_unknown_fit_algorithm() -> None: ...
def test_dict_learning_split() -> None: ...
def test_dict_learning_online_shapes() -> None: ...
def test_dict_learning_online_lars_positive_parameter() -> None: ...
def test_minibatch_dictionary_learning_positivity(transform_algorithm, positive_code, positive_dict) -> None: ...
def test_minibatch_dictionary_learning_lars(positive_dict) -> None: ...
def test_dict_learning_online_positivity(positive_code, positive_dict) -> None: ...
def test_dict_learning_online_verbosity() -> None: ...
def test_dict_learning_online_estimator_shapes() -> None: ...
def test_dict_learning_online_overcomplete() -> None: ...
def test_dict_learning_online_initialization() -> None: ...
def test_dict_learning_online_readonly_initialization() -> None: ...
def test_dict_learning_online_partial_fit() -> None: ...
def test_dict_learning_iter_offset() -> None: ...
def test_sparse_encode_shapes() -> None: ...
def test_sparse_encode_positivity(algo, positive) -> None: ...
def test_sparse_encode_unavailable_positivity(algo) -> None: ...
def test_sparse_encode_input() -> None: ...
def test_sparse_encode_error() -> None: ...
def test_sparse_encode_error_default_sparsity() -> None: ...
def test_unknown_method() -> None: ...
def test_sparse_coder_estimator() -> None: ...
def test_sparse_coder_estimator_clone() -> None: ...
def test_sparse_coder_parallel_mmap() -> None: ...
def test_sparse_coder_common_transformer() -> None: ...
def test_sparse_coder_deprecation() -> None: ...
def test_sparse_coder_n_features_in() -> None: ...
def test_update_dict() -> None: ...
def test_warning_default_transform_alpha(Estimator) -> None: ...
