from sklearn import datasets as datasets, svm as svm
from sklearn.datasets import make_multilabel_classification as make_multilabel_classification
from sklearn.exceptions import UndefinedMetricWarning as UndefinedMetricWarning
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.metrics import accuracy_score as accuracy_score, auc as auc, average_precision_score as average_precision_score, coverage_error as coverage_error, dcg_score as dcg_score, det_curve as det_curve, label_ranking_average_precision_score as label_ranking_average_precision_score, label_ranking_loss as label_ranking_loss, ndcg_score as ndcg_score, precision_recall_curve as precision_recall_curve, roc_auc_score as roc_auc_score, roc_curve as roc_curve, top_k_accuracy_score as top_k_accuracy_score
from sklearn.model_selection import train_test_split as train_test_split
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal
from sklearn.utils.extmath import softmax as softmax
from sklearn.utils.validation import check_array as check_array, check_consistent_length as check_consistent_length, check_random_state as check_random_state
from typing import Any

CURVE_FUNCS: Any

def make_prediction(dataset: Any | None = ..., binary: bool = ...): ...
def test_roc_curve(drop) -> None: ...
def test_roc_curve_end_points() -> None: ...
def test_roc_returns_consistency() -> None: ...
def test_roc_curve_multi() -> None: ...
def test_roc_curve_confidence() -> None: ...
def test_roc_curve_hard() -> None: ...
def test_roc_curve_one_label() -> None: ...
def test_roc_curve_toydata() -> None: ...
def test_roc_curve_drop_intermediate() -> None: ...
def test_roc_curve_fpr_tpr_increasing() -> None: ...
def test_auc() -> None: ...
def test_auc_errors() -> None: ...
def test_multiclass_ovo_roc_auc_toydata(y_true, labels) -> None: ...
def test_multiclass_ovo_roc_auc_toydata_binary(y_true, labels) -> None: ...
def test_multiclass_ovr_roc_auc_toydata(y_true, labels) -> None: ...
def test_roc_auc_score_multiclass_labels_error(msg, y_true, labels, multi_class) -> None: ...
def test_roc_auc_score_multiclass_error(msg, kwargs) -> None: ...
def test_auc_score_non_binary_class() -> None: ...
def test_binary_clf_curve_multiclass_error(curve_func) -> None: ...
def test_binary_clf_curve_implicit_pos_label(curve_func) -> None: ...
def test_binary_clf_curve_zero_sample_weight(curve_func) -> None: ...
def test_precision_recall_curve() -> None: ...
def test_precision_recall_curve_toydata() -> None: ...
def test_average_precision_constant_values() -> None: ...
def test_average_precision_score_pos_label_errors() -> None: ...
def test_score_scale_invariance() -> None: ...
def test_det_curve_toydata(y_true, y_score, expected_fpr, expected_fnr) -> None: ...
def test_det_curve_tie_handling(y_true, y_score, expected_fpr, expected_fnr) -> None: ...
def test_det_curve_sanity_check() -> None: ...
def test_det_curve_constant_scores(y_score) -> None: ...
def test_det_curve_perfect_scores(y_true) -> None: ...
def test_det_curve_bad_input(y_true, y_pred, err_msg) -> None: ...
def test_det_curve_pos_label() -> None: ...
def check_lrap_toy(lrap_score) -> None: ...
def check_zero_or_all_relevant_labels(lrap_score) -> None: ...
def check_lrap_error_raised(lrap_score) -> None: ...
def check_lrap_only_ties(lrap_score) -> None: ...
def check_lrap_without_tie_and_increasing_score(lrap_score) -> None: ...
def check_alternative_lrap_implementation(lrap_score, n_classes: int = ..., n_samples: int = ..., random_state: int = ...) -> None: ...
def test_label_ranking_avp(check, func) -> None: ...
def test_lrap_error_raised() -> None: ...
def test_alternative_lrap_implementation(n_samples, n_classes, random_state) -> None: ...
def test_lrap_sample_weighting_zero_labels() -> None: ...
def test_coverage_error() -> None: ...
def test_coverage_tie_handling() -> None: ...
def test_label_ranking_loss() -> None: ...
def test_ranking_appropriate_input_shape() -> None: ...
def test_ranking_loss_ties_handling() -> None: ...
def test_dcg_score() -> None: ...
def test_dcg_ties() -> None: ...
def test_ndcg_ignore_ties_with_k() -> None: ...
def test_ndcg_invariant() -> None: ...
def test_ndcg_toy_examples(ignore_ties) -> None: ...
def test_ndcg_score() -> None: ...
def test_partial_roc_auc_score() -> None: ...
def test_top_k_accuracy_score(y_true, k, true_score) -> None: ...
def test_top_k_accuracy_score_binary(y_score, k, true_score) -> None: ...
def test_top_k_accuracy_score_multiclass_with_labels(y_true, true_score, labels, labels_as_ndarray) -> None: ...
def test_top_k_accuracy_score_increasing() -> None: ...
def test_top_k_accuracy_score_ties(y_true, k, true_score) -> None: ...
def test_top_k_accuracy_score_warning(y_true, k) -> None: ...
def test_top_k_accuracy_score_error(y_true, labels, msg) -> None: ...
