from typing import Any

class TsaDescriptive:
    data: Any
    label: Any
    name: Any
    def __init__(self, data, label: Any | None = ..., name: str = ...) -> None: ...
    def filter(self, num, den): ...
    def detrend(self, order: int = ...): ...
    mod: Any
    res: Any
    def fit(self, order=..., **kwds): ...
    def acf(self, nlags: int = ...): ...
    def pacf(self, nlags: int = ...): ...
    def periodogram(self): ...
    def plot4(self, fig: Any | None = ..., nobs: int = ..., nacf: int = ..., nfreq: int = ...): ...
