from statsmodels.base.model import LikelihoodModel as LikelihoodModel
from typing import Any

class TSMLEModel(LikelihoodModel):
    nar: int
    nma: int
    def __init__(self, endog, exog: Any | None = ...) -> None: ...
    def geterrors(self, params) -> None: ...
    def loglike(self, params) -> None: ...
    def score(self, params): ...
    def hessian(self, params): ...
    def fit(self, start_params: Any | None = ..., maxiter: int = ..., method: str = ..., tol: float = ...): ...
