from statsmodels.tsa._stl import STL as STL
from typing import Any

def seasonal_mean(x, period): ...
def seasonal_decompose(x, model: str = ..., filt: Any | None = ..., period: Any | None = ..., two_sided: bool = ..., extrapolate_trend: int = ...): ...

class DecomposeResult:
    def __init__(self, observed, seasonal, trend, resid, weights: Any | None = ...) -> None: ...
    @property
    def observed(self): ...
    @property
    def seasonal(self): ...
    @property
    def trend(self): ...
    @property
    def resid(self): ...
    @property
    def weights(self): ...
    @property
    def nobs(self): ...
    def plot(self, observed: bool = ..., seasonal: bool = ..., trend: bool = ..., resid: bool = ..., weights: bool = ...): ...
