from tensorflow.python.platform import gfile as gfile
from tensorflow.python.tpu import tensor_tracer_pb2 as tensor_tracer_pb2
from typing import Any

def report_proto_path(trace_dir): ...
def topological_sort(g): ...

class TensorTracerConfig:
    version: Any
    device_type: Any
    num_replicas: Any
    num_replicas_per_host: Any
    num_hosts: Any
    def __init__(self) -> None: ...

class TensorTraceOrder:
    graph_order: Any
    traced_tensors: Any
    def __init__(self, graph_order, traced_tensors) -> None: ...

def sort_tensors_and_ops(graph): ...

class OpenReportFile:
    def __init__(self, tt_parameters) -> None: ...
    def __enter__(self): ...
    def __exit__(self, unused_type, unused_value, unused_traceback) -> None: ...

def proto_fingerprint(message_proto): ...

class TTReportHandle:
    instrument_records: Any
    def __init__(self) -> None: ...
    def instrument(self, name, explanation) -> None: ...
    def instrument_op(self, op, explanation) -> None: ...
    def instrument_tensor(self, tensor, explanation) -> None: ...
    def create_report_proto(self, tt_config, tt_parameters, tensor_trace_order, tensor_trace_points, collected_signature_types): ...
    def write_report_proto(self, report_proto, tt_parameters) -> None: ...
    def create_report(self, tt_config, tt_parameters, tensor_trace_order, tensor_trace_points) -> None: ...
