from tensorflow.core.protobuf.tpu import topology_pb2 as topology_pb2
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

class Topology:
    def __init__(self, serialized: Any | None = ..., mesh_shape: Any | None = ..., device_coordinates: Any | None = ...) -> None: ...
    @property
    def mesh_shape(self): ...
    @property
    def mesh_rank(self): ...
    @property
    def device_coordinates(self): ...
    @property
    def missing_devices(self): ...
    def task_ordinal_at_coordinates(self, device_coordinates): ...
    def tpu_device_ordinal_at_coordinates(self, device_coordinates): ...
    def cpu_device_name_at_coordinates(self, device_coordinates, job: Any | None = ...): ...
    def tpu_device_name_at_coordinates(self, device_coordinates, job: Any | None = ...): ...
    @property
    def num_tasks(self): ...
    @property
    def num_tpus_per_task(self): ...
    def serialized(self): ...
