from typing import Any

def make_all(module_name, doc_string_modules: Any | None = ...): ...
def reveal_undocumented(symbol_name, target_module: Any | None = ...) -> None: ...
def remove_undocumented(module_name, allowed_exception_list: Any | None = ..., doc_string_modules: Any | None = ...) -> None: ...
