from tensorflow.python.util import decorator_utils as decorator_utils, is_in_graph_mode as is_in_graph_mode, tf_contextlib as tf_contextlib, tf_decorator as tf_decorator, tf_inspect as tf_inspect
from tensorflow.tools.docs import doc_controls as doc_controls
from typing import Any, NamedTuple

class DeprecatedNamesAlreadySet(Exception): ...

def deprecated_alias(deprecated_name, name, func_or_class, warn_once: bool = ...): ...
def deprecated_endpoints(*args): ...
def deprecated(date, instructions, warn_once: bool = ...): ...

class DeprecatedArgSpec(NamedTuple):
    position: Any
    has_ok_value: Any
    ok_value: Any

def deprecated_args(date, instructions, *deprecated_arg_names_or_tuples, **kwargs): ...
def deprecated_arg_values(date, instructions, warn_once: bool = ..., **deprecated_kwargs): ...
def deprecated_argument_lookup(new_name, new_value, old_name, old_value): ...
def rewrite_argument_docstring(old_doc, old_argument, new_argument): ...
def silence() -> None: ...

class HiddenTfApiAttribute(property):
    def __init__(self, deprecation_message) -> None: ...
hide_attribute_from_api = HiddenTfApiAttribute
HIDDEN_ATTRIBUTE: Any
