from tensorflow.core.protobuf import config_pb2 as config_pb2
from tensorflow.python.util import tf_decorator as tf_decorator, tf_inspect as tf_inspect

def fn_args(fn): ...
def has_kwargs(fn): ...
def get_func_name(func): ...
def get_func_code(func): ...
def get_disabled_rewriter_config(): ...
