from tensorflow.python.util.tf_export import tf_export as tf_export

def register_call_context_function(func) -> None: ...
def register_clear_session_function(func) -> None: ...
def register_get_session_function(func) -> None: ...
def register_load_model_function(func) -> None: ...
def get_call_context_function(): ...
def get_clear_session_function(): ...
def get_get_session_function(): ...
def get_load_model_function(): ...
