import inspect as _inspect
from tensorflow.python.util import tf_decorator as tf_decorator
from typing import Any, NamedTuple

def signature(obj, *, follow_wrapped: bool = ...): ...
Parameter = _inspect.Parameter
Signature = _inspect.Signature
ArgSpec = _inspect.ArgSpec
FullArgSpec = _inspect.FullArgSpec

class FullArgSpec(NamedTuple):
    args: Any
    varargs: Any
    varkw: Any
    defaults: Any
    kwonlyargs: Any
    kwonlydefaults: Any
    annotations: Any

def currentframe(): ...
def getargspec(obj): ...
def getfullargspec(obj): ...
def getcallargs(*func_and_positional, **named): ...
def getframeinfo(*args, **kwargs): ...
def getdoc(object): ...
def getfile(object): ...
def getmembers(object, predicate: Any | None = ...): ...
def getmodule(object): ...
def getmro(cls): ...
def getsource(object): ...
def getsourcefile(object): ...
def getsourcelines(object): ...
def isbuiltin(object): ...
def isclass(object): ...
def isfunction(object): ...
def isframe(object): ...
def isgenerator(object): ...
def isgeneratorfunction(object): ...
def ismethod(object): ...
def isanytargetmethod(object): ...
def ismodule(object): ...
def isroutine(object): ...
def stack(context: int = ...): ...
