from typing import Any

def is_generic_union(tp): ...
def is_generic_tuple(tp): ...
def is_generic_list(tp): ...
def is_generic_mapping(tp): ...
def is_forward_ref(tp): ...

get_generic_type_args: Any
