from tensorflow.core.protobuf import saver_pb2 as saver_pb2
from tensorflow.python.eager import context as context, def_function as def_function
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_spec as tensor_spec
from tensorflow.python.ops import array_ops as array_ops, gen_io_ops as gen_io_ops, io_ops as io_ops, string_ops as string_ops
from tensorflow.python.training.saving import checkpoint_options as checkpoint_options, saveable_hook as saveable_hook, saveable_object as saveable_object, saveable_object_util as saveable_object_util
from tensorflow.python.util import nest as nest
from typing import Any

class _SingleDeviceSaver:
    def __init__(self, saveable_objects) -> None: ...
    def save(self, file_prefix, options: Any | None = ...): ...
    def restore(self, file_prefix, options: Any | None = ...): ...

def sharded_filename(filename_tensor, shard, num_shards): ...

class MultiDeviceSaver:
    def __init__(self, saveable_objects) -> None: ...
    def to_proto(self): ...
    def save(self, file_prefix, options: Any | None = ...): ...
    def restore(self, file_prefix, options: Any | None = ...): ...
