class _ConverterError(Exception): ...

class _Converter:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...

class _GSConverter(_Converter):
    def __call__(self, orig, dest): ...

class _SVGConverter(_Converter):
    def __call__(self, orig, dest) -> None: ...
    def __del__(self) -> None: ...

def comparable_formats(): ...
def calculate_rms(expected_image, actual_image): ...
def compare_images(expected, actual, tol, in_decorator: bool = ...): ...
