from matplotlib import cbook as cbook

def pytest_configure(config) -> None: ...
def pytest_unconfigure(config) -> None: ...
def mpl_test_settings(request) -> None: ...
def mpl_image_comparison_parameters(request, extension) -> None: ...
def pd(): ...
