import unittest
from .compare import comparable_formats as comparable_formats, compare_images as compare_images, make_test_filename as make_test_filename
from .exceptions import ImageComparisonFailure as ImageComparisonFailure
from matplotlib import cbook as cbook, ft2font as ft2font, ticker as ticker
from typing import Any

class CleanupTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...

def cleanup(style: Any | None = ...): ...
def check_freetype_version(ver): ...
def remove_ticks_and_titles(figure) -> None: ...

class _ImageComparisonBase:
    func: Any
    tol: Any
    remove_text: Any
    savefig_kwargs: Any
    def __init__(self, func, tol, remove_text, savefig_kwargs) -> None: ...
    def copy_baseline(self, baseline, extension): ...
    def compare(self, idx, baseline, extension, *, _lock: bool = ...) -> None: ...

def image_comparison(baseline_images, extensions: Any | None = ..., tol: int = ..., freetype_version: Any | None = ..., remove_text: bool = ..., savefig_kwarg: Any | None = ..., style=...): ...
def check_figures_equal(*, extensions=..., tol: int = ...): ...
