class RankWarning(UserWarning): ...

def trimseq(seq) -> None: ...
def as_series(alist, trim=...) -> None: ...
def trimcoef(c, tol=...) -> None: ...
def getdomain(x) -> None: ...
def mapparms(old, new) -> None: ...
def mapdomain(x, old, new) -> None: ...
