from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import array_ops as array_ops, check_ops as check_ops, gen_count_ops as gen_count_ops, gen_math_ops as gen_math_ops, math_ops as math_ops
from tensorflow.python.ops.ragged import ragged_tensor as ragged_tensor
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def bincount(arr, weights: Any | None = ..., minlength: Any | None = ..., maxlength: Any | None = ..., dtype=..., name: Any | None = ..., axis: Any | None = ..., binary_output: bool = ...): ...
def bincount_v1(arr, weights: Any | None = ..., minlength: Any | None = ..., maxlength: Any | None = ..., dtype=...): ...
def sparse_bincount(values, weights: Any | None = ..., axis: int = ..., minlength: Any | None = ..., maxlength: Any | None = ..., binary_output: bool = ..., name: Any | None = ...): ...
def validate_dense_weights(values, weights, dtype: Any | None = ...): ...
def validate_sparse_weights(values, weights, dtype: Any | None = ...): ...
def validate_ragged_weights(values, weights, dtype: Any | None = ...): ...
