from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_array_ops as gen_array_ops, gen_nn_ops as gen_nn_ops, math_ops as math_ops
from tensorflow.python.util import deprecation as deprecation, dispatch as dispatch
from tensorflow.python.util.compat import collections_abc as collections_abc
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def clip_by_value(t, clip_value_min, clip_value_max, name: Any | None = ...): ...
def clip_by_norm(t, clip_norm, axes: Any | None = ..., name: Any | None = ...): ...
def global_norm(t_list, name: Any | None = ...): ...
def clip_by_global_norm(t_list, clip_norm, use_norm: Any | None = ..., name: Any | None = ...): ...
def clip_by_average_norm(t, clip_norm, name: Any | None = ...): ...
