from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import control_flow_util as control_flow_util, control_flow_util_v2 as control_flow_util_v2
from tensorflow.python.util.tf_export import tf_export as tf_export

def enable_control_flow_v2() -> None: ...
def disable_control_flow_v2() -> None: ...
def control_flow_v2_enabled(): ...
def output_all_intermediates(state) -> None: ...
