from typing import Any

class _ExecutionSignature: ...

class CriticalSection:
    def __init__(self, name: Any | None = ..., shared_name: Any | None = ..., critical_section_def: Any | None = ..., import_scope: Any | None = ...) -> None: ...
    @property
    def name(self): ...
    def execute(self, fn, exclusive_resource_access: bool = ..., name: Any | None = ...): ...
