from tensorflow.python.framework import dtypes as dtypes, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, resource_variable_ops as resource_variable_ops

def get_zeros_dtype(t): ...
def shape_and_dtype(t): ...
def zeros_like(t): ...
def ones_like(t): ...
def supports_default_grad(t): ...
