from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def empty_tensor_map(name: Any | None = ...): ...

EmptyTensorMap: Any

def empty_tensor_map_eager_fallback(name, ctx): ...
def tensor_map_erase(input_handle, key, value_dtype, name: Any | None = ...): ...

TensorMapErase: Any

def tensor_map_erase_eager_fallback(input_handle, key, value_dtype, name, ctx): ...
def tensor_map_has_key(input_handle, key, name: Any | None = ...): ...

TensorMapHasKey: Any

def tensor_map_has_key_eager_fallback(input_handle, key, name, ctx): ...
def tensor_map_insert(input_handle, key, value, name: Any | None = ...): ...

TensorMapInsert: Any

def tensor_map_insert_eager_fallback(input_handle, key, value, name, ctx): ...
def tensor_map_lookup(input_handle, key, value_dtype, name: Any | None = ...): ...

TensorMapLookup: Any

def tensor_map_lookup_eager_fallback(input_handle, key, value_dtype, name, ctx): ...
def tensor_map_size(input_handle, name: Any | None = ...): ...

TensorMapSize: Any

def tensor_map_size_eager_fallback(input_handle, name, ctx): ...
def tensor_map_stack_keys(input_handle, key_dtype, name: Any | None = ...): ...

TensorMapStackKeys: Any

def tensor_map_stack_keys_eager_fallback(input_handle, key_dtype, name, ctx): ...
