from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def bitwise_and(x, y, name: Any | None = ...): ...

BitwiseAnd: Any

def bitwise_and_eager_fallback(x, y, name, ctx): ...
def bitwise_or(x, y, name: Any | None = ...): ...

BitwiseOr: Any

def bitwise_or_eager_fallback(x, y, name, ctx): ...
def bitwise_xor(x, y, name: Any | None = ...): ...

BitwiseXor: Any

def bitwise_xor_eager_fallback(x, y, name, ctx): ...
def invert(x, name: Any | None = ...): ...

Invert: Any

def invert_eager_fallback(x, name, ctx): ...
def left_shift(x, y, name: Any | None = ...): ...

LeftShift: Any

def left_shift_eager_fallback(x, y, name, ctx): ...
def population_count(x, name: Any | None = ...): ...

PopulationCount: Any

def population_count_eager_fallback(x, name, ctx): ...
def right_shift(x, y, name: Any | None = ...): ...

RightShift: Any

def right_shift_eager_fallback(x, y, name, ctx): ...
