from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, NamedTuple

def fixed_length_record_reader(record_bytes, header_bytes: int = ..., footer_bytes: int = ..., hop_bytes: int = ..., container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

FixedLengthRecordReader: Any

def fixed_length_record_reader_eager_fallback(record_bytes, header_bytes, footer_bytes, hop_bytes, container, shared_name, name, ctx) -> None: ...
def fixed_length_record_reader_v2(record_bytes, header_bytes: int = ..., footer_bytes: int = ..., hop_bytes: int = ..., container: str = ..., shared_name: str = ..., encoding: str = ..., name: Any | None = ...): ...

FixedLengthRecordReaderV2: Any

def fixed_length_record_reader_v2_eager_fallback(record_bytes, header_bytes, footer_bytes, hop_bytes, container, shared_name, encoding, name, ctx): ...
def identity_reader(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

IdentityReader: Any

def identity_reader_eager_fallback(container, shared_name, name, ctx) -> None: ...
def identity_reader_v2(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

IdentityReaderV2: Any

def identity_reader_v2_eager_fallback(container, shared_name, name, ctx): ...
def lmdb_reader(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

LMDBReader: Any

def lmdb_reader_eager_fallback(container, shared_name, name, ctx) -> None: ...
def matching_files(pattern, name: Any | None = ...): ...

MatchingFiles: Any

def matching_files_eager_fallback(pattern, name, ctx): ...
def merge_v2_checkpoints(checkpoint_prefixes, destination_prefix, delete_old_dirs: bool = ..., name: Any | None = ...): ...

MergeV2Checkpoints: Any

def merge_v2_checkpoints_eager_fallback(checkpoint_prefixes, destination_prefix, delete_old_dirs, name, ctx): ...
def read_file(filename, name: Any | None = ...): ...

ReadFile: Any

def read_file_eager_fallback(filename, name, ctx): ...
def reader_num_records_produced(reader_handle, name: Any | None = ...): ...

ReaderNumRecordsProduced: Any

def reader_num_records_produced_eager_fallback(reader_handle, name, ctx) -> None: ...
def reader_num_records_produced_v2(reader_handle, name: Any | None = ...): ...

ReaderNumRecordsProducedV2: Any

def reader_num_records_produced_v2_eager_fallback(reader_handle, name, ctx): ...
def reader_num_work_units_completed(reader_handle, name: Any | None = ...): ...

ReaderNumWorkUnitsCompleted: Any

def reader_num_work_units_completed_eager_fallback(reader_handle, name, ctx) -> None: ...
def reader_num_work_units_completed_v2(reader_handle, name: Any | None = ...): ...

ReaderNumWorkUnitsCompletedV2: Any

def reader_num_work_units_completed_v2_eager_fallback(reader_handle, name, ctx): ...

class _ReaderReadOutput(NamedTuple):
    key: Any
    value: Any

def reader_read(reader_handle, queue_handle, name: Any | None = ...): ...

ReaderRead: Any

def reader_read_eager_fallback(reader_handle, queue_handle, name, ctx) -> None: ...

class _ReaderReadUpToOutput(NamedTuple):
    keys: Any
    values: Any

def reader_read_up_to(reader_handle, queue_handle, num_records, name: Any | None = ...): ...

ReaderReadUpTo: Any

def reader_read_up_to_eager_fallback(reader_handle, queue_handle, num_records, name, ctx) -> None: ...

class _ReaderReadUpToV2Output(NamedTuple):
    keys: Any
    values: Any

def reader_read_up_to_v2(reader_handle, queue_handle, num_records, name: Any | None = ...): ...

ReaderReadUpToV2: Any

def reader_read_up_to_v2_eager_fallback(reader_handle, queue_handle, num_records, name, ctx): ...

class _ReaderReadV2Output(NamedTuple):
    key: Any
    value: Any

def reader_read_v2(reader_handle, queue_handle, name: Any | None = ...): ...

ReaderReadV2: Any

def reader_read_v2_eager_fallback(reader_handle, queue_handle, name, ctx): ...
def reader_reset(reader_handle, name: Any | None = ...): ...

ReaderReset: Any

def reader_reset_eager_fallback(reader_handle, name, ctx) -> None: ...
def reader_reset_v2(reader_handle, name: Any | None = ...): ...

ReaderResetV2: Any

def reader_reset_v2_eager_fallback(reader_handle, name, ctx): ...
def reader_restore_state(reader_handle, state, name: Any | None = ...): ...

ReaderRestoreState: Any

def reader_restore_state_eager_fallback(reader_handle, state, name, ctx) -> None: ...
def reader_restore_state_v2(reader_handle, state, name: Any | None = ...): ...

ReaderRestoreStateV2: Any

def reader_restore_state_v2_eager_fallback(reader_handle, state, name, ctx): ...
def reader_serialize_state(reader_handle, name: Any | None = ...): ...

ReaderSerializeState: Any

def reader_serialize_state_eager_fallback(reader_handle, name, ctx) -> None: ...
def reader_serialize_state_v2(reader_handle, name: Any | None = ...): ...

ReaderSerializeStateV2: Any

def reader_serialize_state_v2_eager_fallback(reader_handle, name, ctx): ...
def restore(file_pattern, tensor_name, dt, preferred_shard: int = ..., name: Any | None = ...): ...

Restore: Any

def restore_eager_fallback(file_pattern, tensor_name, dt, preferred_shard, name, ctx): ...
def restore_slice(file_pattern, tensor_name, shape_and_slice, dt, preferred_shard: int = ..., name: Any | None = ...): ...

RestoreSlice: Any

def restore_slice_eager_fallback(file_pattern, tensor_name, shape_and_slice, dt, preferred_shard, name, ctx): ...
def restore_v2(prefix, tensor_names, shape_and_slices, dtypes, name: Any | None = ...): ...

RestoreV2: Any

def restore_v2_eager_fallback(prefix, tensor_names, shape_and_slices, dtypes, name, ctx): ...
def save(filename, tensor_names, data, name: Any | None = ...): ...

Save: Any

def save_eager_fallback(filename, tensor_names, data, name, ctx): ...
def save_slices(filename, tensor_names, shapes_and_slices, data, name: Any | None = ...): ...

SaveSlices: Any

def save_slices_eager_fallback(filename, tensor_names, shapes_and_slices, data, name, ctx): ...
def save_v2(prefix, tensor_names, shape_and_slices, tensors, name: Any | None = ...): ...

SaveV2: Any

def save_v2_eager_fallback(prefix, tensor_names, shape_and_slices, tensors, name, ctx): ...
def sharded_filename(basename, shard, num_shards, name: Any | None = ...): ...

ShardedFilename: Any

def sharded_filename_eager_fallback(basename, shard, num_shards, name, ctx): ...
def sharded_filespec(basename, num_shards, name: Any | None = ...): ...

ShardedFilespec: Any

def sharded_filespec_eager_fallback(basename, num_shards, name, ctx): ...
def tf_record_reader(container: str = ..., shared_name: str = ..., compression_type: str = ..., name: Any | None = ...): ...

TFRecordReader: Any

def tf_record_reader_eager_fallback(container, shared_name, compression_type, name, ctx) -> None: ...
def tf_record_reader_v2(container: str = ..., shared_name: str = ..., compression_type: str = ..., name: Any | None = ...): ...

TFRecordReaderV2: Any

def tf_record_reader_v2_eager_fallback(container, shared_name, compression_type, name, ctx): ...
def text_line_reader(skip_header_lines: int = ..., container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

TextLineReader: Any

def text_line_reader_eager_fallback(skip_header_lines, container, shared_name, name, ctx) -> None: ...
def text_line_reader_v2(skip_header_lines: int = ..., container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

TextLineReaderV2: Any

def text_line_reader_v2_eager_fallback(skip_header_lines, container, shared_name, name, ctx): ...
def whole_file_reader(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

WholeFileReader: Any

def whole_file_reader_eager_fallback(container, shared_name, name, ctx) -> None: ...
def whole_file_reader_v2(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

WholeFileReaderV2: Any

def whole_file_reader_v2_eager_fallback(container, shared_name, name, ctx): ...
def write_file(filename, contents, name: Any | None = ...): ...

WriteFile: Any

def write_file_eager_fallback(filename, contents, name, ctx): ...
