from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def assign_add_variable_op(resource, value, name: Any | None = ...): ...

AssignAddVariableOp: Any

def assign_add_variable_op_eager_fallback(resource, value, name, ctx): ...
def assign_sub_variable_op(resource, value, name: Any | None = ...): ...

AssignSubVariableOp: Any

def assign_sub_variable_op_eager_fallback(resource, value, name, ctx): ...
def assign_variable_op(resource, value, name: Any | None = ...): ...

AssignVariableOp: Any

def assign_variable_op_eager_fallback(resource, value, name, ctx): ...
def consume_mutex_lock(mutex_lock, name: Any | None = ...): ...

ConsumeMutexLock: Any

def consume_mutex_lock_eager_fallback(mutex_lock, name, ctx): ...
def destroy_resource_op(resource, ignore_lookup_error: bool = ..., name: Any | None = ...): ...

DestroyResourceOp: Any

def destroy_resource_op_eager_fallback(resource, ignore_lookup_error, name, ctx): ...
def mutex_lock(mutex, name: Any | None = ...): ...

MutexLock: Any

def mutex_lock_eager_fallback(mutex, name, ctx): ...
def mutex_v2(container: str = ..., shared_name: str = ..., name: Any | None = ...): ...

MutexV2: Any

def mutex_v2_eager_fallback(container, shared_name, name, ctx): ...
def read_variable_op(resource, dtype, name: Any | None = ...): ...

ReadVariableOp: Any

def read_variable_op_eager_fallback(resource, dtype, name, ctx): ...
def resource_gather(resource, indices, dtype, batch_dims: int = ..., validate_indices: bool = ..., name: Any | None = ...): ...

ResourceGather: Any

def resource_gather_eager_fallback(resource, indices, dtype, batch_dims, validate_indices, name, ctx): ...
def resource_gather_nd(resource, indices, dtype, name: Any | None = ...): ...

ResourceGatherNd: Any

def resource_gather_nd_eager_fallback(resource, indices, dtype, name, ctx): ...
def resource_scatter_add(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterAdd: Any

def resource_scatter_add_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_div(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterDiv: Any

def resource_scatter_div_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_max(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterMax: Any

def resource_scatter_max_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_min(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterMin: Any

def resource_scatter_min_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_mul(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterMul: Any

def resource_scatter_mul_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_sub(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterSub: Any

def resource_scatter_sub_eager_fallback(resource, indices, updates, name, ctx): ...
def resource_scatter_update(resource, indices, updates, name: Any | None = ...): ...

ResourceScatterUpdate: Any

def resource_scatter_update_eager_fallback(resource, indices, updates, name, ctx): ...
def var_handle_op(dtype, shape, container: str = ..., shared_name: str = ..., allowed_devices=..., name: Any | None = ...): ...

VarHandleOp: Any

def var_handle_op_eager_fallback(dtype, shape, container, shared_name, allowed_devices, name, ctx): ...
def var_is_initialized_op(resource, name: Any | None = ...): ...

VarIsInitializedOp: Any

def var_is_initialized_op_eager_fallback(resource, name, ctx): ...
def variable_shape(input, out_type=..., name: Any | None = ...): ...

VariableShape: Any

def variable_shape_eager_fallback(input, out_type, name, ctx): ...
