from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_grad as array_grad, array_ops as array_ops, check_ops as check_ops, control_flow_grad as control_flow_grad, control_flow_ops as control_flow_ops, gradients_util as gradients_util, image_grad as image_grad, linalg_grad as linalg_grad, linalg_ops as linalg_ops, logging_ops as logging_ops, manip_grad as manip_grad, math_grad as math_grad, math_ops as math_ops, optional_grad as optional_grad, random_grad as random_grad, tensor_array_ops as tensor_array_ops
from tensorflow.python.ops.unconnected_gradients import UnconnectedGradients as UnconnectedGradients
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def gradients(ys, xs, grad_ys: Any | None = ..., name: str = ..., colocate_gradients_with_ops: bool = ..., gate_gradients: bool = ..., aggregation_method: Any | None = ..., stop_gradients: Any | None = ..., unconnected_gradients=...): ...
def gradients_v2(ys, xs, grad_ys: Any | None = ..., name: str = ..., gate_gradients: bool = ..., aggregation_method: Any | None = ..., stop_gradients: Any | None = ..., unconnected_gradients=...): ...
def hessians(ys, xs, name: str = ..., colocate_gradients_with_ops: bool = ..., gate_gradients: bool = ..., aggregation_method: Any | None = ...): ...
def HessiansV2(ys, xs, gate_gradients: bool = ..., aggregation_method: Any | None = ..., name: str = ...): ...
