from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_array_ops as gen_array_ops, math_ops as math_ops
from tensorflow.python.util import deprecation as deprecation
from typing import Any

def alias_inplace_update(x, i, v): ...
def alias_inplace_add(x, i, v): ...
def alias_inplace_sub(x, i, v): ...
def empty_like(x, init: Any | None = ...): ...
def inplace_update(x, i, v): ...
def inplace_add(x, i, v): ...
def inplace_sub(x, i, v): ...

empty: Any
