from tensorflow.python.ops.gen_map_ops import *
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, gen_map_ops as gen_map_ops

def empty_tensor_map(): ...
def tensor_map_size(input_handle): ...
def tensor_map_insert(input_handle, key, value): ...
def tensor_map_lookup(input_handle, key, value_dtype): ...
def tensor_map_erase(input_handle, key, value_dtype): ...
def tensor_map_has_key(input_handle, key): ...
def tensor_map_stack_keys(input_handle, key_dtype): ...
def LookupGrad(op, dval): ...
def InsertGrad(op, dmap): ...
def EraseGrad(op, dmap): ...
