from tensorflow.python.framework import dtypes as dtypes, ops as ops, sparse_tensor as sparse_tensor
from tensorflow.python.ops import gen_set_ops as gen_set_ops
from tensorflow.python.util import dispatch as dispatch
from tensorflow.python.util.tf_export import tf_export as tf_export

def set_size(a, validate_indices: bool = ...): ...
def set_intersection(a, b, validate_indices: bool = ...): ...
def set_difference(a, b, aminusb: bool = ..., validate_indices: bool = ...): ...
def set_union(a, b, validate_indices: bool = ...): ...
