from statsmodels.base.model import Model as Model
from typing import Any

class Results: ...

class NonlinearLS(Model):
    endog: Any
    exog: Any
    sigma: Any
    weights: Any
    def __init__(self, endog: Any | None = ..., exog: Any | None = ..., weights: Any | None = ..., sigma: Any | None = ..., missing: str = ...) -> None: ...
    def predict(self, exog, params: Any | None = ...): ...
    def start_value(self) -> None: ...
    def geterrors(self, params, weights: Any | None = ...): ...
    def errorsumsquares(self, params): ...
    df_resid: Any
    df_model: Any
    wendog: Any
    wexog: Any
    normalized_cov_params: Any
    def fit(self, start_value: Any | None = ..., nparams: Any | None = ..., **kw): ...
    def fit_minimal(self, start_value, **kwargs): ...
    def fit_random(self, ntries: int = ..., rvs_generator: Any | None = ..., nparams: Any | None = ...): ...
    def jac_predict(self, params): ...

class Myfunc(NonlinearLS): ...
