from typing import Any

from keras.src.engine.base_layer import Layer as Layer

class Reshape(Layer):
    target_shape: Any
    def __init__(self, target_shape, **kwargs) -> None: ...
    def compute_output_shape(self, input_shape): ...
    def call(self, inputs): ...
    def get_config(self): ...
