from .auxfuncs import *
from typing import Any

def getctype(var): ...
def getstrlength(var): ...
def getarrdims(a, var, verbose: int = ...): ...
def getpydocsign(a, var): ...
def getarrdocsign(a, var): ...
def getinit(a, var): ...
def sign2map(a, var): ...
def routsign2map(rout): ...
def modsign2map(m): ...
def cb_sign2map(a, var, index: Any | None = ...): ...
def cb_routsign2map(rout, um): ...
def common_sign2map(a, var): ...
