from .auxfuncs import getfortranname as getfortranname, isexternal as isexternal, isfunction as isfunction, isfunction_wrap as isfunction_wrap, isintent_in as isintent_in, isintent_out as isintent_out, islogicalfunction as islogicalfunction, ismoduleroutine as ismoduleroutine, isscalar as isscalar, issubroutine as issubroutine, issubroutine_wrap as issubroutine_wrap, outmess as outmess, show as show
from typing import Any

f2py_version: str

def var2fixfortran(vars, a, fa: Any | None = ..., f90mode: Any | None = ...): ...
def createfuncwrapper(rout, signature: int = ...): ...
def createsubrwrapper(rout, signature: int = ...): ...
def assubr(rout): ...
