from distutils.command.config import config as old_config
from numpy.distutils.command.autodist import check_compiler_gcc as check_compiler_gcc, check_gcc_function_attribute as check_gcc_function_attribute, check_gcc_function_attribute_with_intrinsics as check_gcc_function_attribute_with_intrinsics, check_gcc_variable_attribute as check_gcc_variable_attribute, check_gcc_version_at_least as check_gcc_version_at_least, check_inline as check_inline, check_restrict as check_restrict
from numpy.distutils.exec_command import filepath_from_subprocess_output as filepath_from_subprocess_output
from numpy.distutils.mingw32ccompiler import generate_manifest as generate_manifest
from typing import Any

class config(old_config):
    fcompiler: Any
    def initialize_options(self) -> None: ...
    def check_header(self, header, include_dirs: Any | None = ..., library_dirs: Any | None = ..., lang: str = ...): ...
    def check_decl(self, symbol, headers: Any | None = ..., include_dirs: Any | None = ...): ...
    def check_macro_true(self, symbol, headers: Any | None = ..., include_dirs: Any | None = ...): ...
    def check_type(self, type_name, headers: Any | None = ..., include_dirs: Any | None = ..., library_dirs: Any | None = ...): ...
    def check_type_size(self, type_name, headers: Any | None = ..., include_dirs: Any | None = ..., library_dirs: Any | None = ..., expected: Any | None = ...): ...
    def check_func(self, func, headers: Any | None = ..., include_dirs: Any | None = ..., libraries: Any | None = ..., library_dirs: Any | None = ..., decl: bool = ..., call: bool = ..., call_args: Any | None = ...): ...
    def check_funcs_once(self, funcs, headers: Any | None = ..., include_dirs: Any | None = ..., libraries: Any | None = ..., library_dirs: Any | None = ..., decl: bool = ..., call: bool = ..., call_args: Any | None = ...): ...
    def check_inline(self): ...
    def check_restrict(self): ...
    def check_compiler_gcc(self): ...
    def check_gcc_function_attribute(self, attribute, name): ...
    def check_gcc_function_attribute_with_intrinsics(self, attribute, name, code, include): ...
    def check_gcc_variable_attribute(self, attribute): ...
    def check_gcc_version_at_least(self, major, minor: int = ..., patchlevel: int = ...): ...
    def get_output(self, body, headers: Any | None = ..., include_dirs: Any | None = ..., libraries: Any | None = ..., library_dirs: Any | None = ..., lang: str = ..., use_tee: Any | None = ...): ...

class GrabStdout:
    sys_stdout: Any
    data: str
    def __init__(self) -> None: ...
    def write(self, data) -> None: ...
    def flush(self) -> None: ...
    def restore(self) -> None: ...
