from absl.testing.absltest import *
from tensorflow.python.framework import errors as errors
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.platform import benchmark as benchmark
from tensorflow.python.util import tf_decorator as tf_decorator, tf_inspect as tf_inspect
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

Benchmark: Any
absltest_main = main

def g_main(argv) -> None: ...
def main(argv: Any | None = ...): ...
def GetTempDir(): ...
def test_src_dir_path(relative_path): ...
def StatefulSessionAvailable(): ...

class StubOutForTesting:
    cache: Any
    stubs: Any
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, unused_exc_type, unused_exc_value, unused_tb) -> None: ...
    def CleanUp(self) -> None: ...
    def SmartSet(self, obj, attr_name, new_attr) -> None: ...
    def SmartUnsetAll(self) -> None: ...
    def Set(self, parent, child_name, new_child) -> None: ...
    def UnsetAll(self) -> None: ...
