from tensorflow.python.util.tf_export import tf_export as tf_export

def load_resource(path): ...
def get_data_files_path(): ...
def get_root_dir_with_all_resources(): ...
def get_path_to_datafile(path): ...
def readahead_file_path(path, readahead: str = ...): ...
