from tensorflow.python.client import pywrap_tf_session as pywrap_tf_session
from tensorflow.python.platform import build_info as build_info
from tensorflow.python.util.tf_export import tf_export as tf_export

def get_include(): ...
def get_lib(): ...
def get_compile_flags(): ...
def get_link_flags(): ...
def get_build_info(): ...
