from tensorflow.python.util import dispatch as dispatch
from tensorflow.python.util.tf_export import keras_export as keras_export

def epsilon(): ...
def set_epsilon(value) -> None: ...
def floatx(): ...
def set_floatx(value) -> None: ...
def image_data_format(): ...
def set_image_data_format(data_format) -> None: ...
