from sklearn.base import clone as clone
from sklearn.gaussian_process.kernels import GenericKernelMixin as GenericKernelMixin, Hyperparameter as Hyperparameter, Kernel as Kernel, StationaryKernelMixin as StationaryKernelMixin
from typing import Any

class MiniSeqKernel(GenericKernelMixin, StationaryKernelMixin, Kernel):
    baseline_similarity: Any
    baseline_similarity_bounds: Any
    def __init__(self, baseline_similarity: float = ..., baseline_similarity_bounds=...) -> None: ...
    @property
    def hyperparameter_baseline_similarity(self): ...
    def __call__(self, X, Y: Any | None = ..., eval_gradient: bool = ...): ...
    def diag(self, X): ...
    def clone_with_theta(self, theta): ...
