from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any

SPECIAL_BUILTINS: Any

def islambda(f): ...
def isnamedtuple(f): ...
def isbuiltin(f): ...
def isconstructor(cls): ...
def getimmediatesource(obj): ...
def getnamespace(f): ...
def getqualifiedname(namespace, object_, max_depth: int = ..., visited: Any | None = ...): ...
def getdefiningclass(m, owner_class): ...
def getmethodclass(m): ...
def getfutureimports(entity): ...
