from tensorflow.python.autograph.pyct import origin_info as origin_info, parser as parser

def load_source(source, delete_on_exit): ...
def load_ast(nodes, indentation: str = ..., include_source_map: bool = ..., delete_on_exit: bool = ...): ...
