import gast
from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser, pretty_printer as pretty_printer
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any

class LineLocation: ...

class Location:
    @property
    def line_loc(self): ...

class OriginInfo:
    def as_frame(self): ...

def create_source_map(nodes, code, filepath): ...

class _Function:
    name: Any
    def __init__(self, name) -> None: ...

class OriginResolver(gast.NodeVisitor):
    def __init__(self, root_node, source_lines, comments_map, context_lineno, context_col_offset, filepath) -> None: ...
    def visit(self, node) -> None: ...

def resolve(node, source, context_filepath, context_lineno, context_col_offset) -> None: ...
def resolve_entity(node, source, entity) -> None: ...
def copy_origin(from_node, to_node) -> None: ...
