from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.lang import directives as directives
from tensorflow.python.autograph.pyct import anno as anno
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any

STATIC_VALUE: str

class _LoopScope:
    ast_node: Any
    statements_visited: int
    def __init__(self) -> None: ...

class DirectivesTransformer(converter.Base):
    def visit_Name(self, node): ...
    def visit_Attribute(self, node): ...
    def visit_Assign(self, node): ...
    def visit_AugAssign(self, node): ...
    def visit_Expr(self, node): ...
    def visit_While(self, node): ...
    def visit_For(self, node): ...

def transform(node, ctx): ...
