from statsmodels.tools.sm_exceptions import ConvergenceWarning as ConvergenceWarning

def qc_results(params, alpha, score, qc_tol, qc_verbose: bool = ...): ...
def do_trim_params(params, k_params, alpha, score, passed, trim_mode, size_trim_tol, auto_trim_tol): ...
