from tensorflow.python.autograph.core import config as config, converter as converter
from tensorflow.python.autograph.impl import api as api
from tensorflow.python.framework import ops as ops
from tensorflow.python.platform import test as test
from typing import Any

def allowlist(f) -> None: ...
def is_inside_generated_code(): ...

class TestingTranspiler(api.PyToTF):
    transformed_ast: Any
    def __init__(self, converters, ag_overrides) -> None: ...
    def get_extra_locals(self): ...
    transform_ctx: Any
    def transform_ast(self, node, ctx): ...

class TestCase(test.TestCase):
    graph: Any
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def assertPrints(self, expected_result) -> None: ...
    def transform(self, f, converter_module, include_ast: bool = ..., ag_overrides: Any | None = ...): ...
