from tensorflow.python import pywrap_tfe as pywrap_tfe
from tensorflow.python.eager import context as context
from tensorflow.python.util.tf_export import tf_export as tf_export

def to_dlpack(tf_tensor): ...
def from_dlpack(dlcapsule): ...
