from .validation import check_array as check_array
from typing import Any

def unique_labels(*ys): ...
def is_multilabel(y): ...
def check_classification_targets(y) -> None: ...
def type_of_target(y): ...
def class_distribution(y, sample_weight: Any | None = ...): ...
