from tensorflow.python import pywrap_mlir as pywrap_mlir
from tensorflow.python.util.tf_export import tf_export as tf_export

def convert_graph_def(graph_def, pass_pipeline: str = ..., show_debug_info: bool = ...): ...
def convert_function(concrete_function, pass_pipeline: str = ..., show_debug_info: bool = ...): ...
