from sklearn.base import clone as clone
from sklearn.cluster import DBSCAN as DBSCAN, SpectralClustering as SpectralClustering
from sklearn.cluster.tests.common import generate_clustered_data as generate_clustered_data
from sklearn.datasets import make_blobs as make_blobs
from sklearn.manifold import Isomap as Isomap, SpectralEmbedding as SpectralEmbedding, TSNE as TSNE
from sklearn.neighbors import KNeighborsRegressor as KNeighborsRegressor, KNeighborsTransformer as KNeighborsTransformer, LocalOutlierFactor as LocalOutlierFactor, RadiusNeighborsRegressor as RadiusNeighborsRegressor, RadiusNeighborsTransformer as RadiusNeighborsTransformer
from sklearn.pipeline import make_pipeline as make_pipeline
from sklearn.utils._testing import assert_array_almost_equal as assert_array_almost_equal

def test_spectral_clustering() -> None: ...
def test_spectral_embedding() -> None: ...
def test_dbscan() -> None: ...
def test_isomap() -> None: ...
def test_tsne() -> None: ...
def test_lof_novelty_false() -> None: ...
def test_lof_novelty_true() -> None: ...
def test_kneighbors_regressor() -> None: ...
