from sklearn.metrics import euclidean_distances as euclidean_distances
from sklearn.neighbors import KNeighborsTransformer as KNeighborsTransformer, RadiusNeighborsTransformer as RadiusNeighborsTransformer

def test_transformer_result() -> None: ...
def test_explicit_diagonal() -> None: ...
