from sklearn.utils import check_random_state as check_random_state

def test_quadtree_boundary_computation() -> None: ...
def test_quadtree_similar_point() -> None: ...
def test_quad_tree_pickle(n_dimensions, protocol) -> None: ...
def test_qt_insert_duplicate(n_dimensions) -> None: ...
def test_summarize() -> None: ...
