from sklearn.datasets import make_blobs as make_blobs
from sklearn.exceptions import NotFittedError as NotFittedError
from sklearn.model_selection import GridSearchCV as GridSearchCV
from sklearn.neighbors import KDTree as KDTree, KernelDensity as KernelDensity, NearestNeighbors as NearestNeighbors
from sklearn.neighbors._ball_tree import kernel_norm as kernel_norm
from sklearn.pipeline import make_pipeline as make_pipeline
from sklearn.preprocessing import StandardScaler as StandardScaler
from sklearn.utils._testing import assert_allclose as assert_allclose

def compute_kernel_slow(Y, X, kernel, h): ...
def check_results(kernel, bandwidth, atol, rtol, X, Y, dens_true) -> None: ...
def test_kernel_density(kernel, bandwidth) -> None: ...
def test_kernel_density_sampling(n_samples: int = ..., n_features: int = ...) -> None: ...
def test_kde_algorithm_metric_choice(algorithm, metric) -> None: ...
def test_kde_score(n_samples: int = ..., n_features: int = ...) -> None: ...
def test_kde_badargs() -> None: ...
def test_kde_pipeline_gridsearch() -> None: ...
def test_kde_sample_weights() -> None: ...
def test_sample_weight_invalid() -> None: ...
def test_pickling(tmpdir, sample_weight) -> None: ...
def test_check_is_fitted(method) -> None: ...
