from _typeshed import Incomplete

def get_opt_parser(): ...
def are_values_different(*values): ...
def get_headers_diff(file_headers, names: Incomplete | None = None): ...
def get_data_hash_diff(files, dtype=...): ...
def get_data_diff(files, max_abs: int = 0, max_rel: int = 0, dtype=...): ...
def display_diff(files, diff): ...
def diff(
    files,
    header_fields: str = "all",
    data_max_abs_diff: Incomplete | None = None,
    data_max_rel_diff: Incomplete | None = None,
    dtype=...,
): ...
def main(args: Incomplete | None = None, out: Incomplete | None = None) -> None: ...
