from _typeshed import Incomplete

verbose_level: int

def verbose(thing, msg) -> None: ...
def table2string(table, out: Incomplete | None = None): ...
def ap(helplist, format_, sep: str = ", "): ...
def safe_get(obj, name): ...
