import tensorflow.compat.v2 as tf
from keras.layers.preprocessing import string_lookup as string_lookup
from typing import Any

class DistributeKplTestUtils(tf.test.TestCase):
    FEATURE_VOCAB: Any
    LABEL_VOCAB: Any
    def define_kpls_for_training(self, use_adapt): ...
    def dataset_fn(self, feature_mapper, label_mapper): ...
    def define_model(self): ...
    def define_reverse_lookup_layer(self): ...
    def create_serving_signature(self, model, feature_mapper, label_inverse_lookup_layer): ...
    def test_save_load_serving_model(self, model, feature_mapper, label_inverse_lookup_layer) -> None: ...
