from keras.utils import io_utils as io_utils
from typing import Any

def get_source_inputs(tensor, layer: Any | None = ..., node_index: Any | None = ...): ...
def validate_string_arg(input_data, allowable_strings, layer_name, arg_name, allow_none: bool = ..., allow_callables: bool = ...) -> None: ...
def count_params(weights): ...
def print_summary(model, line_length: Any | None = ..., positions: Any | None = ..., print_fn: Any | None = ..., expand_nested: bool = ..., show_trainable: bool = ...) -> None: ...
def convert_dense_weights_data_format(dense, previous_feature_map_shape, target_data_format: str = ...) -> None: ...
def is_builtin_layer(layer): ...
def cached_per_instance(f): ...
def filter_empty_layer_containers(layer_list) -> None: ...
