import inspect as _inspect
from typing import Any, NamedTuple

ArgSpec = _inspect.ArgSpec
# FullArgSpec = _inspect.FullArgSpec

class FullArgSpec(NamedTuple):
    args: Any
    varargs: Any
    varkw: Any
    defaults: Any
    kwonlyargs: Any
    kwonlydefaults: Any
    annotations: Any

def currentframe(): ...
def getargspec(obj): ...
def getfullargspec(obj): ...
def getcallargs(*func_and_positional, **named): ...
def getframeinfo(*args, **kwargs): ...
def getdoc(obj): ...
def getfile(obj): ...
def getmembers(obj, predicate: Any | None = ...): ...
def getmodule(obj): ...
def getmro(cls): ...
def getsource(obj): ...
def getsourcefile(obj): ...
def getsourcelines(obj): ...
def isbuiltin(obj): ...
def isclass(obj): ...
def isfunction(obj): ...
def isframe(obj): ...
def isgenerator(obj): ...
def isgeneratorfunction(obj): ...
def ismethod(obj): ...
def ismodule(obj): ...
def isroutine(obj): ...
def stack(context: int = ...): ...
