from typing import Any

def include_frame(fname): ...
def filter_traceback(fn): ...
def inject_argument_info_in_traceback(fn, object_name: Any | None = ...): ...
def format_argument_value(value): ...
