from tensorflow.core.protobuf import rewriter_config_pb2 as rewriter_config_pb2

def disable_non_trt_optimizers_in_rewriter_config(rewriter_config) -> None: ...
def is_linked_tensorrt_version_greater_equal(major, minor: int = ..., patch: int = ...): ...
def is_loaded_tensorrt_version_greater_equal(major, minor: int = ..., patch: int = ...): ...
