from sklearn.preprocessing import FunctionTransformer as FunctionTransformer
from sklearn.utils._testing import assert_allclose_dense_sparse as assert_allclose_dense_sparse, assert_array_equal as assert_array_equal

def test_delegate_to_func() -> None: ...
def test_np_log() -> None: ...
def test_kw_arg() -> None: ...
def test_kw_arg_update() -> None: ...
def test_kw_arg_reset() -> None: ...
def test_inverse_transform() -> None: ...
def test_check_inverse() -> None: ...
def test_function_transformer_frame() -> None: ...
def test_function_transformer_validate_inverse(): ...
