from sklearn import datasets as datasets
from sklearn.covariance import EmpiricalCovariance as EmpiricalCovariance, LedoitWolf as LedoitWolf, OAS as OAS, ShrunkCovariance as ShrunkCovariance, empirical_covariance as empirical_covariance, ledoit_wolf as ledoit_wolf, ledoit_wolf_shrinkage as ledoit_wolf_shrinkage, oas as oas, shrunk_covariance as shrunk_covariance
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal
from typing import Any

X: Any
X_1d: Any
n_samples: Any
n_features: Any

def test_covariance() -> None: ...
def test_shrunk_covariance() -> None: ...
def test_ledoit_wolf() -> None: ...
def test_ledoit_wolf_small() -> None: ...
def test_ledoit_wolf_large() -> None: ...
def test_ledoit_wolf_empty_array(ledoit_wolf_fitting_function) -> None: ...
def test_oas() -> None: ...
def test_EmpiricalCovariance_validates_mahalanobis() -> None: ...
