from sklearn import datasets as datasets
from sklearn.covariance import GraphicalLasso as GraphicalLasso, GraphicalLassoCV as GraphicalLassoCV, empirical_covariance as empirical_covariance, graphical_lasso as graphical_lasso
from sklearn.datasets import make_sparse_spd_matrix as make_sparse_spd_matrix
from sklearn.utils import check_random_state as check_random_state
from sklearn.utils._testing import assert_array_almost_equal as assert_array_almost_equal, assert_array_less as assert_array_less

def test_graphical_lasso(random_state: int = ...) -> None: ...
def test_graphical_lasso_iris() -> None: ...
def test_graph_lasso_2D() -> None: ...
def test_graphical_lasso_iris_singular() -> None: ...
def test_graphical_lasso_cv(random_state: int = ...) -> None: ...
def test_graphical_lasso_cv_grid_scores_and_cv_alphas_deprecated() -> None: ...
def test_graphical_lasso_cv_scores(suffix) -> None: ...
def test_graphical_lasso_cv_scores_deprecated() -> None: ...
