from sklearn.experimental import enable_iterative_imputer as enable_iterative_imputer
from sklearn.impute import IterativeImputer as IterativeImputer, KNNImputer as KNNImputer, SimpleImputer as SimpleImputer
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_allclose_dense_sparse as assert_allclose_dense_sparse, assert_array_equal as assert_array_equal
from typing import Any

IMPUTERS: Any
SPARSE_IMPUTERS: Any

def test_imputation_missing_value_in_test_array(imputer) -> None: ...
def test_imputers_add_indicator(marker, imputer) -> None: ...
def test_imputers_add_indicator_sparse(imputer, marker) -> None: ...
def test_imputers_pandas_na_integer_array_support(imputer, add_indicator) -> None: ...
