from typing import Any

def cohn_numbers(df, observations, censorship): ...
def plotting_positions(df, censorship, cohn): ...
def impute_ros(observations, censorship, df: Any | None = ..., min_uncensored: int = ..., max_fraction_censored: float = ..., substitution_fraction: float = ..., transform_in=..., transform_out=..., as_array: bool = ...): ...
