from keras import backend as backend
from keras.src.engine import keras_tensor as keras_tensor

def is_input_keras_tensor(tensor): ...
def find_nodes_by_inputs_and_outputs(inputs, outputs): ...
def clone_graph_nodes(inputs, outputs): ...
def clone_keras_tensors(args, keras_tensor_mapping): ...
