from _typeshed import Incomplete

ASCCONV_RE: Incomplete

class AscconvParseError(Exception): ...

class Atom:
    op: Incomplete
    obj_type: Incomplete
    obj_id: Incomplete
    def __init__(self, op, obj_type, obj_id) -> None: ...

class NoValue: ...

def assign2atoms(assign_ast, default_class=...): ...
def obj_from_atoms(atoms, namespace): ...
def parse_ascconv(ascconv_str, str_delim: str = '"'): ...
