from tensorflow.python.debug.cli import analyzer_cli as analyzer_cli, cli_config as cli_config, cli_shared as cli_shared, command_parser as command_parser, debugger_cli_common as debugger_cli_common, profile_analyzer_cli as profile_analyzer_cli, ui_factory as ui_factory
from tensorflow.python.debug.lib import common as common, debug_data as debug_data
from tensorflow.python.debug.wrappers import framework as framework
from tensorflow.python.lib.io import file_io as file_io
from typing import Any

class LocalCLIDebugWrapperSession(framework.BaseDebugWrapperSession):
    def __init__(self, sess, dump_root: Any | None = ..., log_usage: bool = ..., ui_type: str = ..., thread_name_filter: Any | None = ..., config_file_path: bool = ...) -> None: ...
    def add_tensor_filter(self, filter_name, tensor_filter) -> None: ...
    def on_session_init(self, request): ...
    def on_run_start(self, request): ...
    def on_run_end(self, request): ...
