from typing import Any

class EmptyContextManager:
    def __init__(self, obj) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args): ...
    def __getattr__(self, name): ...

def get_file_obj(fname, mode: str = ..., encoding: Any | None = ...): ...
