from tensorflow.python.eager import context as context
from tensorflow.python.framework import config as config, constant_op as constant_op, dtypes as dtypes, errors_impl as errors_impl, test_util as test_util
from tensorflow.python.ops import array_ops as array_ops, gradient_checker_v2 as gradient_checker_v2, nn_ops as nn_ops
from tensorflow.python.platform import test as test

class SparseXentOpTestBase(test.TestCase):
    def testSingleClass(self) -> None: ...
    def testInvalidLabelGPU(self) -> None: ...
    def testInvalidLabelCPU(self) -> None: ...
    def testNpXent(self) -> None: ...
    def testShapeMismatch(self) -> None: ...
    def testScalar(self) -> None: ...
    def testLabelsPlaceholderScalar(self) -> None: ...
    def testVector(self) -> None: ...
    def testFloat(self) -> None: ...
    def testDouble(self) -> None: ...
    def testHalf(self) -> None: ...
    def testEmpty(self) -> None: ...
    def testGradient(self): ...
    def testSecondGradient(self): ...
    def testHighDim(self) -> None: ...
    def testHighDim2(self) -> None: ...
    def testScalarHandling(self) -> None: ...
