from .. import rcmod as rcmod, utils as utils
from ..utils import get_color_cycle as get_color_cycle, get_dataset_names as get_dataset_names, load_dataset as load_dataset, remove_na as remove_na
from typing import Any

a_norm: Any

def test_pmf_hist_basics() -> None: ...
def test_ci_to_errsize() -> None: ...
def test_desaturate() -> None: ...
def test_desaturation_prop() -> None: ...
def test_saturate() -> None: ...
def test_sig_stars(p, annot) -> None: ...
def test_iqr() -> None: ...
def test_to_utf8(s, exp) -> None: ...

class TestSpineUtils:
    sides: Any
    outer_sides: Any
    inner_sides: Any
    offset: int
    original_position: Any
    offset_position: Any
    def test_despine(self) -> None: ...
    def test_despine_specific_axes(self) -> None: ...
    def test_despine_with_offset(self) -> None: ...
    def test_despine_side_specific_offset(self) -> None: ...
    def test_despine_with_offset_specific_axes(self) -> None: ...
    def test_despine_trim_spines(self) -> None: ...
    def test_despine_trim_inverted(self) -> None: ...
    def test_despine_trim_noticks(self) -> None: ...
    def test_despine_trim_categorical(self) -> None: ...
    def test_despine_moved_ticks(self) -> None: ...

def test_ticklabels_overlap() -> None: ...
def test_locator_to_legend_entries() -> None: ...
def test_move_legend_matplotlib_objects() -> None: ...
def test_move_legend_grid_object(long_df) -> None: ...
def test_move_legend_input_checks() -> None: ...
def check_load_dataset(name) -> None: ...
def check_load_cached_dataset(name) -> None: ...
def test_get_dataset_names() -> None: ...
def test_load_datasets() -> None: ...
def test_load_dataset_string_error() -> None: ...
def test_load_dataset_passed_data_error() -> None: ...
def test_load_cached_datasets() -> None: ...
def test_relative_luminance() -> None: ...
def test_get_color_cycle(cycler, result) -> None: ...
def test_remove_na() -> None: ...
def test_assign_default_kwargs() -> None: ...
def test_draw_figure() -> None: ...
