from .. import palettes as palettes, rcmod as rcmod, utils as utils
from ..colors import crayons as crayons, xkcd_rgb as xkcd_rgb
from ..external import husl as husl

class TestColorPalettes:
    def test_current_palette(self) -> None: ...
    def test_palette_context(self) -> None: ...
    def test_big_palette_context(self) -> None: ...
    def test_palette_size(self) -> None: ...
    def test_seaborn_palettes(self) -> None: ...
    def test_hls_palette(self) -> None: ...
    def test_husl_palette(self) -> None: ...
    def test_mpl_palette(self) -> None: ...
    def test_mpl_dark_palette(self) -> None: ...
    def test_bad_palette_name(self) -> None: ...
    def test_terrible_palette_name(self) -> None: ...
    def test_bad_palette_colors(self) -> None: ...
    def test_palette_desat(self) -> None: ...
    def test_palette_is_list_of_tuples(self) -> None: ...
    def test_palette_cycles(self) -> None: ...
    def test_hls_values(self) -> None: ...
    def test_husl_values(self) -> None: ...
    def test_cbrewer_qual(self) -> None: ...
    def test_mpl_reversal(self) -> None: ...
    def test_rgb_from_hls(self) -> None: ...
    def test_rgb_from_husl(self) -> None: ...
    def test_rgb_from_xkcd(self) -> None: ...
    def test_light_palette(self) -> None: ...
    def test_dark_palette(self) -> None: ...
    def test_diverging_palette(self) -> None: ...
    def test_blend_palette(self) -> None: ...
    def test_cubehelix_against_matplotlib(self) -> None: ...
    def test_cubehelix_n_colors(self) -> None: ...
    def test_cubehelix_reverse(self) -> None: ...
    def test_cubehelix_cmap(self) -> None: ...
    def test_cubehelix_code(self) -> None: ...
    def test_xkcd_palette(self) -> None: ...
    def test_crayon_palette(self) -> None: ...
    def test_color_codes(self) -> None: ...
    def test_as_hex(self) -> None: ...
    def test_preserved_palette_length(self) -> None: ...
    def test_html_rep(self) -> None: ...
