def random() -> None: ...
def test_bootstrap(random) -> None: ...
def test_bootstrap_length(random) -> None: ...
def test_bootstrap_range(random) -> None: ...
def test_bootstrap_multiarg(random): ...
def test_bootstrap_axis(random) -> None: ...
def test_bootstrap_seed(random) -> None: ...
def test_bootstrap_ols(random): ...
def test_bootstrap_units(random) -> None: ...
def test_bootstrap_arglength() -> None: ...
def test_bootstrap_string_func() -> None: ...
def test_bootstrap_reproducibility(random) -> None: ...
def test_seed_new() -> None: ...
def test_seed_old(seed1, seed2, match) -> None: ...
def test_bad_seed_old() -> None: ...
