from statsmodels.compat.python import lrange as lrange
from typing import Any

class MPLConfigurator:
    def __init__(self) -> None: ...
    def revert(self) -> None: ...
    def set_fontsize(self, size) -> None: ...

def plot_mts(Y, names: Any | None = ..., index: Any | None = ...): ...
def plot_var_forc(prior, forc, err_upper, err_lower, index: Any | None = ..., names: Any | None = ..., plot_stderr: bool = ..., legend_options: Any | None = ...): ...
def plot_with_error(y, error, x: Any | None = ..., axes: Any | None = ..., value_fmt: str = ..., error_fmt: str = ..., alpha: float = ..., stderr_type: str = ...): ...
def plot_full_acorr(acorr, fontsize: int = ..., linewidth: int = ..., xlabel: Any | None = ..., err_bound: Any | None = ...): ...
def acorr_plot(acorr, linewidth: int = ..., xlabel: Any | None = ..., ax: Any | None = ...) -> None: ...
def plot_acorr_with_error() -> None: ...
def adjust_subplots(**kwds) -> None: ...
def irf_grid_plot(values, stderr, impcol, rescol, names, title, signif: float = ..., hlines: Any | None = ..., subplot_params: Any | None = ..., plot_params: Any | None = ..., figsize=..., stderr_type: str = ...): ...
