from sklearn.exceptions import ConvergenceWarning as ConvergenceWarning, NotFittedError as NotFittedError
from sklearn.metrics.cluster import adjusted_rand_score as adjusted_rand_score
from sklearn.mixture import BayesianGaussianMixture as BayesianGaussianMixture
from sklearn.mixture.tests.test_gaussian_mixture import RandomData as RandomData
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_equal as assert_array_equal, ignore_warnings as ignore_warnings
from typing import Any

COVARIANCE_TYPE: Any
PRIOR_TYPE: Any

def test_log_dirichlet_norm() -> None: ...
def test_log_wishart_norm() -> None: ...
def test_bayesian_mixture_covariance_type() -> None: ...
def test_bayesian_mixture_weight_concentration_prior_type() -> None: ...
def test_bayesian_mixture_weights_prior_initialisation() -> None: ...
def test_bayesian_mixture_mean_prior_initialisation() -> None: ...
def test_bayesian_mixture_precisions_prior_initialisation() -> None: ...
def test_bayesian_mixture_check_is_fitted() -> None: ...
def test_bayesian_mixture_weights() -> None: ...
def test_monotonic_likelihood() -> None: ...
def test_compare_covar_type() -> None: ...
def test_check_covariance_precision() -> None: ...
def test_invariant_translation() -> None: ...
def test_bayesian_mixture_fit_predict(seed, max_iter, tol) -> None: ...
def test_bayesian_mixture_fit_predict_n_init() -> None: ...
def test_bayesian_mixture_predict_predict_proba() -> None: ...
