from pandas import get_option as get_option, option_context as option_context
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame

def read_clipboard(sep: str = ..., **kwargs): ...
def to_clipboard(obj, excel: Union[bool, None] = ..., sep: Union[str, None] = ..., **kwargs) -> None: ...
