from statsmodels.stats.base import HolderTuple as HolderTuple
from typing import Any

def test_chisquare_binning(counts, expected, sort_var: Any | None = ..., bins: int = ..., df: Any | None = ..., ordered: bool = ..., sort_method: str = ..., alpha_nc: float = ...): ...
def prob_larger_ordinal_choice(prob): ...
def prob_larger_2ordinal(probs1, probs2): ...
def cov_multinomial(probs): ...
def var_multinomial(probs): ...
