from typing import Any

class ResultsBunch(dict):
    template: str
    __dict__: Any
    def __init__(self, **kwds) -> None: ...

def aggregate_raters(data, n_cat: Any | None = ...): ...
def to_table(data, bins: Any | None = ...): ...
def fleiss_kappa(table, method: str = ...): ...
def cohens_kappa(table, weights: Any | None = ..., return_results: bool = ..., wt: Any | None = ...): ...

class KappaResults(ResultsBunch):
    template: Any
