def mc2mnc(mc): ...
def mnc2mc(mnc, wmean: bool = ...): ...
def cum2mc(kappa): ...
def mnc2cum(mnc): ...
def mc2cum(mc): ...
def mvsk2mc(args): ...
def mvsk2mnc(args): ...
def mc2mvsk(args): ...
def mnc2mvsk(args): ...
def cov2corr(cov, return_std: bool = ...): ...
def corr2cov(corr, std): ...
def se_cov(cov): ...
