from statsmodels.tools.tools import Bunch as Bunch

def partial_project(endog, exog): ...
def cancorr(x1, x2, demean: bool = ..., standardize: bool = ...): ...
def cc_ranktest(x1, x2, demean: bool = ..., fullrank: bool = ...): ...
def cc_stats(x1, x2, demean: bool = ...): ...
