from statsmodels.stats._knockoff import RegressionFDR as RegressionFDR
from typing import Any

def multipletests(pvals, alpha: float = ..., method: str = ..., is_sorted: bool = ..., returnsorted: bool = ...): ...
def fdrcorrection(pvals, alpha: float = ..., method: str = ..., is_sorted: bool = ...): ...
def fdrcorrection_twostage(pvals, alpha: float = ..., method: str = ..., iter: bool = ..., is_sorted: bool = ...): ...
def local_fdr(zscores, null_proportion: float = ..., null_pdf: Any | None = ..., deg: int = ..., nbins: int = ..., alpha: int = ...): ...

class NullDistribution:
    mean: Any
    sd: Any
    null_proportion: Any
    def __init__(self, zscores, null_lb: int = ..., null_ub: int = ..., estimate_mean: bool = ..., estimate_scale: bool = ..., estimate_null_proportion: bool = ...): ...
    def pdf(self, zscores): ...
