from statsmodels.regression.linear_model import OLS as OLS
from typing import Any

class RegularizedInvCovariance:
    exog: Any
    def __init__(self, exog) -> None: ...
    def fit(self, alpha: int = ...) -> None: ...
    def approx_inv_cov(self): ...
