from typing import Any

KERAS_ATTR: str
KERAS_CACHE_KEY: str
SAVED_METADATA_PATH: str
INPUT_LAYER_IDENTIFIER: str
LAYER_IDENTIFIER: str
METRIC_IDENTIFIER: str
MODEL_IDENTIFIER: str
NETWORK_IDENTIFIER: str
RNN_LAYER_IDENTIFIER: str
SEQUENTIAL_IDENTIFIER: str
KERAS_OBJECT_IDENTIFIERS: Any
