import json
from tensorflow.python.framework import dtypes as dtypes, tensor_shape as tensor_shape, type_spec as type_spec

class Encoder(json.JSONEncoder):
    def default(self, obj): ...
    def encode(self, obj): ...

def decode(json_string): ...
def get_json_type(obj): ...
