from matplotlib import cbook as cbook
from matplotlib.axes._axes import Axes as Axes
from matplotlib.gridspec import GridSpec as GridSpec, SubplotSpec as SubplotSpec
from typing import Any

class SubplotBase:
    def __init__(self, fig, *args, **kwargs) -> None: ...
    def get_geometry(self): ...
    def change_geometry(self, numrows, numcols, num) -> None: ...
    def get_subplotspec(self): ...
    def set_subplotspec(self, subplotspec) -> None: ...
    def get_gridspec(self): ...
    @property
    def figbox(self): ...
    @property
    def numRows(self): ...
    @property
    def numCols(self): ...
    def update_params(self) -> None: ...
    def is_first_row(self): ...
    def is_last_row(self): ...
    def is_first_col(self): ...
    def is_last_col(self): ...
    def label_outer(self) -> None: ...

subplot_class_factory: Any
Subplot: Any
