from keras import backend as backend
from typing import Any

FLAGS: Any

def global_batch_size_supported(distribution_strategy): ...
def call_replica_local_fn(fn, *args, **kwargs): ...
def is_distributed_variable(v): ...
def get_strategy(): ...
