from keras.distribute import keras_correctness_test_base as keras_correctness_test_base
from typing import Any

class DistributionStrategyEmbeddingModelCorrectnessTest(keras_correctness_test_base.TestDistributionStrategyEmbeddingModelCorrectnessBase):
    def get_model(self, max_words: int = ..., initial_weights: Any | None = ..., distribution: Any | None = ..., input_shapes: Any | None = ...): ...
    use_distributed_dense: bool
    def test_embedding_model_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_embedding_time_distributed_model_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...

class DistributionStrategySiameseEmbeddingModelCorrectnessTest(keras_correctness_test_base.TestDistributionStrategyEmbeddingModelCorrectnessBase):
    def get_model(self, max_words: int = ..., initial_weights: Any | None = ..., distribution: Any | None = ..., input_shapes: Any | None = ...): ...
    def get_data(self, count=..., min_words: int = ..., max_words: int = ..., max_word_id: int = ..., num_classes: int = ...): ...
    def test_siamese_embedding_model_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
