from keras.distribute import keras_correctness_test_base as keras_correctness_test_base
from typing import Any

def strategies_for_stateful_embedding_model(): ...
def test_combinations_for_stateful_embedding_model(): ...

class DistributionStrategyStatefulLstmModelCorrectnessTest(keras_correctness_test_base.TestDistributionStrategyEmbeddingModelCorrectnessBase):
    def get_model(self, max_words: int = ..., initial_weights: Any | None = ..., distribution: Any | None = ..., input_shapes: Any | None = ...): ...
    def disabled_test_stateful_lstm_model_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_incorrectly_use_multiple_cores_for_stateful_lstm_model(self, distribution, use_numpy, use_validation_data) -> None: ...
