import tensorflow.compat.v2 as tf
from absl.testing import parameterized
from keras.distribute import model_combinations as model_combinations
from typing import Any

PREDICT_STEPS: int
simple_models: Any
strategies: Any

def simple_models_with_strategies(): ...
def simple_models_with_strategy_pairs(): ...
def tfmodule_models_with_strategies(): ...
def tfmodule_models_with_strategy_pairs(): ...
def load_and_run_with_saved_model_api(distribution, saved_dir, predict_dataset, output_name): ...

class TestSavedModelBase(tf.test.TestCase, parameterized.TestCase):
    def setUp(self) -> None: ...
    def run_test_save_no_strategy_restore_strategy(self, model_and_input, distribution) -> None: ...
    def run_test_save_strategy_restore_no_strategy(self, model_and_input, distribution, save_in_scope) -> None: ...
    def run_test_save_strategy_restore_strategy(self, model_and_input, distribution_for_saving, distribution_for_restoring, save_in_scope) -> None: ...
    def run_test_save_strategy(self, model_and_input, distribution, save_in_scope): ...
