from keras.legacy_tf_layers import core as core, normalization as normalization
from keras.optimizer_v2 import optimizer_v2 as optimizer_v2

def minimize_loss_example(optimizer, use_bias: bool = ..., use_callable_loss: bool = ...): ...
def batchnorm_example(optimizer_fn, batch_per_epoch: int = ..., momentum: float = ..., renorm: bool = ..., update_ops_in_replica_mode: bool = ...): ...
