from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.core.indexes.api import MultiIndex as MultiIndex

def flex_binary_moment(arg1, arg2, f, pairwise: bool = ...): ...
def zsqrt(x): ...
def prep_binary(arg1, arg2): ...
