from _typeshed import Incomplete

from ...fileslice import strided_scalar as strided_scalar
from ...testing import clear_and_catch_warnings as clear_and_catch_warnings
from ...tests.nibabel_data import get_nibabel_data as get_nibabel_data
from ...tests.nibabel_data import needs_nibabel_data as needs_nibabel_data
from ...tmpdirs import InTemporaryDirectory as InTemporaryDirectory
from .. import read_annot as read_annot
from .. import read_geometry as read_geometry
from .. import read_label as read_label
from .. import read_morph_data as read_morph_data
from .. import write_annot as write_annot
from .. import write_geometry as write_geometry
from .. import write_morph_data as write_morph_data

DATA_SDIR: str
have_freesurfer: bool
data_path: Incomplete
nib_data: Incomplete
freesurfer_test: Incomplete

def test_geometry() -> None: ...
def test_quad_geometry() -> None: ...
def test_morph_data() -> None: ...
def test_write_morph_data() -> None: ...
def test_annot() -> None: ...
def test_read_write_annot() -> None: ...
def test_write_annot_fill_ctab() -> None: ...
def test_read_annot_old_format() -> None: ...
def test_label() -> None: ...
def test_write_annot_maxstruct() -> None: ...
