import numpy as np
from pandas.core.dtypes.common import is_bool as is_bool, is_integer as is_integer
from pandas.util._exceptions import find_stack_level as find_stack_level
from typing import Union, Iterable, Sequence

def validate_args(fname, args, max_fname_arg_count, compat_args) -> None: ...
def validate_kwargs(fname, kwargs, compat_args) -> None: ...
def validate_args_and_kwargs(fname, args, kwargs, max_fname_arg_count, compat_args) -> None: ...
def validate_bool_kwarg(value, arg_name, none_allowed: bool = ..., int_allowed: bool = ...): ...
def validate_axis_style_args(data, args, kwargs, arg_name, method_name): ...
def validate_fillna_kwargs(value, method, validate_scalar_dict_value: bool = ...): ...
def validate_percentile(q: Union[float, Iterable[float]]) -> np.ndarray: ...
def validate_ascending(ascending: Union[bool, int, Sequence[Union[bool, int]]] = ...): ...
def validate_endpoints(closed: Union[str, None]) -> tuple[bool, bool]: ...
def validate_inclusive(inclusive: Union[str, None]) -> tuple[bool, bool]: ...
def validate_insert_loc(loc: int, length: int) -> int: ...
