from typing import Any

def load_checkpoint(ckpt_dir_or_file): ...
def load_variable(ckpt_dir_or_file, name): ...
def list_variables(ckpt_dir_or_file): ...
def checkpoints_iterator(checkpoint_dir, min_interval_secs: int = ..., timeout: Any | None = ..., timeout_fn: Any | None = ...) -> None: ...
def init_from_checkpoint(ckpt_dir_or_file, assignment_map): ...
