from tensorflow.python.framework import dtypes as dtypes, errors_impl as errors_impl
from tensorflow.python.util import compat as compat
from tensorflow.python.util._pywrap_checkpoint_reader import CheckpointReader as CheckpointReader
from tensorflow.python.util.tf_export import tf_export as tf_export

def error_translator(e) -> None: ...
def get_variable_to_dtype_map(self): ...
def has_tensor(self, tensor_str): ...
def get_tensor(self, tensor_str): ...
def NewCheckpointReader(filepattern): ...
