from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

class SessionRunHook:
    def begin(self) -> None: ...
    def after_create_session(self, session, coord) -> None: ...
    def before_run(self, run_context) -> None: ...
    def after_run(self, run_context, run_values) -> None: ...
    def end(self, session) -> None: ...

class SessionRunArgs:
    def __new__(cls, fetches, feed_dict: Any | None = ..., options: Any | None = ...): ...

class SessionRunContext:
    def __init__(self, original_args, session) -> None: ...
    @property
    def original_args(self): ...
    @property
    def session(self): ...
    @property
    def stop_requested(self): ...
    def request_stop(self) -> None: ...

class SessionRunValues: ...
