from tensorflow.compiler.xla.experimental.xla_sharding import xla_sharding as xla_sharding
from tensorflow.python.distribute import distribution_strategy_context as distribution_strategy_context
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, resource_variable_ops as resource_variable_ops, variable_scope as variable_scope, variables as variables
from typing import Any

def create_slot(primary, val, name, colocate_with_primary: bool = ..., *, copy_xla_sharding: bool = ...): ...
def create_slot_with_initializer(primary, initializer, shape, dtype, name, colocate_with_primary: bool = ..., *, copy_xla_sharding: bool = ...): ...
def create_zeros_slot(primary, name, dtype: Any | None = ..., colocate_with_primary: bool = ..., *, copy_xla_sharding: bool = ...): ...
