from statsmodels.tools.tools import Bunch as Bunch
from statsmodels.tsa.statespace import initialization as initialization, mlemodel as mlemodel
from statsmodels.tsa.statespace.kalman_smoother import SMOOTHER_STATE as SMOOTHER_STATE, SMOOTHER_STATE_AUTOCOV as SMOOTHER_STATE_AUTOCOV, SMOOTHER_STATE_COV as SMOOTHER_STATE_COV
from statsmodels.tsa.statespace.tools import constrain_stationary_univariate as constrain_stationary_univariate, unconstrain_stationary_univariate as unconstrain_stationary_univariate
from typing import Any

class QuarterlyAR1(mlemodel.MLEModel):
    def __init__(self, endog) -> None: ...
    @property
    def param_names(self): ...
    @property
    def start_params(self): ...
    def fit(self, *args, **kwargs): ...
    def fit_em(self, start_params: Any | None = ..., transformed: bool = ..., cov_type: str = ..., cov_kwds: Any | None = ..., maxiter: int = ..., tolerance: float = ..., em_initialization: bool = ..., mstep_method: Any | None = ..., full_output: bool = ..., return_params: bool = ..., low_memory: bool = ...): ...
    def transform_params(self, unconstrained): ...
    def untransform_params(self, constrained): ...
    def update(self, params, **kwargs) -> None: ...
