from . import tools as tools
from typing import Any

class Initialization:
    k_states: Any
    blocks: Any
    initialization_type: Any
    constant: Any
    stationary_cov: Any
    approximate_diffuse_variance: Any
    prefix_initialization_map: Any
    def __init__(self, k_states, initialization_type: Any | None = ..., initialization_classes: Any | None = ..., approximate_diffuse_variance: float = ..., constant: Any | None = ..., stationary_cov: Any | None = ...) -> None: ...
    def __setitem__(self, index, initialization_type) -> None: ...
    def set(self, index, initialization_type, constant: Any | None = ..., stationary_cov: Any | None = ..., approximate_diffuse_variance: Any | None = ...) -> None: ...
    def unset(self, index) -> None: ...
    def clear(self) -> None: ...
    @property
    def initialized(self): ...
    def __call__(self, index: Any | None = ..., model: Any | None = ..., initial_state_mean: Any | None = ..., initial_diffuse_state_cov: Any | None = ..., initial_stationary_state_cov: Any | None = ..., complex_step: bool = ...): ...
