from tensorflow.python.ops.distributions import special_math as special_math

def test_moment_matching(samples, number_moments, dist, stride: int = ...): ...
def chi_squared(x, bins): ...
def normal_cdf(x): ...
def anderson_darling(x): ...
def test_truncated_normal(assert_equal, assert_all_close, n, y, mean_atol: float = ..., median_atol: float = ..., variance_rtol: float = ...): ...
