from gi.repository import Gtk
from matplotlib import backend_tools as backend_tools, cbook as cbook
from matplotlib.backend_bases import NavigationToolbar2 as NavigationToolbar2, TimerBase as TimerBase, _Backend
from typing import Any

backend_version: Any

class TimerGTK(TimerBase):
    def __init__(self, *args, **kwargs) -> None: ...

class _NavigationToolbar2GTK(NavigationToolbar2):
    def set_message(self, s) -> None: ...
    def draw_rubberband(self, event, x0, y0, x1, y1) -> None: ...
    def remove_rubberband(self) -> None: ...
    def pan(self, *args) -> None: ...
    def zoom(self, *args) -> None: ...
    def set_history_buttons(self) -> None: ...

class RubberbandGTK(backend_tools.RubberbandBase):
    def draw_rubberband(self, x0, y0, x1, y1) -> None: ...
    def remove_rubberband(self) -> None: ...

class ConfigureSubplotsGTK(backend_tools.ConfigureSubplotsBase, Gtk.Window):
    def trigger(self, *args) -> None: ...

class _BackendGTK(_Backend):
    @staticmethod
    def mainloop() -> None: ...
