from typing import Any

QT_API_PYQT6: str
QT_API_PYSIDE6: str
QT_API_PYQT5: str
QT_API_PYSIDE2: str
QT_API_PYQTv2: str
QT_API_PYSIDE: str
QT_API_PYQT: str
QT_API_ENV: Any
QT_API = QT_API_PYQT6
QT_API = QT_API_PYSIDE6
QT_API = QT_API_PYQT5
QT_API = QT_API_PYSIDE2

class __getattr__:
    ETS: Any
    QT_RC_MAJOR_VERSION: Any
