from typing import Any

def is_data_frame(obj): ...
def is_design_matrix(obj): ...
def interpret_data(data, colnames: Any | None = ..., rownames: Any | None = ...): ...
def struct_to_ndarray(arr): ...
