def logdet_symm(m, check_symm: bool = ...): ...
def stationary_solve(r, b): ...
def transf_constraints(constraints): ...
def matrix_sqrt(mat, inverse: bool = ..., full: bool = ..., nullspace: bool = ..., threshold: float = ...): ...
