from statsmodels.compat.pandas import Appender as Appender, Substitution as Substitution
from typing import Any

EPS: Any

def approx_fprime(x, f, epsilon: Any | None = ..., args=..., kwargs=..., centered: bool = ...): ...
def approx_fprime_cs(x, f, epsilon: Any | None = ..., args=..., kwargs=...): ...
def approx_hess_cs(x, f, epsilon: Any | None = ..., args=..., kwargs=...): ...
def approx_hess1(x, f, epsilon: Any | None = ..., args=..., kwargs=..., return_grad: bool = ...): ...
def approx_hess2(x, f, epsilon: Any | None = ..., args=..., kwargs=..., return_grad: bool = ...): ...
def approx_hess3(x, f, epsilon: Any | None = ..., args=..., kwargs=...): ...
approx_hess = approx_hess3
