from typing import Any

def discrepancy(sample, bounds: Any | None = ...): ...
def primes_from_2_to(n): ...
def n_primes(n): ...
def van_der_corput(n_sample, base: int = ..., start_index: int = ...): ...
def halton(dim, n_sample, bounds: Any | None = ..., start_index: int = ...): ...
