from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, special_math_ops as special_math_ops
from tensorflow.python.util import dispatch as dispatch
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def kaiser_window(window_length, beta: float = ..., dtype=..., name: Any | None = ...): ...
def kaiser_bessel_derived_window(window_length, beta: float = ..., dtype=..., name: Any | None = ...): ...
def vorbis_window(window_length, dtype=..., name: Any | None = ...): ...
def hann_window(window_length, periodic: bool = ..., dtype=..., name: Any | None = ...): ...
def hamming_window(window_length, periodic: bool = ..., dtype=..., name: Any | None = ...): ...
