from sklearn.exceptions import ConvergenceWarning as ConvergenceWarning
from sklearn.linear_model import LinearRegression as LinearRegression, TheilSenRegressor as TheilSenRegressor
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal

def no_stdout_stderr() -> None: ...
def gen_toy_problem_1d(intercept: bool = ...): ...
def gen_toy_problem_2d(): ...
def gen_toy_problem_4d(): ...
def test_modweiszfeld_step_1d() -> None: ...
def test_modweiszfeld_step_2d() -> None: ...
def test_spatial_median_1d() -> None: ...
def test_spatial_median_2d(): ...
def test_theil_sen_1d() -> None: ...
def test_theil_sen_1d_no_intercept() -> None: ...
def test_theil_sen_2d() -> None: ...
def test_calc_breakdown_point() -> None: ...
def test_checksubparams_negative_subpopulation() -> None: ...
def test_checksubparams_too_few_subsamples() -> None: ...
def test_checksubparams_too_many_subsamples() -> None: ...
def test_checksubparams_n_subsamples_if_less_samples_than_features() -> None: ...
def test_subpopulation() -> None: ...
def test_subsamples() -> None: ...
def test_verbosity() -> None: ...
def test_theil_sen_parallel() -> None: ...
def test_less_samples_than_features() -> None: ...
