from sklearn.feature_extraction.image import PatchExtractor as PatchExtractor, extract_patches_2d as extract_patches_2d, grid_to_graph as grid_to_graph, img_to_graph as img_to_graph, reconstruct_from_patches_2d as reconstruct_from_patches_2d
from sklearn.utils._testing import ignore_warnings as ignore_warnings
from typing import Any

def test_img_to_graph() -> None: ...
def test_img_to_graph_sparse() -> None: ...
def test_grid_to_graph() -> None: ...
def test_connect_regions() -> None: ...
def test_connect_regions_with_grid() -> None: ...

downsampled_face: Any
orange_face: Any
face_collection: Any

def test_extract_patches_all() -> None: ...
def test_extract_patches_all_color() -> None: ...
def test_extract_patches_all_rect() -> None: ...
def test_extract_patches_max_patches() -> None: ...
def test_extract_patch_same_size_image() -> None: ...
def test_extract_patches_less_than_max_patches() -> None: ...
def test_reconstruct_patches_perfect() -> None: ...
def test_reconstruct_patches_perfect_color() -> None: ...
def test_patch_extractor_fit() -> None: ...
def test_patch_extractor_max_patches() -> None: ...
def test_patch_extractor_max_patches_default() -> None: ...
def test_patch_extractor_all_patches() -> None: ...
def test_patch_extractor_color() -> None: ...
def test_extract_patches_strided() -> None: ...
def test_extract_patches_square() -> None: ...
def test_width_patch() -> None: ...
