from sklearn.feature_extraction import FeatureHasher as FeatureHasher
from sklearn.utils._testing import fails_if_pypy as fails_if_pypy, ignore_warnings as ignore_warnings

pytestmark = fails_if_pypy

def test_feature_hasher_dicts() -> None: ...
def test_feature_hasher_strings() -> None: ...
def test_hashing_transform_seed() -> None: ...
def test_feature_hasher_pairs() -> None: ...
def test_feature_hasher_pairs_with_string_values() -> None: ...
def test_hash_empty_input() -> None: ...
def test_hasher_invalid_input() -> None: ...
def test_hasher_set_params() -> None: ...
def test_hasher_zeros() -> None: ...
def test_hasher_alternate_sign() -> None: ...
def test_hash_collisions() -> None: ...
