from sklearn.feature_extraction import DictVectorizer as DictVectorizer
from sklearn.feature_selection import SelectKBest as SelectKBest, chi2 as chi2

def test_dictvectorizer(sparse, dtype, sort, iterable) -> None: ...
def test_feature_selection(get_names) -> None: ...
def test_one_of_k(get_names) -> None: ...
def test_iterable_value(get_names) -> None: ...
def test_iterable_not_string_error() -> None: ...
def test_mapping_error() -> None: ...
def test_unseen_or_no_features() -> None: ...
def test_deterministic_vocabulary() -> None: ...
def test_n_features_in() -> None: ...
def test_feature_union_get_feature_names_deprecated() -> None: ...
def test_dictvectorizer_dense_sparse_equivalence() -> None: ...
def test_dict_vectorizer_unsupported_value_type() -> None: ...
def test_dict_vectorizer_get_feature_names_out() -> None: ...
