from .numeric import ndarray
from typing import Any

def equal(x1, x2): ...
def not_equal(x1, x2): ...
def greater_equal(x1, x2): ...
def less_equal(x1, x2): ...
def greater(x1, x2): ...
def less(x1, x2): ...
def str_len(a): ...
def add(x1, x2): ...
def multiply(a, i): ...
def mod(a, values): ...
def capitalize(a): ...
def center(a, width, fillchar: str = ...): ...
def count(a, sub, start: int = ..., end: Any | None = ...): ...
def decode(a, encoding: Any | None = ..., errors: Any | None = ...): ...
def encode(a, encoding: Any | None = ..., errors: Any | None = ...): ...
def endswith(a, suffix, start: int = ..., end: Any | None = ...): ...
def expandtabs(a, tabsize: int = ...): ...
def find(a, sub, start: int = ..., end: Any | None = ...): ...
def index(a, sub, start: int = ..., end: Any | None = ...): ...
def isalnum(a): ...
def isalpha(a): ...
def isdigit(a): ...
def islower(a): ...
def isspace(a): ...
def istitle(a): ...
def isupper(a): ...
def join(sep, seq): ...
def ljust(a, width, fillchar: str = ...): ...
def lower(a): ...
def lstrip(a, chars: Any | None = ...): ...
def partition(a, sep): ...
def replace(a, old, new, count: Any | None = ...): ...
def rfind(a, sub, start: int = ..., end: Any | None = ...): ...
def rindex(a, sub, start: int = ..., end: Any | None = ...): ...
def rjust(a, width, fillchar: str = ...): ...
def rpartition(a, sep): ...
def rsplit(a, sep: Any | None = ..., maxsplit: Any | None = ...): ...
def rstrip(a, chars: Any | None = ...): ...
def split(a, sep: Any | None = ..., maxsplit: Any | None = ...): ...
def splitlines(a, keepends: Any | None = ...): ...
def startswith(a, prefix, start: int = ..., end: Any | None = ...): ...
def strip(a, chars: Any | None = ...): ...
def swapcase(a): ...
def title(a): ...
def translate(a, table, deletechars: Any | None = ...): ...
def upper(a): ...
def zfill(a, width): ...
def isnumeric(a): ...
def isdecimal(a): ...

class chararray(ndarray):
    def __new__(subtype, shape, itemsize: int = ..., unicode: bool = ..., buffer: Any | None = ..., offset: int = ..., strides: Any | None = ..., order: str = ...): ...
    def __array_finalize__(self, obj) -> None: ...
    def __getitem__(self, obj): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __ge__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __lt__(self, other): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, i): ...
    def __rmul__(self, i): ...
    def __mod__(self, i): ...
    def __rmod__(self, other): ...
    def argsort(self, axis: int = ..., kind: Any | None = ..., order: Any | None = ...): ...
    def capitalize(self): ...
    def center(self, width, fillchar: str = ...): ...
    def count(self, sub, start: int = ..., end: Any | None = ...): ...
    def decode(self, encoding: Any | None = ..., errors: Any | None = ...): ...
    def encode(self, encoding: Any | None = ..., errors: Any | None = ...): ...
    def endswith(self, suffix, start: int = ..., end: Any | None = ...): ...
    def expandtabs(self, tabsize: int = ...): ...
    def find(self, sub, start: int = ..., end: Any | None = ...): ...
    def index(self, sub, start: int = ..., end: Any | None = ...): ...
    def isalnum(self): ...
    def isalpha(self): ...
    def isdigit(self): ...
    def islower(self): ...
    def isspace(self): ...
    def istitle(self): ...
    def isupper(self): ...
    def join(self, seq): ...
    def ljust(self, width, fillchar: str = ...): ...
    def lower(self): ...
    def lstrip(self, chars: Any | None = ...): ...
    def partition(self, sep): ...
    def replace(self, old, new, count: Any | None = ...): ...
    def rfind(self, sub, start: int = ..., end: Any | None = ...): ...
    def rindex(self, sub, start: int = ..., end: Any | None = ...): ...
    def rjust(self, width, fillchar: str = ...): ...
    def rpartition(self, sep): ...
    def rsplit(self, sep: Any | None = ..., maxsplit: Any | None = ...): ...
    def rstrip(self, chars: Any | None = ...): ...
    def split(self, sep: Any | None = ..., maxsplit: Any | None = ...): ...
    def splitlines(self, keepends: Any | None = ...): ...
    def startswith(self, prefix, start: int = ..., end: Any | None = ...): ...
    def strip(self, chars: Any | None = ...): ...
    def swapcase(self): ...
    def title(self): ...
    def translate(self, table, deletechars: Any | None = ...): ...
    def upper(self): ...
    def zfill(self, width): ...
    def isnumeric(self): ...
    def isdecimal(self): ...

def array(obj, itemsize: Any | None = ..., copy: bool = ..., unicode: Any | None = ..., order: Any | None = ...): ...
def asarray(obj, itemsize: Any | None = ..., unicode: Any | None = ..., order: Any | None = ...): ...
