from .numeric import dtype, ndarray
from typing import Any

dtypedescr = dtype

class memmap(ndarray):
    __array_priority__: Any
    offset: Any
    mode: Any
    filename: Any
    def __new__(subtype, filename, dtype=..., mode: str = ..., offset: int = ..., shape: Any | None = ..., order: str = ...): ...
    def __array_finalize__(self, obj) -> None: ...
    def flush(self) -> None: ...
    def __array_wrap__(self, arr, context: Any | None = ...): ...
    def __getitem__(self, index): ...
