from setup_common import *
from numpy.compat import npy_load_module as npy_load_module
from numpy.distutils import log as log
from typing import Any

NPY_RELAXED_STRIDES_CHECKING: Any
NPY_RELAXED_STRIDES_DEBUG: Any

class CallOnceOnly:
    def __init__(self) -> None: ...
    def check_types(self, *a, **kw): ...
    def check_ieee_macros(self, *a, **kw): ...
    def check_complex(self, *a, **kw): ...

def pythonlib_dir(): ...
def is_npy_no_signal(): ...
def is_npy_no_smp(): ...
def win32_checks(deflist) -> None: ...
def check_math_capabilities(config, ext, moredefs, mathlibs): ...
def check_complex(config, mathlibs): ...
def check_ieee_macros(config): ...
def check_types(config_cmd, ext, build_dir): ...
def check_mathlib(config_cmd): ...
def visibility_define(config): ...
def configuration(parent_package: str = ..., top_path: Any | None = ...): ...
