from pandas import DataFrame as DataFrame
from pandas._config import get_option as get_option
from pandas._typing import IndexLabel as IndexLabel
from pandas.core.base import PandasObject as PandasObject
from pandas.core.dtypes.common import is_integer as is_integer, is_list_like as is_list_like
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.util._decorators import Appender as Appender, Substitution as Substitution
from typing import Union, Any, Sequence

def hist_series(self, by: Any | None = ..., ax: Any | None = ..., grid: bool = ..., xlabelsize: Union[int, None] = ..., xrot: Union[float, None] = ..., ylabelsize: Union[int, None] = ..., yrot: Union[float, None] = ..., figsize: Union[tuple[int, int], None] = ..., bins: Union[int, Sequence[int]] = ..., backend: Union[str, None] = ..., legend: bool = ..., **kwargs): ...
def hist_frame(data: DataFrame, column: IndexLabel = ..., by: Any | None = ..., grid: bool = ..., xlabelsize: Union[int, None] = ..., xrot: Union[float, None] = ..., ylabelsize: Union[int, None] = ..., yrot: Union[float, None] = ..., ax: Any | None = ..., sharex: bool = ..., sharey: bool = ..., figsize: Union[tuple[int, int], None] = ..., layout: Union[tuple[int, int], None] = ..., bins: Union[int, Sequence[int]] = ..., backend: Union[str, None] = ..., legend: bool = ..., **kwargs): ...
def boxplot(data, column: Any | None = ..., by: Any | None = ..., ax: Any | None = ..., fontsize: Any | None = ..., rot: int = ..., grid: bool = ..., figsize: Any | None = ..., layout: Any | None = ..., return_type: Any | None = ..., **kwargs): ...
def boxplot_frame(self, column: Any | None = ..., by: Any | None = ..., ax: Any | None = ..., fontsize: Any | None = ..., rot: int = ..., grid: bool = ..., figsize: Any | None = ..., layout: Any | None = ..., return_type: Any | None = ..., backend: Any | None = ..., **kwargs): ...
def boxplot_frame_groupby(grouped, subplots: bool = ..., column: Any | None = ..., fontsize: Any | None = ..., rot: int = ..., grid: bool = ..., ax: Any | None = ..., figsize: Any | None = ..., layout: Any | None = ..., sharex: bool = ..., sharey: bool = ..., backend: Any | None = ..., **kwargs): ...

class PlotAccessor(PandasObject):
    def __init__(self, data) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def line(self, x: Any | None = ..., y: Any | None = ..., **kwargs): ...
    def bar(self, x: Any | None = ..., y: Any | None = ..., **kwargs): ...
    def barh(self, x: Any | None = ..., y: Any | None = ..., **kwargs): ...
    def box(self, by: Any | None = ..., **kwargs): ...
    def hist(self, by: Any | None = ..., bins: int = ..., **kwargs): ...
    def kde(self, bw_method: Any | None = ..., ind: Any | None = ..., **kwargs): ...
    density: Any
    def area(self, x: Any | None = ..., y: Any | None = ..., **kwargs): ...
    def pie(self, **kwargs): ...
    def scatter(self, x, y, s: Any | None = ..., c: Any | None = ..., **kwargs): ...
    def hexbin(self, x, y, C: Any | None = ..., reduce_C_function: Any | None = ..., gridsize: Any | None = ..., **kwargs): ...
