def combined_commuting_self_adjoint_hint(operator_a, operator_b): ...
def is_square(operator_a, operator_b): ...
def combined_commuting_positive_definite_hint(operator_a, operator_b): ...
def combined_non_singular_hint(operator_a, operator_b): ...
