from sklearn.neural_network._base import binary_log_loss as binary_log_loss, log_loss as log_loss

def test_binary_log_loss_1_prob_finite() -> None: ...
def test_log_loss_1_prob_finite(y_true, y_prob) -> None: ...
