from sklearn.datasets import load_digits as load_digits
from sklearn.neural_network import BernoulliRBM as BernoulliRBM
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_almost_equal as assert_almost_equal, assert_array_equal as assert_array_equal
from sklearn.utils.validation import assert_all_finite as assert_all_finite
from typing import Any

Xdigits: Any

def test_fit() -> None: ...
def test_partial_fit() -> None: ...
def test_transform() -> None: ...
def test_small_sparse() -> None: ...
def test_small_sparse_partial_fit() -> None: ...
def test_sample_hiddens() -> None: ...
def test_fit_gibbs(): ...
def test_fit_gibbs_sparse() -> None: ...
def test_gibbs_smoke() -> None: ...
def test_score_samples() -> None: ...
def test_rbm_verbose() -> None: ...
def test_sparse_and_verbose() -> None: ...
def test_transformer_dtypes_casting(dtype_in, dtype_out) -> None: ...
def test_convergence_dtype_consistency() -> None: ...
