from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape
from tensorflow.python.keras import backend as backend
from tensorflow.python.ops import array_ops as array_ops
from typing import Any

def convert_data_format(data_format, ndim): ...
def normalize_tuple(value, n, name): ...
def conv_output_length(input_length, filter_size, padding, stride, dilation: int = ...): ...
def conv_input_length(output_length, filter_size, padding, stride): ...
def deconv_output_length(input_length, filter_size, padding, output_padding: Any | None = ..., stride: int = ..., dilation: int = ...): ...
def normalize_data_format(value): ...
def normalize_padding(value): ...
def conv_kernel_mask(input_shape, kernel_shape, strides, padding): ...
def conv_kernel_idxs(input_shape, kernel_shape, strides, padding, filters_in, filters_out, data_format): ...
def conv_connected_inputs(input_shape, kernel_shape, output_position, strides, padding): ...
def conv_output_shape(input_shape, kernel_shape, strides, padding): ...
def squeeze_batch_dims(inp, op, inner_rank): ...
