from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any

def to_categorical(y, num_classes: Any | None = ..., dtype: str = ...): ...
def normalize(x, axis: int = ..., order: int = ...): ...
