from tensorflow.python import tf2 as tf2
from tensorflow.python.eager import context as context
from tensorflow.python.framework import composite_tensor as composite_tensor, dtypes as dtypes, tensor_conversion_registry as tensor_conversion_registry, tensor_shape as tensor_shape, type_spec as type_spec
from tensorflow.python.types import internal as internal
from tensorflow.python.util.compat import collections_abc as collections_abc
from tensorflow.python.util.lazy_loader import LazyLoader as LazyLoader
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, NamedTuple

math_ops: Any
ops: Any
tensor_spec: Any
tensor_util: Any

class IndexedSlices(internal.NativeObject, composite_tensor.CompositeTensor):
    def __init__(self, values, indices, dense_shape: Any | None = ...) -> None: ...
    @property
    def values(self): ...
    @property
    def indices(self): ...
    @property
    def dense_shape(self): ...
    @property
    def shape(self): ...
    @property
    def name(self): ...
    @property
    def device(self): ...
    @property
    def op(self): ...
    @property
    def dtype(self): ...
    @property
    def graph(self): ...
    def __neg__(self): ...
    def consumers(self): ...

class IndexedSlicesValue(NamedTuple):
    values: Any
    indices: Any
    dense_shape: Any

class IndexedSlicesSpec(type_spec.TypeSpec):
    value_type: Any
    def __init__(self, shape: Any | None = ..., dtype=..., indices_dtype=..., dense_shape_dtype: Any | None = ..., indices_shape: Any | None = ...) -> None: ...

def convert_to_tensor_or_indexed_slices(value, dtype: Any | None = ..., name: Any | None = ...): ...
def internal_convert_to_tensor_or_indexed_slices(value, dtype: Any | None = ..., name: Any | None = ..., as_ref: bool = ...): ...
def internal_convert_n_to_tensor_or_indexed_slices(values, dtype: Any | None = ..., name: Any | None = ..., as_ref: bool = ...): ...
def convert_n_to_tensor_or_indexed_slices(values, dtype: Any | None = ..., name: Any | None = ...): ...
