from tensorflow.python.eager import context as context, execute as execute
from typing import Any

def add_op_callback(callback_fn) -> None: ...
def should_invoke_op_callbacks(): ...
def remove_op_callback(op_callback) -> None: ...
def clear_op_callbacks() -> None: ...
def invoke_op_callbacks(op_type, inputs, attrs, outputs, op_name: Any | None = ..., graph: Any | None = ...): ...
