from tensorflow.python.profiler.traceme import traceme_wrapper as traceme_wrapper
from typing import Any

class _PythonMemoryChecker:
    def __init__(self) -> None: ...
    def record_snapshot(self): ...
    def report(self) -> None: ...
    def assert_no_leak_if_all_possibly_except_one(self) -> None: ...
    def assert_no_new_objects(self, threshold: Any | None = ...) -> None: ...
