from tensorflow.python.util import compat as compat
from typing import Any

class Registry:
    def __init__(self, name) -> None: ...
    def register(self, candidate, name: Any | None = ...) -> None: ...
    def list(self): ...
    def lookup(self, name): ...
