from _typeshed import Incomplete

from ...loadsave import load as load
from ...loadsave import save as save
from ...nifti1 import xform_codes as xform_codes
from ...testing import clear_and_catch_warnings as clear_and_catch_warnings
from ...testing import suppress_warnings as suppress_warnings
from ...tmpdirs import InTemporaryDirectory as InTemporaryDirectory
from ..parse_gifti_fast import GiftiImageParser as GiftiImageParser
from ..parse_gifti_fast import GiftiParseError as GiftiParseError
from ..util import gifti_endian_codes as gifti_endian_codes

IO_DATA_PATH: Incomplete
DATA_FILE1: Incomplete
DATA_FILE2: Incomplete
DATA_FILE3: Incomplete
DATA_FILE4: Incomplete
DATA_FILE5: Incomplete
DATA_FILE6: Incomplete
DATA_FILE7: Incomplete
DATA_FILE8: Incomplete
datafiles: Incomplete
numDA: Incomplete
DATA_FILE1_darr1: Incomplete
DATA_FILE1_darr2: Incomplete
DATA_FILE2_darr1: Incomplete
DATA_FILE3_darr1: Incomplete
DATA_FILE4_darr1: Incomplete
DATA_FILE5_darr1: Incomplete
DATA_FILE5_darr2: Incomplete
DATA_FILE6_darr1: Incomplete
DATA_FILE7_darr1: Incomplete
DATA_FILE7_darr2: Incomplete
DATA_FILE8_darr1: Incomplete
DATA_FILE8_darr2: Incomplete

def assert_default_types(loaded) -> None: ...
def test_default_types() -> None: ...
def test_read_ordering() -> None: ...
def test_load_metadata() -> None: ...
def test_load_dataarray1() -> None: ...
def test_load_dataarray2() -> None: ...
def test_load_dataarray3() -> None: ...
def test_load_dataarray4() -> None: ...
def test_dataarray5() -> None: ...
def test_base64_written() -> None: ...
def test_readwritedata() -> None: ...
def test_modify_darray() -> None: ...
def test_write_newmetadata() -> None: ...
def test_load_getbyintent() -> None: ...
def test_load_labeltable() -> None: ...
def test_parse_dataarrays() -> None: ...
def test_parse_with_buffersize() -> None: ...
def test_dataarray7() -> None: ...
def test_parse_with_memmmap() -> None: ...
def test_parse_with_memmap_fallback() -> None: ...
def test_external_file_failure_cases() -> None: ...
def test_load_compressed() -> None: ...
def test_load_flat_ascii_data() -> None: ...
