import numpy as np
from datetime import datetime, tzinfo
from pandas._typing import npt as npt
from typing import Union, Callable

dateutil_gettz: Callable[[str], tzinfo]

def tz_standardize(tz: tzinfo) -> tzinfo: ...
def tz_compare(start: Union[tzinfo, None], end: Union[tzinfo, None]) -> bool: ...
def infer_tzinfo(start: Union[datetime, None], end: Union[datetime, None]) -> Union[tzinfo, None]: ...
def get_dst_info(tz: tzinfo) -> tuple[npt.NDArray[np.int64], npt.NDArray[np.int64], str]: ...
def maybe_get_tz(tz: Union[str, int, np.int64, tzinfo, None]) -> Union[tzinfo, None]: ...
def get_timezone(tz: tzinfo) -> Union[tzinfo, str]: ...
def is_utc(tz: Union[tzinfo, None]) -> bool: ...
