from sklearn.cluster import AffinityPropagation as AffinityPropagation, affinity_propagation as affinity_propagation
from sklearn.datasets import make_blobs as make_blobs
from sklearn.exceptions import ConvergenceWarning as ConvergenceWarning
from sklearn.metrics import euclidean_distances as euclidean_distances
from sklearn.utils._testing import assert_array_equal as assert_array_equal
from typing import Any

n_clusters: int
centers: Any
X: Any

def test_affinity_propagation() -> None: ...
def test_affinity_propagation_affinity_shape() -> None: ...
def test_affinity_propagation_params_validation(input, params, err_type, err_msg) -> None: ...
def test_affinity_propagation_predict() -> None: ...
def test_affinity_propagation_predict_error() -> None: ...
def test_affinity_propagation_fit_non_convergence() -> None: ...
def test_affinity_propagation_equal_mutual_similarities() -> None: ...
def test_affinity_propagation_predict_non_convergence() -> None: ...
def test_affinity_propagation_non_convergence_regressiontest() -> None: ...
def test_equal_similarities_and_preferences() -> None: ...
def test_affinity_propagation_random_state() -> None: ...
def test_affinity_propagation_convergence_warning_dense_sparse(centers) -> None: ...
def test_affinity_propagation_float32() -> None: ...
def test_sparse_input_for_predict() -> None: ...
def test_sparse_input_for_fit_predict() -> None: ...
def test_affinity_propagation_pairwise_is_deprecated() -> None: ...
