from sklearn.base import BaseEstimator as BaseEstimator, BiclusterMixin as BiclusterMixin
from sklearn.cluster import SpectralBiclustering as SpectralBiclustering, SpectralCoclustering as SpectralCoclustering
from sklearn.datasets import make_biclusters as make_biclusters, make_checkerboard as make_checkerboard
from sklearn.metrics import consensus_score as consensus_score, v_measure_score as v_measure_score
from sklearn.model_selection import ParameterGrid as ParameterGrid
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal

class MockBiclustering(BiclusterMixin, BaseEstimator):
    def __init__(self) -> None: ...
    def get_indices(self, i): ...

def test_get_submatrix() -> None: ...
def test_spectral_coclustering() -> None: ...
def test_spectral_biclustering() -> None: ...
def test_scale_normalize() -> None: ...
def test_bistochastic_normalize() -> None: ...
def test_log_normalize() -> None: ...
def test_fit_best_piecewise() -> None: ...
def test_project_and_cluster() -> None: ...
def test_perfect_checkerboard() -> None: ...
def test_errors(args) -> None: ...
def test_wrong_shape() -> None: ...
def test_n_features_in_(est) -> None: ...
