from typing import Any

class MatplotlibDeprecationWarning(DeprecationWarning): ...
mplDeprecation = MatplotlibDeprecationWarning

def warn_deprecated(since, *, message: str = ..., name: str = ..., alternative: str = ..., pending: bool = ..., obj_type: str = ..., addendum: str = ..., removal: str = ...) -> None: ...
def deprecated(since, *, message: str = ..., name: str = ..., alternative: str = ..., pending: bool = ..., obj_type: Any | None = ..., addendum: str = ..., removal: str = ...): ...

class deprecate_privatize_attribute:
    deprecator: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __set_name__(self, owner, name): ...

DECORATORS: Any

def rename_parameter(since, old, new, func: Any | None = ...): ...

class _deprecated_parameter_class: ...

def delete_parameter(since, name, func: Any | None = ..., **kwargs): ...
def make_keyword_only(since, name, func: Any | None = ...): ...
def deprecate_method_override(method, obj, *, allow_empty: bool = ..., **kwargs): ...
def suppress_matplotlib_deprecation_warning() -> None: ...
