from sklearn.metrics.cluster import adjusted_mutual_info_score as adjusted_mutual_info_score, adjusted_rand_score as adjusted_rand_score, calinski_harabasz_score as calinski_harabasz_score, completeness_score as completeness_score, davies_bouldin_score as davies_bouldin_score, fowlkes_mallows_score as fowlkes_mallows_score, homogeneity_score as homogeneity_score, mutual_info_score as mutual_info_score, normalized_mutual_info_score as normalized_mutual_info_score, rand_score as rand_score, silhouette_score as silhouette_score, v_measure_score as v_measure_score
from sklearn.utils._testing import assert_allclose as assert_allclose
from typing import Any

SUPERVISED_METRICS: Any
UNSUPERVISED_METRICS: Any
SYMMETRIC_METRICS: Any
NON_SYMMETRIC_METRICS: Any
NORMALIZED_METRICS: Any
rng: Any
y1: Any
y2: Any

def test_symmetric_non_symmetric_union() -> None: ...
def test_symmetry(metric_name, y1, y2) -> None: ...
def test_non_symmetry(metric_name, y1, y2) -> None: ...
def test_normalized_output(metric_name) -> None: ...
def test_permute_labels(metric_name) -> None: ...
def test_format_invariance(metric_name) -> None: ...
def test_single_sample(metric) -> None: ...
def test_inf_nan_input(metric_name, metric_func) -> None: ...
