from sklearn import datasets as datasets
from sklearn.metrics import pairwise_distances as pairwise_distances
from sklearn.metrics.cluster import calinski_harabasz_score as calinski_harabasz_score, davies_bouldin_score as davies_bouldin_score, silhouette_samples as silhouette_samples, silhouette_score as silhouette_score
from sklearn.utils._testing import assert_array_equal as assert_array_equal

def test_silhouette() -> None: ...
def test_cluster_size_1() -> None: ...
def test_silhouette_paper_example() -> None: ...
def test_correct_labelsize() -> None: ...
def test_non_encoded_labels() -> None: ...
def test_non_numpy_labels() -> None: ...
def test_silhouette_nonzero_diag(dtype) -> None: ...
def assert_raises_on_only_one_label(func) -> None: ...
def assert_raises_on_all_points_same_cluster(func) -> None: ...
def test_calinski_harabasz_score() -> None: ...
def test_davies_bouldin_score() -> None: ...
