from typing import Any

def kernel_rbf(x, y, scale: int = ..., **kwds): ...
def kernel_euclid(x, y, p: int = ..., **kwds): ...

class GaussProcess:
    x: Any
    kernel: Any
    scale: Any
    ridgecoeff: Any
    distxsample: Any
    Kinv: Any
    y: Any
    yest: Any
    def __init__(self, x, y: Any | None = ..., kernel=..., scale: float = ..., ridgecoeff: float = ..., **kwds) -> None: ...
    parest: Any
    def fit(self, y): ...
    xpredict: Any
    ypredict: Any
    def predict(self, x): ...
    def plot(self, y, plt=...) -> None: ...

def example1() -> None: ...
def example2(m: int = ..., scale: float = ..., stride: int = ...) -> None: ...
