def norm_lls(y, params): ...
def norm_lls_grad(y, params): ...
def mean_grad(x, beta): ...
def normgrad(y, x, params): ...
def tstd_lls(y, params, df): ...
def norm_dlldy(y): ...
def tstd_pdf(x, df): ...
def ts_lls(y, params, df): ...
def ts_dlldy(y, df): ...
def tstd_dlldy(y, df): ...
def locscale_grad(y, loc, scale, dlldy, *args): ...
