def has_verdana(): ...
def remove_pandas_unit_conversion() -> None: ...
def close_figs() -> None: ...
def random_seed() -> None: ...
def rng(): ...
def wide_df(rng): ...
def wide_array(wide_df): ...
def flat_series(rng): ...
def flat_array(flat_series): ...
def flat_list(flat_series): ...
def flat_data(rng, request): ...
def wide_list_of_series(rng): ...
def wide_list_of_arrays(wide_list_of_series): ...
def wide_list_of_lists(wide_list_of_series): ...
def wide_dict_of_series(wide_list_of_series): ...
def wide_dict_of_arrays(wide_list_of_series): ...
def wide_dict_of_lists(wide_list_of_series): ...
def long_df(rng): ...
def long_dict(long_df): ...
def repeated_df(rng): ...
def missing_df(rng, long_df): ...
def object_df(rng, long_df): ...
def null_series(flat_series): ...
