from ._core import VectorPlotter
from typing import Any

class _DistributionPlotter(VectorPlotter):
    semantics: Any
    wide_structure: Any
    flat_structure: Any
    def __init__(self, data: Any | None = ..., variables=...) -> None: ...
    @property
    def univariate(self): ...
    @property
    def data_variable(self): ...
    @property
    def has_xy_data(self): ...
    def plot_univariate_histogram(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws) -> None: ...
    def plot_bivariate_histogram(self, common_bins, common_norm, thresh, pthresh, pmax, color, legend, cbar, cbar_ax, cbar_kws, estimate_kws, **plot_kws) -> None: ...
    def plot_univariate_density(self, multiple, common_norm, common_grid, warn_singular, fill, legend, estimate_kws, **plot_kws) -> None: ...
    def plot_bivariate_density(self, common_norm, fill, levels, thresh, color, legend, cbar, warn_singular, cbar_ax, cbar_kws, estimate_kws, **contour_kws) -> None: ...
    def plot_univariate_ecdf(self, estimate_kws, legend, **plot_kws) -> None: ...
    def plot_rug(self, height, expand_margins, legend, **kws) -> None: ...

class _DistributionFacetPlotter(_DistributionPlotter):
    semantics: Any

def histplot(data: Any | None = ..., *, x: Any | None = ..., y: Any | None = ..., hue: Any | None = ..., weights: Any | None = ..., stat: str = ..., bins: str = ..., binwidth: Any | None = ..., binrange: Any | None = ..., discrete: Any | None = ..., cumulative: bool = ..., common_bins: bool = ..., common_norm: bool = ..., multiple: str = ..., element: str = ..., fill: bool = ..., shrink: int = ..., kde: bool = ..., kde_kws: Any | None = ..., line_kws: Any | None = ..., thresh: int = ..., pthresh: Any | None = ..., pmax: Any | None = ..., cbar: bool = ..., cbar_ax: Any | None = ..., cbar_kws: Any | None = ..., palette: Any | None = ..., hue_order: Any | None = ..., hue_norm: Any | None = ..., color: Any | None = ..., log_scale: Any | None = ..., legend: bool = ..., ax: Any | None = ..., **kwargs): ...
def kdeplot(x: Any | None = ..., *, y: Any | None = ..., shade: Any | None = ..., vertical: bool = ..., kernel: Any | None = ..., bw: Any | None = ..., gridsize: int = ..., cut: int = ..., clip: Any | None = ..., legend: bool = ..., cumulative: bool = ..., shade_lowest: Any | None = ..., cbar: bool = ..., cbar_ax: Any | None = ..., cbar_kws: Any | None = ..., ax: Any | None = ..., weights: Any | None = ..., hue: Any | None = ..., palette: Any | None = ..., hue_order: Any | None = ..., hue_norm: Any | None = ..., multiple: str = ..., common_norm: bool = ..., common_grid: bool = ..., levels: int = ..., thresh: float = ..., bw_method: str = ..., bw_adjust: int = ..., log_scale: Any | None = ..., color: Any | None = ..., fill: Any | None = ..., data: Any | None = ..., data2: Any | None = ..., warn_singular: bool = ..., **kwargs): ...
def ecdfplot(data: Any | None = ..., *, x: Any | None = ..., y: Any | None = ..., hue: Any | None = ..., weights: Any | None = ..., stat: str = ..., complementary: bool = ..., palette: Any | None = ..., hue_order: Any | None = ..., hue_norm: Any | None = ..., log_scale: Any | None = ..., legend: bool = ..., ax: Any | None = ..., **kwargs): ...
def rugplot(x: Any | None = ..., *, height: float = ..., axis: Any | None = ..., ax: Any | None = ..., data: Any | None = ..., y: Any | None = ..., hue: Any | None = ..., palette: Any | None = ..., hue_order: Any | None = ..., hue_norm: Any | None = ..., expand_margins: bool = ..., legend: bool = ..., a: Any | None = ..., **kwargs): ...
def displot(data: Any | None = ..., *, x: Any | None = ..., y: Any | None = ..., hue: Any | None = ..., row: Any | None = ..., col: Any | None = ..., weights: Any | None = ..., kind: str = ..., rug: bool = ..., rug_kws: Any | None = ..., log_scale: Any | None = ..., legend: bool = ..., palette: Any | None = ..., hue_order: Any | None = ..., hue_norm: Any | None = ..., color: Any | None = ..., col_wrap: Any | None = ..., row_order: Any | None = ..., col_order: Any | None = ..., height: int = ..., aspect: int = ..., facet_kws: Any | None = ..., **kwargs): ...
def distplot(a: Any | None = ..., bins: Any | None = ..., hist: bool = ..., kde: bool = ..., rug: bool = ..., fit: Any | None = ..., hist_kws: Any | None = ..., kde_kws: Any | None = ..., rug_kws: Any | None = ..., fit_kws: Any | None = ..., color: Any | None = ..., vertical: bool = ..., norm_hist: bool = ..., axlabel: Any | None = ..., label: Any | None = ..., ax: Any | None = ..., x: Any | None = ...): ...
