from typing import Any
from pandas.core.frame import DataFrame as DataFrame

def desaturate(color, prop): ...
def saturate(color): ...
def set_hls_values(
    color, h: Any | None = ..., l: Any | None = ..., s: Any | None = ...
): ...
def despine(
    fig: Any | None = ...,
    ax: Any | None = ...,
    top: bool = ...,
    right: bool = ...,
    left: bool = ...,
    bottom: bool = ...,
    offset: Any | None = ...,
    trim: bool = ...,
) -> None: ...
def move_legend(obj, loc, **kwargs) -> None: ...
def get_dataset_names(): ...
def get_data_home(data_home: Any | None = ...): ...
def load_dataset(
    name, cache: bool = ..., data_home: Any | None = ..., **kws
) -> DataFrame: ...
