from IPython.html.widgets import FloatSliderWidget, IntSliderWidget

FloatSlider = FloatSliderWidget
IntSlider = IntSliderWidget

def choose_colorbrewer_palette(data_type, as_cmap: bool = ...): ...
def choose_dark_palette(input: str = ..., as_cmap: bool = ...): ...
def choose_light_palette(input: str = ..., as_cmap: bool = ...): ...
def choose_diverging_palette(as_cmap: bool = ...): ...
def choose_cubehelix_palette(as_cmap: bool = ...): ...
