from . import cbook as cbook, rcParams as rcParams
from ._enums import CapStyle as CapStyle, JoinStyle as JoinStyle
from .path import Path as Path
from .transforms import Affine2D as Affine2D, IdentityTransform as IdentityTransform
from typing import Any

TICKLEFT: Any
TICKRIGHT: Any
TICKUP: Any
TICKDOWN: Any
CARETLEFT: Any
CARETRIGHT: Any
CARETUP: Any
CARETDOWN: Any
CARETLEFTBASE: Any
CARETRIGHTBASE: Any
CARETUPBASE: Any
CARETDOWNBASE: Any

class MarkerStyle:
    markers: Any
    filled_markers: Any
    fillstyles: Any
    def __init__(self, marker: Any | None = ..., fillstyle: Any | None = ...) -> None: ...
    def __bool__(self): ...
    def is_filled(self): ...
    def get_fillstyle(self): ...
    def set_fillstyle(self, fillstyle): ...
    def get_joinstyle(self): ...
    def get_capstyle(self): ...
    def get_marker(self): ...
    def set_marker(self, marker): ...
    def get_path(self): ...
    def get_transform(self): ...
    def get_alt_path(self): ...
    def get_alt_transform(self): ...
    def get_snap_threshold(self): ...
