from matplotlib import cbook as cbook, dviread as dviread, rcParams as rcParams
from typing import Any

class TexManager:
    texcache: Any
    grey_arrayd: Any
    font_family: Any
    font_families: Any
    font_info: Any
    def __new__(cls): ...
    def get_font_config(self): ...
    def get_basefile(self, tex, fontsize, dpi: Any | None = ...): ...
    def get_font_preamble(self): ...
    def get_custom_preamble(self): ...
    def make_tex(self, tex, fontsize): ...
    def make_dvi(self, tex, fontsize): ...
    def make_png(self, tex, fontsize, dpi): ...
    def get_grey(self, tex, fontsize: Any | None = ..., dpi: Any | None = ...): ...
    def get_rgba(self, tex, fontsize: Any | None = ..., dpi: Any | None = ..., rgb=...): ...
    def get_text_width_height_descent(self, tex, fontsize, renderer: Any | None = ...): ...
