from matplotlib.transforms import Affine2D as Affine2D, Bbox as Bbox, TransformedBbox as TransformedBbox
from typing import Any

def adjust_bbox(fig, bbox_inches, fixed_dpi: Any | None = ...): ...
def process_figure_for_rasterizing(fig, bbox_inches_restore, fixed_dpi: Any | None = ...): ...
