from keras.engine.base_layer import Layer as Layer
from typing import Any

class Masking(Layer):
    supports_masking: bool
    mask_value: Any
    def __init__(self, mask_value: float = ..., **kwargs) -> None: ...
    def compute_mask(self, inputs, mask: Any | None = ...): ...
    def call(self, inputs): ...
    def compute_output_shape(self, input_shape): ...
    def get_config(self): ...
