from sklearn.feature_selection import mutual_info_classif as mutual_info_classif, mutual_info_regression as mutual_info_regression
from sklearn.utils import check_random_state as check_random_state
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_equal as assert_array_equal

def test_compute_mi_dd() -> None: ...
def test_compute_mi_cc() -> None: ...
def test_compute_mi_cd() -> None: ...
def test_compute_mi_cd_unique_label() -> None: ...
def test_mutual_info_classif_discrete() -> None: ...
def test_mutual_info_regression() -> None: ...
def test_mutual_info_classif_mixed() -> None: ...
def test_mutual_info_options() -> None: ...
