from sklearn.feature_selection import SelectKBest as SelectKBest, chi2 as chi2
from sklearn.utils._testing import assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal
from typing import Any

X: Any
y: Any

def mkchi2(k): ...
def test_chi2() -> None: ...
def test_chi2_coo() -> None: ...
def test_chi2_negative() -> None: ...
def test_chi2_unused_feature() -> None: ...
def test_chisquare() -> None: ...
