from sklearn import datasets as datasets
from sklearn.model_selection import ShuffleSplit as ShuffleSplit
from sklearn.svm import SVC as SVC
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal
from sklearn.utils.fixes import parse_version as parse_version
from sklearn.utils.multiclass import check_classification_targets as check_classification_targets, class_distribution as class_distribution, is_multilabel as is_multilabel, type_of_target as type_of_target, unique_labels as unique_labels
from typing import Any

EXAMPLES: Any
NON_ARRAY_LIKE_EXAMPLES: Any
MULTILABEL_SEQUENCES: Any

def test_unique_labels() -> None: ...
def test_unique_labels_non_specific() -> None: ...
def test_unique_labels_mixed_types() -> None: ...
def test_is_multilabel() -> None: ...
def test_check_classification_targets() -> None: ...
def test_type_of_target() -> None: ...
def test_type_of_target_pandas_sparse() -> None: ...
def test_class_distribution() -> None: ...
def test_safe_split_with_precomputed_kernel() -> None: ...
def test_ovr_decision_function() -> None: ...
