def test_weighted_percentile() -> None: ...
def test_weighted_percentile_equal() -> None: ...
def test_weighted_percentile_zero_weight() -> None: ...
def test_weighted_percentile_zero_weight_zero_percentile() -> None: ...
def test_weighted_median_equal_weights() -> None: ...
def test_weighted_median_integer_weights() -> None: ...
def test_weighted_percentile_2d() -> None: ...
