from sklearn.metrics.pairwise import pairwise_distances as pairwise_distances
from sklearn.neighbors import kneighbors_graph as kneighbors_graph

def test_fix_connected_components() -> None: ...
def test_fix_connected_components_precomputed() -> None: ...
def test_fix_connected_components_wrong_mode() -> None: ...
def test_fix_connected_components_connectivity_mode() -> None: ...
def test_fix_connected_components_distance_mode() -> None: ...
