from sklearn.utils.graph import graph_shortest_path as graph_shortest_path, single_source_shortest_path_length as single_source_shortest_path_length

def test_graph_shortest_path_deprecation() -> None: ...
def floyd_warshall_slow(graph, directed: bool = ...): ...
def generate_graph(N: int = ...): ...
def test_floyd_warshall() -> None: ...
def test_dijkstra() -> None: ...
def test_shortest_path() -> None: ...
def test_dijkstra_bug_fix() -> None: ...
