from sklearn import config_context as config_context
from sklearn.utils import check_random_state as check_random_state, column_or_1d as column_or_1d, deprecated as deprecated, gen_batches as gen_batches, gen_even_slices as gen_even_slices, get_chunk_n_rows as get_chunk_n_rows, is_scalar_nan as is_scalar_nan, resample as resample, safe_mask as safe_mask, shuffle as shuffle
from sklearn.utils._mocking import MockDataFrame as MockDataFrame
from sklearn.utils._testing import SkipTest as SkipTest, assert_allclose_dense_sparse as assert_allclose_dense_sparse, assert_array_equal as assert_array_equal, assert_no_warnings as assert_no_warnings
from sklearn.utils.fixes import parse_version as parse_version
from typing import Any

X_toy: Any

def test_make_rng() -> None: ...
def test_gen_batches() -> None: ...
def test_deprecated(): ...
def test_resample() -> None: ...
def test_resample_stratified() -> None: ...
def test_resample_stratified_replace() -> None: ...
def test_resample_stratify_2dy() -> None: ...
def test_resample_stratify_sparse_error() -> None: ...
def test_safe_mask() -> None: ...
def test_column_or_1d() -> None: ...
def test_determine_key_type(key, dtype) -> None: ...
def test_determine_key_type_error() -> None: ...
def test_determine_key_type_slice_error() -> None: ...
def test_safe_indexing_2d_container_axis_0(array_type, indices_type) -> None: ...
def test_safe_indexing_1d_container(array_type, indices_type) -> None: ...
def test_safe_indexing_2d_container_axis_1(array_type, indices_type, indices) -> None: ...
def test_safe_indexing_2d_read_only_axis_1(array_read_only, indices_read_only, array_type, indices_type, axis, expected_array) -> None: ...
def test_safe_indexing_1d_container_mask(array_type, indices_type) -> None: ...
def test_safe_indexing_2d_mask(array_type, indices_type, axis, expected_subset) -> None: ...
def test_safe_indexing_2d_scalar_axis_0(array_type, expected_output_type) -> None: ...
def test_safe_indexing_1d_scalar(array_type) -> None: ...
def test_safe_indexing_2d_scalar_axis_1(array_type, expected_output_type, indices) -> None: ...
def test_safe_indexing_None_axis_0(array_type) -> None: ...
def test_safe_indexing_pandas_no_matching_cols_error() -> None: ...
def test_safe_indexing_error_axis(axis) -> None: ...
def test_safe_indexing_1d_array_error(X_constructor) -> None: ...
def test_safe_indexing_container_axis_0_unsupported_type() -> None: ...
def test_safe_indexing_pandas_no_settingwithcopy_warning() -> None: ...
def test_get_column_indices_error(key, err_msg) -> None: ...
def test_get_column_indices_pandas_nonunique_columns_error(key) -> None: ...
def test_shuffle_on_ndim_equals_three(): ...
def test_shuffle_dont_convert_to_array() -> None: ...
def test_gen_even_slices() -> None: ...
def test_get_chunk_n_rows(row_bytes, max_n_rows, working_memory, expected, warn_msg) -> None: ...
def test_message_with_time(source, message, is_long, time, time_str) -> None: ...
def test_print_elapsed_time(message, expected, capsys, monkeypatch): ...
def test_is_scalar_nan(value, result) -> None: ...
def test_approximate_mode() -> None: ...
def dummy_func() -> None: ...
def test_deprecation_joblib_api(tmpdir) -> None: ...
def test_to_object_array(sequence) -> None: ...
