from sklearn.utils.deprecation import deprecated as deprecated

class MockClass1: ...

class MockClass2:
    def method(self) -> None: ...
    @property
    def n_features_(self): ...

class MockClass3:
    def __init__(self) -> None: ...

class MockClass4: ...

def mock_function(): ...
def test_deprecated() -> None: ...
def test_is_deprecated() -> None: ...
def test_pickle() -> None: ...
def test_deprecated_property_docstring_exists() -> None: ...
