from sklearn.datasets import make_classification as make_classification
from sklearn.utils._testing import assert_allclose as assert_allclose
from sklearn.utils.sparsefuncs import count_nonzero as count_nonzero, csc_median_axis_0 as csc_median_axis_0, incr_mean_variance_axis as incr_mean_variance_axis, inplace_column_scale as inplace_column_scale, inplace_row_scale as inplace_row_scale, inplace_swap_column as inplace_swap_column, inplace_swap_row as inplace_swap_row, mean_variance_axis as mean_variance_axis, min_max_axis as min_max_axis
from sklearn.utils.sparsefuncs_fast import assign_rows_csr as assign_rows_csr, csr_row_norms as csr_row_norms, inplace_csr_row_normalize_l1 as inplace_csr_row_normalize_l1, inplace_csr_row_normalize_l2 as inplace_csr_row_normalize_l2

def test_mean_variance_axis0() -> None: ...
def test_mean_variance_axis0_precision(dtype, sparse_constructor) -> None: ...
def test_mean_variance_axis1() -> None: ...
def test_incr_mean_variance_axis_weighted_axis1(Xw, X, weights, sparse_constructor, dtype) -> None: ...
def test_incr_mean_variance_axis_weighted_axis0(Xw, X, weights, sparse_constructor, dtype) -> None: ...
def test_incr_mean_variance_axis() -> None: ...
def test_incr_mean_variance_axis_dim_mismatch(sparse_constructor) -> None: ...
def test_incr_mean_variance_axis_equivalence_mean_variance(X1, X2) -> None: ...
def test_incr_mean_variance_no_new_n() -> None: ...
def test_incr_mean_variance_n_float() -> None: ...
def test_incr_mean_variance_axis_ignore_nan(axis, sparse_constructor) -> None: ...
def test_mean_variance_illegal_axis() -> None: ...
def test_densify_rows() -> None: ...
def test_inplace_column_scale() -> None: ...
def test_inplace_row_scale() -> None: ...
def test_inplace_swap_row() -> None: ...
def test_inplace_swap_column() -> None: ...
def test_min_max(dtype, axis, sparse_format, missing_values, min_func, max_func, ignore_nan, large_indices) -> None: ...
def test_min_max_axis_errors() -> None: ...
def test_count_nonzero() -> None: ...
def test_csc_row_median() -> None: ...
def test_inplace_normalize() -> None: ...
def test_csr_row_norms(dtype) -> None: ...
