from sklearn.datasets import make_blobs as make_blobs
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.utils._testing import assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal
from sklearn.utils.class_weight import compute_class_weight as compute_class_weight, compute_sample_weight as compute_sample_weight

def test_compute_class_weight() -> None: ...
def test_compute_class_weight_not_present() -> None: ...
def test_compute_class_weight_dict() -> None: ...
def test_compute_class_weight_invariance() -> None: ...
def test_compute_class_weight_balanced_negative() -> None: ...
def test_compute_class_weight_balanced_unordered() -> None: ...
def test_compute_class_weight_default() -> None: ...
def test_compute_sample_weight() -> None: ...
def test_compute_sample_weight_with_subsample() -> None: ...
def test_compute_sample_weight_errors() -> None: ...
def test_compute_sample_weight_more_than_32() -> None: ...
