from sklearn.utils._cython_blas import ColMajor as ColMajor, NoTrans as NoTrans, RowMajor as RowMajor, Trans as Trans
from sklearn.utils._testing import assert_allclose as assert_allclose
from typing import Any

RTOL: Any
ORDER: Any

def test_dot(dtype) -> None: ...
def test_asum(dtype) -> None: ...
def test_axpy(dtype) -> None: ...
def test_nrm2(dtype) -> None: ...
def test_copy(dtype) -> None: ...
def test_scal(dtype) -> None: ...
def test_rotg(dtype): ...
def test_rot(dtype) -> None: ...
def test_gemv(dtype, opA, transA, order) -> None: ...
def test_ger(dtype, order) -> None: ...
def test_gemm(dtype, opA, transA, opB, transB, order) -> None: ...
