from sklearn.datasets import make_low_rank_matrix as make_low_rank_matrix, make_sparse_spd_matrix as make_sparse_spd_matrix
from sklearn.utils import gen_batches as gen_batches
from sklearn.utils._testing import assert_allclose as assert_allclose, assert_allclose_dense_sparse as assert_allclose_dense_sparse, assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal, skip_if_32bit as skip_if_32bit
from sklearn.utils.extmath import cartesian as cartesian, density as density, log_logistic as log_logistic, randomized_svd as randomized_svd, row_norms as row_norms, safe_sparse_dot as safe_sparse_dot, softmax as softmax, stable_cumsum as stable_cumsum, svd_flip as svd_flip, weighted_mode as weighted_mode

def test_density() -> None: ...
def test_uniform_weights() -> None: ...
def test_random_weights() -> None: ...
def check_randomized_svd_low_rank(dtype) -> None: ...
def test_randomized_svd_low_rank_all_dtypes(dtype) -> None: ...
def test_randomized_eigsh(dtype) -> None: ...
def test_randomized_eigsh_compared_to_others(k) -> None: ...
def test_randomized_eigsh_reconst_low_rank(n, rank) -> None: ...
def test_row_norms(dtype) -> None: ...
def test_randomized_svd_low_rank_with_noise() -> None: ...
def test_randomized_svd_infinite_rank() -> None: ...
def test_randomized_svd_transpose_consistency() -> None: ...
def test_randomized_svd_power_iteration_normalizer() -> None: ...
def test_randomized_svd_sparse_warnings() -> None: ...
def test_svd_flip() -> None: ...
def test_randomized_svd_sign_flip() -> None: ...
def test_randomized_svd_sign_flip_with_transpose(): ...
def test_cartesian() -> None: ...
def test_logistic_sigmoid(): ...
def rng(): ...
def test_incremental_weighted_mean_and_variance_simple(rng, dtype) -> None: ...
def test_incremental_weighted_mean_and_variance(mean, var, weight_loc, weight_scale, rng) -> None: ...
def test_incremental_weighted_mean_and_variance_ignore_nan(dtype) -> None: ...
def test_incremental_variance_update_formulas() -> None: ...
def test_incremental_mean_and_variance_ignore_nan() -> None: ...
def test_incremental_variance_numerical_stability(): ...
def test_incremental_variance_ddof() -> None: ...
def test_vector_sign_flip() -> None: ...
def test_softmax() -> None: ...
def test_stable_cumsum() -> None: ...
def test_safe_sparse_dot_2d(A_array_constr, B_array_constr) -> None: ...
def test_safe_sparse_dot_nd() -> None: ...
def test_safe_sparse_dot_2d_1d(A_array_constr) -> None: ...
def test_safe_sparse_dot_dense_output(dense_output) -> None: ...
