from sklearn.utils.murmurhash import murmurhash3_32 as murmurhash3_32

def test_mmhash3_int() -> None: ...
def test_mmhash3_int_array() -> None: ...
def test_mmhash3_bytes() -> None: ...
def test_mmhash3_unicode() -> None: ...
def test_no_collision_on_byte_range() -> None: ...
def test_uniform_distribution() -> None: ...
