from sklearn.utils.random import sample_without_replacement as sample_without_replacement

def test_invalid_sample_without_replacement_algorithm() -> None: ...
def test_sample_without_replacement_algorithms(): ...
def check_edge_case_of_sample_int(sample_without_replacement) -> None: ...
def check_sample_int(sample_without_replacement) -> None: ...
def check_sample_int_distribution(sample_without_replacement) -> None: ...
def test_random_choice_csc(n_samples: int = ..., random_state: int = ...) -> None: ...
def test_random_choice_csc_errors() -> None: ...
def test_our_rand_r() -> None: ...
