from sklearn.datasets import load_iris as load_iris
from sklearn.utils import check_array as check_array
from sklearn.utils._mocking import CheckingClassifier as CheckingClassifier

def iris(): ...
def test_check_on_fit_success(iris, kwargs) -> None: ...
def test_check_on_fit_fail(iris, kwargs) -> None: ...
def test_check_X_on_predict_success(iris, pred_func) -> None: ...
def test_check_X_on_predict_fail(iris, pred_func) -> None: ...
def test_checking_classifier(iris, input_type) -> None: ...
def test_checking_classifier_with_params(iris) -> None: ...
def test_checking_classifier_fit_params(iris) -> None: ...
def test_checking_classifier_missing_fit_params(iris) -> None: ...
def test_checking_classifier_methods_to_check(iris, methods_to_check, predict_method) -> None: ...
