from statsmodels.tsa.arima_process import ArmaProcess as ArmaProcess
from typing import Any

class ArmaFft(ArmaProcess):
    ar: Any
    ma: Any
    nobs: Any
    arpoly: Any
    mapoly: Any
    nar: Any
    nma: Any
    def __init__(self, ar, ma, n) -> None: ...
    def padarr(self, arr, maxlag, atend: bool = ...): ...
    def pad(self, maxlag): ...
    def fftar(self, n: Any | None = ...): ...
    def fftma(self, n): ...
    def fftarma(self, n: Any | None = ...): ...
    def spd(self, npos): ...
    def spdshift(self, n): ...
    def spddirect(self, n): ...
    def spdroots(self, w): ...
    def spdpoly(self, w, nma: int = ...): ...
    def filter(self, x): ...
    def filter2(self, x, pad: int = ...): ...
    def acf2spdfreq(self, acovf, nfreq: int = ..., w: Any | None = ...): ...
    def invpowerspd(self, n): ...
    def spdmapoly(self, w, twosided: bool = ...): ...
    def plot4(self, fig: Any | None = ..., nobs: int = ..., nacf: int = ..., nfreq: int = ...): ...

def spdar1(ar, w): ...
