def movorder(x, order: str = ..., windsize: int = ..., lag: str = ...): ...
def movmean(x, windowsize: int = ..., lag: str = ...): ...
def movvar(x, windowsize: int = ..., lag: str = ...): ...
def movmoment(x, k, windowsize: int = ..., lag: str = ...): ...
