from tensorflow.python.eager import context as context
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.keras.optimizer_v2 import learning_rate_schedule as learning_rate_schedule
from tensorflow.python.ops import math_ops as math_ops
from tensorflow.python.util import nest as nest
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def exponential_decay(learning_rate, global_step, decay_steps, decay_rate, staircase: bool = ..., name: Any | None = ...): ...
def piecewise_constant(x, boundaries, values, name: Any | None = ...): ...
def polynomial_decay(learning_rate, global_step, decay_steps, end_learning_rate: float = ..., power: float = ..., cycle: bool = ..., name: Any | None = ...): ...
def natural_exp_decay(learning_rate, global_step, decay_steps, decay_rate, staircase: bool = ..., name: Any | None = ...): ...
def inverse_time_decay(learning_rate, global_step, decay_steps, decay_rate, staircase: bool = ..., name: Any | None = ...): ...
def cosine_decay(learning_rate, global_step, decay_steps, alpha: float = ..., name: Any | None = ...): ...
def cosine_decay_restarts(learning_rate, global_step, first_decay_steps, t_mul: float = ..., m_mul: float = ..., alpha: float = ..., name: Any | None = ...): ...
def linear_cosine_decay(learning_rate, global_step, decay_steps, num_periods: float = ..., alpha: float = ..., beta: float = ..., name: Any | None = ...): ...
def noisy_linear_cosine_decay(learning_rate, global_step, decay_steps, initial_variance: float = ..., variance_decay: float = ..., num_periods: float = ..., alpha: float = ..., beta: float = ..., name: Any | None = ...): ...
