from _typeshed import Incomplete
from nibabel.cifti2 import cifti2 as cifti2
from nibabel.cifti2 import cifti2_axes as cifti2_axes
from nibabel.tests.nibabel_data import get_nibabel_data as get_nibabel_data
from nibabel.tests.nibabel_data import needs_nibabel_data as needs_nibabel_data

test_directory: Incomplete
hcp_labels: Incomplete
hcp_n_elements: Incomplete
hcp_affine: Incomplete

def check_hcp_grayordinates(brain_model) -> None: ...
def check_Conte69(brain_model) -> None: ...
def check_rewrite(arr, axes, extension: str = ".nii"): ...
def test_read_ones() -> None: ...
def test_read_conte69_dscalar() -> None: ...
def test_read_conte69_dtseries() -> None: ...
def test_read_conte69_dlabel() -> None: ...
def test_read_conte69_ptseries() -> None: ...
