from _typeshed import Incomplete
from nibabel.tmpdirs import InTemporaryDirectory as InTemporaryDirectory

from ...testing import assert_array_equal as assert_array_equal
from ...testing import clear_and_catch_warnings as clear_and_catch_warnings
from ...testing import error_warnings as error_warnings
from ...testing import suppress_warnings as suppress_warnings

affine: Incomplete
dimensions: Incomplete
number_of_vertices: int
brain_models: Incomplete

def create_geometry_map(applies_to_matrix_dimension): ...
def check_geometry_map(mapping) -> None: ...

parcels: Incomplete

def create_parcel_map(applies_to_matrix_dimension): ...
def check_parcel_map(mapping) -> None: ...

scalars: Incomplete

def create_scalar_map(applies_to_matrix_dimension): ...
def check_scalar_map(mapping) -> None: ...

labels: Incomplete

def create_label_map(applies_to_matrix_dimension): ...
def check_label_map(mapping) -> None: ...
def create_series_map(applies_to_matrix_dimension): ...
def check_series_map(mapping) -> None: ...
def test_dtseries() -> None: ...
def test_dscalar() -> None: ...
def test_dlabel() -> None: ...
def test_dconn() -> None: ...
def test_ptseries() -> None: ...
def test_pscalar() -> None: ...
def test_pdconn() -> None: ...
def test_dpconn() -> None: ...
def test_plabel() -> None: ...
def test_pconn() -> None: ...
def test_pconnseries() -> None: ...
def test_pconnscalar() -> None: ...
def test_wrong_shape() -> None: ...
