from _typeshed import Incomplete
from nibabel import cifti2 as ci
from nibabel.cifti2.cifti2 import Cifti2HeaderError as Cifti2HeaderError
from nibabel.nifti2 import Nifti2Header as Nifti2Header
from nibabel.tests.test_dataobj_images import TestDataobjAPI as _TDA
from nibabel.tests.test_image_api import DtypeOverrideMixin as DtypeOverrideMixin
from nibabel.tests.test_image_api import SerializeMixin as SerializeMixin

def compare_xml_leaf(str1, str2): ...
def test_value_if_klass() -> None: ...
def test_cifti2_metadata() -> None: ...
def test__float_01() -> None: ...
def test_cifti2_labeltable() -> None: ...
def test_cifti2_label() -> None: ...
def test_cifti2_parcel() -> None: ...
def test_cifti2_vertices() -> None: ...
def test_cifti2_transformationmatrixvoxelindicesijktoxyz() -> None: ...
def test_cifti2_surface() -> None: ...
def test_cifti2_volume() -> None: ...
def test_cifti2_vertexindices() -> None: ...
def test_cifti2_voxelindicesijk() -> None: ...
def test_matrixindicesmap() -> None: ...
def test_matrix() -> None: ...
def test_underscoring() -> None: ...

class TestCifti2ImageAPI(_TDA, SerializeMixin, DtypeOverrideMixin):
    image_maker = ci.Cifti2Image
    header_maker = ci.Cifti2Header
    ni_header_maker = Nifti2Header
    example_shapes: Incomplete
    standard_extension: str
    storable_dtypes: Incomplete
    def make_imaker(
        self, arr, header: Incomplete | None = None, ni_header: Incomplete | None = None
    ): ...
