from _typeshed import Incomplete
from nibabel.tests import test_nifti2 as tn2
from nibabel.tests.nibabel_data import get_nibabel_data as get_nibabel_data
from nibabel.tests.nibabel_data import needs_nibabel_data as needs_nibabel_data
from nibabel.tmpdirs import InTemporaryDirectory as InTemporaryDirectory

NIBABEL_TEST_DATA: Incomplete
NIFTI2_DATA: Incomplete
CIFTI2_DATA: Incomplete
DATA_FILE1: Incomplete
DATA_FILE2: Incomplete
DATA_FILE3: Incomplete
DATA_FILE4: Incomplete
DATA_FILE5: Incomplete
DATA_FILE6: Incomplete
datafiles: Incomplete

def test_space_separated_affine() -> None: ...
def test_read_nifti2() -> None: ...
def test_read_internal() -> None: ...
def test_read_and_proxies() -> None: ...
def test_version() -> None: ...
def test_readwritedata() -> None: ...
def test_nibabel_readwritedata() -> None: ...
def test_cifti2types() -> None: ...
def test_read_geometry() -> None: ...
def test_read_parcels() -> None: ...
def test_read_scalar() -> None: ...
def test_read_series() -> None: ...
def test_read_labels() -> None: ...

class TestCifti2SingleHeader(tn2.TestNifti2SingleHeader):
    header_class: Incomplete
    def test_pixdim_checks(self) -> None: ...
    def test_nifti_qfac_checks(self) -> None: ...
    def test_pixdim_log_checks(self) -> None: ...
