from sklearn.compose import make_column_transformer as make_column_transformer
from sklearn.datasets import load_breast_cancer as load_breast_cancer, make_classification as make_classification
from sklearn.exceptions import NotFittedError as NotFittedError
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.metrics import PrecisionRecallDisplay as PrecisionRecallDisplay, average_precision_score as average_precision_score, plot_precision_recall_curve as plot_precision_recall_curve, precision_recall_curve as precision_recall_curve
from sklearn.model_selection import train_test_split as train_test_split
from sklearn.pipeline import make_pipeline as make_pipeline
from sklearn.preprocessing import StandardScaler as StandardScaler
from sklearn.svm import SVC as SVC, SVR as SVR
from sklearn.utils import shuffle as shuffle
from typing import Any

pytestmark: Any

def test_precision_recall_display_validation(pyplot) -> None: ...
def test_plot_precision_recall_curve_deprecation(pyplot) -> None: ...
def test_precision_recall_display_plotting(pyplot, constructor_name, response_method) -> None: ...
def test_precision_recall_display_name(pyplot, constructor_name, default_label) -> None: ...
def test_precision_recall_display_pipeline(pyplot, clf) -> None: ...
def test_precision_recall_display_string_labels(pyplot) -> None: ...
def test_default_labels(pyplot, average_precision, estimator_name, expected_label) -> None: ...
def test_plot_precision_recall_pos_label(pyplot, constructor_name, response_method) -> None: ...
