from sklearn.compose import make_column_transformer as make_column_transformer
from sklearn.datasets import make_classification as make_classification
from sklearn.exceptions import NotFittedError as NotFittedError
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.metrics import ConfusionMatrixDisplay as ConfusionMatrixDisplay, confusion_matrix as confusion_matrix
from sklearn.pipeline import make_pipeline as make_pipeline
from sklearn.preprocessing import StandardScaler as StandardScaler
from sklearn.svm import SVC as SVC, SVR as SVR
from typing import Any

pytestmark: Any

def test_confusion_matrix_display_validation(pyplot) -> None: ...
def test_confusion_matrix_display_invalid_option(pyplot, constructor_name) -> None: ...
def test_confusion_matrix_display_custom_labels(pyplot, constructor_name, with_labels, with_display_labels) -> None: ...
def test_confusion_matrix_display_plotting(pyplot, constructor_name, normalize, include_values) -> None: ...
def test_confusion_matrix_display(pyplot, constructor_name) -> None: ...
def test_confusion_matrix_contrast(pyplot) -> None: ...
def test_confusion_matrix_pipeline(pyplot, clf) -> None: ...
def test_confusion_matrix_with_unknown_labels(pyplot, constructor_name) -> None: ...
def test_colormap_max(pyplot) -> None: ...
