from sklearn.compose import make_column_transformer as make_column_transformer
from sklearn.datasets import load_breast_cancer as load_breast_cancer, load_iris as load_iris, make_classification as make_classification
from sklearn.exceptions import NotFittedError as NotFittedError
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.metrics import RocCurveDisplay as RocCurveDisplay, auc as auc, plot_roc_curve as plot_roc_curve, roc_curve as roc_curve
from sklearn.model_selection import train_test_split as train_test_split
from sklearn.pipeline import make_pipeline as make_pipeline
from sklearn.preprocessing import StandardScaler as StandardScaler
from sklearn.utils import shuffle as shuffle

def data(): ...
def data_binary(data): ...
def test_roc_curve_display_plotting(pyplot, response_method, data_binary, with_sample_weight, drop_intermediate, with_strings, constructor_name, default_name) -> None: ...
def test_roc_curve_display_complex_pipeline(pyplot, data_binary, clf, constructor_name) -> None: ...
def test_roc_curve_display_default_labels(pyplot, roc_auc, estimator_name, expected_label) -> None: ...
def test_plot_roc_curve_pos_label(pyplot, response_method, constructor_name) -> None: ...
def test_plot_precision_recall_curve_deprecation(pyplot) -> None: ...
