from sklearn.datasets import load_iris as load_iris
from sklearn.linear_model import LogisticRegression as LogisticRegression
from sklearn.metrics import det_curve as det_curve, plot_det_curve as plot_det_curve

def data(): ...
def data_binary(data): ...
def test_plot_det_curve(pyplot, response_method, data_binary, with_sample_weight, with_strings) -> None: ...
