from tensorflow.python.framework import tensor_util as tensor_util
from tensorflow.python.ops import control_flow_ops as control_flow_ops, gen_math_ops as gen_math_ops

def not_(a): ...
def and_(a, b): ...
def or_(a, b): ...
def eq(a, b): ...
def not_eq(a, b): ...
