from typing import Any

def ld(v): ...
def ldu(load_v, name): ...

class Undefined:
    symbol_name: Any
    def __init__(self, symbol_name) -> None: ...
    def read(self) -> None: ...
    def __getattribute__(self, name): ...
    def __getitem__(self, i): ...

class UndefinedReturnValue: ...
