from docutils.parsers.rst import Directive
from matplotlib import cbook as cbook
from matplotlib.backend_bases import FigureManagerBase as FigureManagerBase
from typing import Any

align: Any

def mark_plot_labels(app, document) -> None: ...

class PlotDirective(Directive):
    has_content: bool
    required_arguments: int
    optional_arguments: int
    final_argument_whitespace: bool
    option_spec: Any
    def run(self): ...

def setup(app): ...
def contains_doctest(text): ...
def unescape_doctest(text): ...
def split_code_at_show(text): ...

TEMPLATE: str
exception_template: str
plot_context: Any

class ImageFile:
    basename: Any
    dirname: Any
    formats: Any
    def __init__(self, basename, dirname) -> None: ...
    def filename(self, format): ...
    def filenames(self): ...

def out_of_date(original, derived, includes: Any | None = ...): ...

class PlotError(RuntimeError): ...

def run_code(code, code_path, ns: Any | None = ..., function_name: Any | None = ...) -> None: ...
def clear_state(plot_rcparams, close: bool = ...) -> None: ...
def get_plot_formats(config): ...
def render_figures(code, code_path, output_dir, output_base, context, function_name, config, context_reset: bool = ..., close_figs: bool = ..., code_includes: Any | None = ...): ...
def run(arguments, content, options, state_machine, state, lineno): ...
