class Field:
    NB_STREAMLINES: str
    STEP_SIZE: str
    METHOD: str
    NB_SCALARS_PER_POINT: str
    NB_PROPERTIES_PER_STREAMLINE: str
    NB_POINTS: str
    VOXEL_SIZES: str
    DIMENSIONS: str
    MAGIC_NUMBER: str
    ORIGIN: str
    VOXEL_TO_RASMM: str
    VOXEL_ORDER: str
    ENDIANNESS: str
