from contextlib import nullcontext as nullcontext

from _typeshed import Incomplete

from ..casting import FloatingError as FloatingError
from ..casting import ceil_exact as ceil_exact
from ..casting import floor_exact as floor_exact
from ..casting import floor_log2 as floor_log2
from ..casting import have_binary128 as have_binary128
from ..casting import longdouble_precision_improved as longdouble_precision_improved
from ..casting import ok_floats as ok_floats
from ..casting import on_powerpc as on_powerpc
from ..casting import sctypes as sctypes
from ..casting import type_info as type_info
from ..testing import suppress_warnings as suppress_warnings

IEEE_floats: Incomplete
LD_INFO: Incomplete
FP_OVERFLOW_WARN: Incomplete

def dtt2dict(dtt): ...
def test_type_info() -> None: ...
def test_nmant() -> None: ...
def test_check_nmant_nexp() -> None: ...
def test_int_longdouble_np_regression() -> None: ...
def test_int_np_regression() -> None: ...
def test_floor_exact_16() -> None: ...
def test_floor_exact_64() -> None: ...
def test_floor_exact(max_digits): ...
def test_usable_binary128() -> None: ...
