from nibabel.pkg_info import cmp_pkg_version as cmp_pkg_version

def test_pkg_info() -> None: ...
def test_version() -> None: ...
def test_cmp_pkg_version_0() -> None: ...
def test_cmp_pkg_version_1(test_ver, pkg_ver, exp_out) -> None: ...
def test_cmp_pkg_version_error(args) -> None: ...
