from _typeshed import Incomplete

from ..pkg_info import cmp_pkg_version as cmp_pkg_version

MODULE_SCHEDULE: Incomplete
OBJECT_SCHEDULE: Incomplete
ATTRIBUTE_SCHEDULE: Incomplete

def test_module_removal() -> None: ...
def test_object_removal() -> None: ...
def test_attribute_removal() -> None: ...
def test_unremoved_module() -> None: ...
def test_unremoved_object() -> None: ...
def test_unremoved_attr() -> None: ...
