from _typeshed import Incomplete

from ..casting import sctypes as sctypes
from ..testing import assert_allclose_safely as assert_allclose_safely
from ..testing import assert_re_in as assert_re_in
from ..testing import clear_and_catch_warnings as clear_and_catch_warnings
from ..testing import data_path as data_path
from ..testing import error_warnings as error_warnings
from ..testing import get_fresh_mod as get_fresh_mod
from ..testing import get_test_data as get_test_data
from ..testing import suppress_warnings as suppress_warnings

def test_assert_allclose_safely() -> None: ...
def assert_warn_len_equal(mod, n_in_context) -> None: ...
def test_clear_and_catch_warnings() -> None: ...

class my_cacw(clear_and_catch_warnings):
    class_modules: Incomplete

def test_clear_and_catch_warnings_inherit() -> None: ...
def test_warn_error() -> None: ...
def test_warn_ignore() -> None: ...
def test_assert_re_in(regex, entries) -> None: ...
def test_test_data() -> None: ...
