from ..volumeutils import DtypeMapper as DtypeMapper
from ..volumeutils import Recoder as Recoder
from ..volumeutils import native_code as native_code
from ..volumeutils import swapped_code as swapped_code

def test_recoder_1() -> None: ...
def test_recoder_2() -> None: ...
def test_recoder_3() -> None: ...
def test_recoder_4() -> None: ...
def test_recoder_5() -> None: ...
def test_recoder_6() -> None: ...
def test_custom_dicter(): ...
def test_add_codes() -> None: ...
def test_sugar() -> None: ...
def test_dtmapper() -> None: ...
