from _typeshed import Incomplete
from nibabel.cmdline.diff import are_values_different as are_values_different

DATA_PATH: Incomplete

def test_diff_values_int() -> None: ...
def test_diff_values_float() -> None: ...
def test_diff_values_mixed() -> None: ...
def test_diff_values_array() -> None: ...
