from _typeshed import Incomplete

from ..arraywriters import ArrayWriter as ArrayWriter
from ..arraywriters import ScalingError as ScalingError
from ..arraywriters import SlopeArrayWriter as SlopeArrayWriter
from ..arraywriters import SlopeInterArrayWriter as SlopeInterArrayWriter
from ..arraywriters import WriterError as WriterError
from ..arraywriters import get_slope_inter as get_slope_inter
from ..arraywriters import make_array_writer as make_array_writer
from ..casting import int_abs as int_abs
from ..casting import sctypes as sctypes
from ..casting import shared_range as shared_range
from ..casting import type_info as type_info
from ..testing import assert_allclose_safely as assert_allclose_safely
from ..testing import suppress_warnings as suppress_warnings
from ..volumeutils import apply_read_scaling as apply_read_scaling
from ..volumeutils import array_from_file as array_from_file

FLOAT_TYPES: Incomplete
COMPLEX_TYPES: Incomplete
INT_TYPES: Incomplete
UINT_TYPES: Incomplete
CFLOAT_TYPES: Incomplete
IUINT_TYPES: Incomplete
NUMERIC_TYPES: Incomplete

def round_trip(writer, order: str = "F", apply_scale: bool = True): ...
def test_arraywriters() -> None: ...
def test_arraywriter_check_scaling() -> None: ...
def test_no_scaling() -> None: ...
def test_scaling_needed() -> None: ...
def test_special_rt() -> None: ...
def test_high_int2uint() -> None: ...
def test_slope_inter_castable() -> None: ...
def test_calculate_scale() -> None: ...
def test_resets() -> None: ...
def test_no_offset_scale() -> None: ...
def test_with_offset_scale() -> None: ...
def test_io_scaling() -> None: ...
def test_input_ranges() -> None: ...
def test_nan2zero() -> None: ...
def test_byte_orders() -> None: ...
def test_writers_roundtrip() -> None: ...
def test_to_float() -> None: ...
def test_dumber_writers() -> None: ...
def test_writer_maker() -> None: ...
def test_float_int_min_max() -> None: ...
def test_int_int_min_max() -> None: ...
def test_int_int_slope() -> None: ...
def test_float_int_spread() -> None: ...
def rt_err_estimate(arr_t, out_dtype, slope, inter): ...
def test_rt_bias() -> None: ...
def test_nan2zero_scaling() -> None: ...
def test_finite_range_nan() -> None: ...
