from collections.abc import Generator

from _typeshed import Incomplete

from .. import dft as dft
from .. import nifti1 as nifti1
from ..optpkg import optional_package as optional_package
from ..testing import suppress_warnings as suppress_warnings

have_dicom: Incomplete
PImage: Incomplete
have_pil: Incomplete
_: Incomplete
data_dir: Incomplete

def setUpModule() -> None: ...

class Test_DBclass:
    def setup_method(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_cursor_conflict(self) -> None: ...

def db(monkeypatch) -> Generator[Incomplete, None, None]: ...
def test_init(db) -> None: ...
def test_study(db) -> None: ...
def test_series(db) -> None: ...
def test_storage_instances(db) -> None: ...
def test_png(db) -> None: ...
def test_nifti(db) -> None: ...
