from ..casting import CastingError as CastingError
from ..casting import able_int_type as able_int_type
from ..casting import best_float as best_float
from ..casting import float_to_int as float_to_int
from ..casting import floor_log2 as floor_log2
from ..casting import int_abs as int_abs
from ..casting import longdouble_precision_improved as longdouble_precision_improved
from ..casting import sctypes as sctypes
from ..casting import shared_range as shared_range
from ..casting import ulp as ulp
from ..testing import suppress_warnings as suppress_warnings

def test_shared_range() -> None: ...
def test_shared_range_inputs() -> None: ...
def test_casting() -> None: ...
def test_int_abs() -> None: ...
def test_floor_log2() -> None: ...
def test_able_int_type() -> None: ...
def test_able_casting() -> None: ...
def test_best_float() -> None: ...
def test_longdouble_precision_improved() -> None: ...
def test_ulp() -> None: ...
