from _typeshed import Incomplete
from nibabel.deprecator import TESTCLEANUP as TESTCLEANUP
from nibabel.deprecator import TESTSETUP as TESTSETUP
from nibabel.deprecator import Deprecator as Deprecator
from nibabel.deprecator import ExpiredDeprecationError as ExpiredDeprecationError

from ..testing import clear_and_catch_warnings as clear_and_catch_warnings

def test__ensure_cr() -> None: ...
def test__add_dep_doc() -> None: ...

class CustomError(Exception): ...

def cmp_func(v): ...
def func_no_doc() -> None: ...
def func_doc(i) -> None: ...
def func_doc_long(i, j) -> None: ...

class TestDeprecatorFunc:
    dep_func: Incomplete
    def test_dep_func(self): ...

class TestDeprecatorMaker:
    dep_maker: Incomplete
    def test_deprecator_maker(self) -> None: ...
