from _typeshed import Incomplete
from nibabel.optpkg import optional_package as optional_package
from nibabel.tripwire import TripWire as TripWire
from nibabel.tripwire import TripWireError as TripWireError

def assert_good(pkg_name, min_version: Incomplete | None = None) -> None: ...
def assert_bad(pkg_name, min_version: Incomplete | None = None) -> None: ...
def test_basic(): ...
def test_versions(): ...
