from collections.abc import Generator

from ..data import Bomber as Bomber
from ..data import DataError as DataError
from ..data import Datasource as Datasource
from ..data import VersionedDatasource as VersionedDatasource
from ..data import datasource_or_bomber as datasource_or_bomber
from ..data import find_data_dir as find_data_dir
from ..data import get_data_path as get_data_path
from ..data import make_datasource as make_datasource
from .test_environment import DATA_KEY as DATA_KEY
from .test_environment import USER_KEY as USER_KEY
from .test_environment import with_environment as with_environment

def with_nimd_env(request, with_environment) -> Generator[None, None, None]: ...
def test_datasource() -> None: ...
def test_versioned() -> None: ...
def test__cfg_value() -> None: ...
def test_data_path(with_nimd_env): ...
def test_find_data_dir() -> None: ...
def test_make_datasource(with_nimd_env): ...
def test_bomber() -> None: ...
def test_bomber_inspect() -> None: ...
def test_datasource_or_bomber(with_nimd_env): ...
