from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import math_ops as math_ops
from typing import Any

def assert_finite(array) -> None: ...
def assert_strictly_increasing(array) -> None: ...
def assert_strictly_decreasing(array) -> None: ...
def assert_strictly_monotonic(array) -> None: ...
def assert_scalar_congruency(bijector, lower_x, upper_x, n=..., rtol: float = ..., sess: Any | None = ...) -> None: ...
def assert_bijective_and_finite(bijector, x, y, event_ndims, atol: int = ..., rtol: float = ..., sess: Any | None = ...) -> None: ...
