def ndtr(x, name: str = ...): ...
def ndtri(p, name: str = ...): ...
def log_ndtr(x, series_order: int = ..., name: str = ...): ...
def erfinv(x, name: str = ...): ...
def log_cdf_laplace(x, name: str = ...): ...
