from tensorflow.python.debug.cli import cli_config as cli_config, cli_shared as cli_shared, command_parser as command_parser, debugger_cli_common as debugger_cli_common, evaluator as evaluator, ui_factory as ui_factory
from tensorflow.python.debug.lib import debug_graphs as debug_graphs, source_utils as source_utils
from typing import Any

RL: Any
HANG_UNFINISHED: str
HANG_FINISHED: str
HANG_SUFFIX: str
DEPTH_TEMPLATE: str
OP_TYPE_TEMPLATE: str
CTRL_LABEL: str
ELLIPSIS: str
SORT_TENSORS_BY_TIMESTAMP: str
SORT_TENSORS_BY_DUMP_SIZE: str
SORT_TENSORS_BY_OP_TYPE: str
SORT_TENSORS_BY_TENSOR_NAME: str

class DebugAnalyzer:
    def __init__(self, debug_dump, config) -> None: ...
    def add_tensor_filter(self, filter_name, filter_callable) -> None: ...
    def get_tensor_filter(self, filter_name): ...
    def get_help(self, handler_name): ...
    def list_tensors(self, args, screen_info: Any | None = ...): ...
    def node_info(self, args, screen_info: Any | None = ...): ...
    def list_inputs(self, args, screen_info: Any | None = ...): ...
    def print_tensor(self, args, screen_info: Any | None = ...): ...
    def list_outputs(self, args, screen_info: Any | None = ...): ...
    def evaluate_expression(self, args, screen_info: Any | None = ...): ...
    def print_source(self, args, screen_info: Any | None = ...): ...
    def list_source(self, args, screen_info: Any | None = ...): ...

def create_analyzer_ui(debug_dump, tensor_filters: Any | None = ..., ui_type: str = ..., on_ui_exit: Any | None = ..., config: Any | None = ...): ...
