from tensorflow.python.debug.cli import cli_config as cli_config, command_parser as command_parser, debugger_cli_common as debugger_cli_common
from typing import Any

class BaseUI:
    CLI_PROMPT: str
    CLI_EXIT_COMMANDS: Any
    ERROR_MESSAGE_PREFIX: str
    INFO_MESSAGE_PREFIX: str
    def __init__(self, on_ui_exit: Any | None = ..., config: Any | None = ...) -> None: ...
    def set_help_intro(self, help_intro) -> None: ...
    def register_command_handler(self, prefix, handler, help_info, prefix_aliases: Any | None = ...) -> None: ...
    def register_tab_comp_context(self, *args, **kwargs) -> None: ...
    def run_ui(self, init_command: Any | None = ..., title: Any | None = ..., title_color: Any | None = ..., enable_mouse_on_start: bool = ...) -> None: ...
    @property
    def config(self): ...
