from typing import Any

def inplace_identity(X) -> None: ...
def inplace_logistic(X) -> None: ...
def inplace_tanh(X) -> None: ...
def inplace_relu(X) -> None: ...
def inplace_softmax(X) -> None: ...

ACTIVATIONS: Any

def inplace_identity_derivative(Z, delta) -> None: ...
def inplace_logistic_derivative(Z, delta) -> None: ...
def inplace_tanh_derivative(Z, delta) -> None: ...
def inplace_relu_derivative(Z, delta) -> None: ...

DERIVATIVES: Any

def squared_loss(y_true, y_pred): ...
def log_loss(y_true, y_prob): ...
def binary_log_loss(y_true, y_prob): ...

LOSS_FUNCTIONS: Any
