from typing import Any

def violinplot(data, ax: Any | None = ..., labels: Any | None = ..., positions: Any | None = ..., side: str = ..., show_boxplot: bool = ..., plot_opts: Any | None = ...): ...
def beanplot(data, ax: Any | None = ..., labels: Any | None = ..., positions: Any | None = ..., side: str = ..., jitter: bool = ..., plot_opts=...): ...
