from . import utils as utils
from typing import Any

def plot_corr(dcorr, xnames: Any | None = ..., ynames: Any | None = ..., title: Any | None = ..., normcolor: bool = ..., ax: Any | None = ..., cmap: str = ...): ...
def plot_corr_grid(dcorrs, titles: Any | None = ..., ncols: Any | None = ..., normcolor: bool = ..., xnames: Any | None = ..., ynames: Any | None = ..., fig: Any | None = ..., cmap: str = ...): ...
