from typing import Any

class HdrResults:
    def __init__(self, kwds) -> None: ...

def hdrboxplot(data, ncomp: int = ..., alpha: Any | None = ..., threshold: float = ..., bw: Any | None = ..., xdata: Any | None = ..., labels: Any | None = ..., ax: Any | None = ..., use_brute: bool = ..., seed: Any | None = ...): ...
def fboxplot(data, xdata: Any | None = ..., labels: Any | None = ..., depth: Any | None = ..., method: str = ..., wfactor: float = ..., ax: Any | None = ..., plot_opts: Any | None = ...): ...
def rainbowplot(data, xdata: Any | None = ..., depth: Any | None = ..., method: str = ..., ax: Any | None = ..., cmap: Any | None = ...): ...
def banddepth(data, method: str = ...): ...
