from statsmodels.compat.pandas import deprecate_kwarg as deprecate_kwarg
from statsmodels.graphics import utils as utils
from statsmodels.tsa.stattools import acf as acf, pacf as pacf
from typing import Any

def plot_acf(x, ax: Any | None = ..., lags: Any | None = ..., *, alpha: float = ..., use_vlines: bool = ..., adjusted: bool = ..., fft: bool = ..., missing: str = ..., title: str = ..., zero: bool = ..., auto_ylims: bool = ..., bartlett_confint: bool = ..., vlines_kwargs: Any | None = ..., **kwargs): ...
def plot_pacf(x, ax: Any | None = ..., lags: Any | None = ..., alpha: float = ..., method: Any | None = ..., use_vlines: bool = ..., title: str = ..., zero: bool = ..., vlines_kwargs: Any | None = ..., **kwargs): ...
def seasonal_plot(grouped_x, xticklabels, ylabel: Any | None = ..., ax: Any | None = ...): ...
def month_plot(x, dates: Any | None = ..., ylabel: Any | None = ..., ax: Any | None = ...): ...
def quarter_plot(x, dates: Any | None = ..., ylabel: Any | None = ..., ax: Any | None = ...): ...
def plot_predict(result, start: Any | None = ..., end: Any | None = ..., dynamic: bool = ..., alpha: float = ..., ax: Any | None = ..., **predict_kwargs): ...
