from tensorflow.core.util import event_pb2 as event_pb2
from tensorflow.python.lib.io import tf_record as tf_record
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

class _SummaryIterator:
    def __init__(self, path) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    next: Any

def summary_iterator(path): ...
