from sklearn.ensemble._hist_gradient_boosting.common import G_H_DTYPE as G_H_DTYPE, HISTOGRAM_DTYPE as HISTOGRAM_DTYPE, MonotonicConstraint as MonotonicConstraint, X_BINNED_DTYPE as X_BINNED_DTYPE
from sklearn.ensemble._hist_gradient_boosting.histogram import HistogramBuilder as HistogramBuilder
from sklearn.ensemble._hist_gradient_boosting.splitting import Splitter as Splitter, compute_node_value as compute_node_value
from sklearn.utils._testing import skip_if_32bit as skip_if_32bit
from typing import Any

n_threads: Any

def test_histogram_split(n_bins) -> None: ...
def test_gradient_and_hessian_sanity(constant_hessian) -> None: ...
def test_split_indices() -> None: ...
def test_min_gain_to_split() -> None: ...
def test_splitting_missing_values(X_binned, all_gradients, has_missing_values, n_bins_non_missing, expected_split_on_nan, expected_bin_idx, expected_go_to_left) -> None: ...
def test_splitting_categorical_cat_smooth(X_binned, has_missing_values, n_bins_non_missing) -> None: ...
def test_splitting_categorical_sanity(X_binned, all_gradients, expected_categories_left, n_bins_non_missing, missing_values_bin_idx, has_missing_values, expected_missing_go_to_left) -> None: ...
