from sklearn.ensemble import HistGradientBoostingClassifier as HistGradientBoostingClassifier, HistGradientBoostingRegressor as HistGradientBoostingRegressor
from sklearn.ensemble._hist_gradient_boosting.common import G_H_DTYPE as G_H_DTYPE, MonotonicConstraint as MonotonicConstraint, X_BINNED_DTYPE as X_BINNED_DTYPE
from sklearn.ensemble._hist_gradient_boosting.grower import TreeGrower as TreeGrower
from sklearn.ensemble._hist_gradient_boosting.histogram import HistogramBuilder as HistogramBuilder
from sklearn.ensemble._hist_gradient_boosting.splitting import Splitter as Splitter, compute_node_value as compute_node_value
from typing import Any

n_threads: Any

def is_increasing(a): ...
def is_decreasing(a): ...
def assert_leaves_values_monotonic(predictor, monotonic_cst): ...
def assert_children_values_monotonic(predictor, monotonic_cst) -> None: ...
def assert_children_values_bounded(grower, monotonic_cst) -> None: ...
def test_nodes_values(monotonic_cst, seed) -> None: ...
def test_predictions(seed) -> None: ...
def test_input_error() -> None: ...
def test_bounded_value_min_gain_to_split() -> None: ...
