from sklearn.ensemble._hist_gradient_boosting.common import G_H_DTYPE as G_H_DTYPE, HISTOGRAM_DTYPE as HISTOGRAM_DTYPE, X_BINNED_DTYPE as X_BINNED_DTYPE

def test_build_histogram(build_func) -> None: ...
def test_histogram_sample_order_independence() -> None: ...
def test_unrolled_equivalent_to_naive(constant_hessian) -> None: ...
def test_hist_subtraction(constant_hessian) -> None: ...
