from typing import Any

def simple_function(x): ...
def nested_functions(x): ...
def function_with_print() -> None: ...

simple_lambda: Any

class SimpleClass:
    def simple_method(self): ...
    def method_with_print(self) -> None: ...

def function_with_multiline_call(x): ...
def basic_decorator(f): ...
def decorated_function(x): ...
